
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Buch` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model Buch
 * 
 */
export type BuchModel = runtime.Types.Result.DefaultSelection<Prisma.$BuchPayload>

export type AggregateBuch = {
  _count: BuchCountAggregateOutputType | null
  _avg: BuchAvgAggregateOutputType | null
  _sum: BuchSumAggregateOutputType | null
  _min: BuchMinAggregateOutputType | null
  _max: BuchMaxAggregateOutputType | null
}

export type BuchAvgAggregateOutputType = {
  id: number | null
  abteilungId: number | null
}

export type BuchSumAggregateOutputType = {
  id: number | null
  abteilungId: number | null
}

export type BuchMinAggregateOutputType = {
  id: number | null
  titel: string | null
  autor: string | null
  abteilungId: number | null
}

export type BuchMaxAggregateOutputType = {
  id: number | null
  titel: string | null
  autor: string | null
  abteilungId: number | null
}

export type BuchCountAggregateOutputType = {
  id: number
  titel: number
  autor: number
  abteilungId: number
  _all: number
}


export type BuchAvgAggregateInputType = {
  id?: true
  abteilungId?: true
}

export type BuchSumAggregateInputType = {
  id?: true
  abteilungId?: true
}

export type BuchMinAggregateInputType = {
  id?: true
  titel?: true
  autor?: true
  abteilungId?: true
}

export type BuchMaxAggregateInputType = {
  id?: true
  titel?: true
  autor?: true
  abteilungId?: true
}

export type BuchCountAggregateInputType = {
  id?: true
  titel?: true
  autor?: true
  abteilungId?: true
  _all?: true
}

export type BuchAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Buch to aggregate.
   */
  where?: Prisma.BuchWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Buches to fetch.
   */
  orderBy?: Prisma.BuchOrderByWithRelationInput | Prisma.BuchOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.BuchWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Buches from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Buches.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Buches
  **/
  _count?: true | BuchCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: BuchAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: BuchSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: BuchMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: BuchMaxAggregateInputType
}

export type GetBuchAggregateType<T extends BuchAggregateArgs> = {
      [P in keyof T & keyof AggregateBuch]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateBuch[P]>
    : Prisma.GetScalarType<T[P], AggregateBuch[P]>
}




export type BuchGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.BuchWhereInput
  orderBy?: Prisma.BuchOrderByWithAggregationInput | Prisma.BuchOrderByWithAggregationInput[]
  by: Prisma.BuchScalarFieldEnum[] | Prisma.BuchScalarFieldEnum
  having?: Prisma.BuchScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: BuchCountAggregateInputType | true
  _avg?: BuchAvgAggregateInputType
  _sum?: BuchSumAggregateInputType
  _min?: BuchMinAggregateInputType
  _max?: BuchMaxAggregateInputType
}

export type BuchGroupByOutputType = {
  id: number
  titel: string
  autor: string
  abteilungId: number
  _count: BuchCountAggregateOutputType | null
  _avg: BuchAvgAggregateOutputType | null
  _sum: BuchSumAggregateOutputType | null
  _min: BuchMinAggregateOutputType | null
  _max: BuchMaxAggregateOutputType | null
}

type GetBuchGroupByPayload<T extends BuchGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<BuchGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof BuchGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], BuchGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], BuchGroupByOutputType[P]>
      }
    >
  >



export type BuchWhereInput = {
  AND?: Prisma.BuchWhereInput | Prisma.BuchWhereInput[]
  OR?: Prisma.BuchWhereInput[]
  NOT?: Prisma.BuchWhereInput | Prisma.BuchWhereInput[]
  id?: Prisma.IntFilter<"Buch"> | number
  titel?: Prisma.StringFilter<"Buch"> | string
  autor?: Prisma.StringFilter<"Buch"> | string
  abteilungId?: Prisma.IntFilter<"Buch"> | number
  abteilung?: Prisma.XOR<Prisma.AbteilungScalarRelationFilter, Prisma.AbteilungWhereInput>
  exemplare?: Prisma.ExemplarListRelationFilter
}

export type BuchOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  titel?: Prisma.SortOrder
  autor?: Prisma.SortOrder
  abteilungId?: Prisma.SortOrder
  abteilung?: Prisma.AbteilungOrderByWithRelationInput
  exemplare?: Prisma.ExemplarOrderByRelationAggregateInput
}

export type BuchWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.BuchWhereInput | Prisma.BuchWhereInput[]
  OR?: Prisma.BuchWhereInput[]
  NOT?: Prisma.BuchWhereInput | Prisma.BuchWhereInput[]
  titel?: Prisma.StringFilter<"Buch"> | string
  autor?: Prisma.StringFilter<"Buch"> | string
  abteilungId?: Prisma.IntFilter<"Buch"> | number
  abteilung?: Prisma.XOR<Prisma.AbteilungScalarRelationFilter, Prisma.AbteilungWhereInput>
  exemplare?: Prisma.ExemplarListRelationFilter
}, "id">

export type BuchOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  titel?: Prisma.SortOrder
  autor?: Prisma.SortOrder
  abteilungId?: Prisma.SortOrder
  _count?: Prisma.BuchCountOrderByAggregateInput
  _avg?: Prisma.BuchAvgOrderByAggregateInput
  _max?: Prisma.BuchMaxOrderByAggregateInput
  _min?: Prisma.BuchMinOrderByAggregateInput
  _sum?: Prisma.BuchSumOrderByAggregateInput
}

export type BuchScalarWhereWithAggregatesInput = {
  AND?: Prisma.BuchScalarWhereWithAggregatesInput | Prisma.BuchScalarWhereWithAggregatesInput[]
  OR?: Prisma.BuchScalarWhereWithAggregatesInput[]
  NOT?: Prisma.BuchScalarWhereWithAggregatesInput | Prisma.BuchScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"Buch"> | number
  titel?: Prisma.StringWithAggregatesFilter<"Buch"> | string
  autor?: Prisma.StringWithAggregatesFilter<"Buch"> | string
  abteilungId?: Prisma.IntWithAggregatesFilter<"Buch"> | number
}

export type BuchCreateInput = {
  titel: string
  autor: string
  abteilung: Prisma.AbteilungCreateNestedOneWithoutBuecherInput
  exemplare?: Prisma.ExemplarCreateNestedManyWithoutBuchInput
}

export type BuchUncheckedCreateInput = {
  id?: number
  titel: string
  autor: string
  abteilungId: number
  exemplare?: Prisma.ExemplarUncheckedCreateNestedManyWithoutBuchInput
}

export type BuchUpdateInput = {
  titel?: Prisma.StringFieldUpdateOperationsInput | string
  autor?: Prisma.StringFieldUpdateOperationsInput | string
  abteilung?: Prisma.AbteilungUpdateOneRequiredWithoutBuecherNestedInput
  exemplare?: Prisma.ExemplarUpdateManyWithoutBuchNestedInput
}

export type BuchUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  titel?: Prisma.StringFieldUpdateOperationsInput | string
  autor?: Prisma.StringFieldUpdateOperationsInput | string
  abteilungId?: Prisma.IntFieldUpdateOperationsInput | number
  exemplare?: Prisma.ExemplarUncheckedUpdateManyWithoutBuchNestedInput
}

export type BuchCreateManyInput = {
  id?: number
  titel: string
  autor: string
  abteilungId: number
}

export type BuchUpdateManyMutationInput = {
  titel?: Prisma.StringFieldUpdateOperationsInput | string
  autor?: Prisma.StringFieldUpdateOperationsInput | string
}

export type BuchUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  titel?: Prisma.StringFieldUpdateOperationsInput | string
  autor?: Prisma.StringFieldUpdateOperationsInput | string
  abteilungId?: Prisma.IntFieldUpdateOperationsInput | number
}

export type BuchListRelationFilter = {
  every?: Prisma.BuchWhereInput
  some?: Prisma.BuchWhereInput
  none?: Prisma.BuchWhereInput
}

export type BuchOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type BuchCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  titel?: Prisma.SortOrder
  autor?: Prisma.SortOrder
  abteilungId?: Prisma.SortOrder
}

export type BuchAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  abteilungId?: Prisma.SortOrder
}

export type BuchMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  titel?: Prisma.SortOrder
  autor?: Prisma.SortOrder
  abteilungId?: Prisma.SortOrder
}

export type BuchMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  titel?: Prisma.SortOrder
  autor?: Prisma.SortOrder
  abteilungId?: Prisma.SortOrder
}

export type BuchSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  abteilungId?: Prisma.SortOrder
}

export type BuchScalarRelationFilter = {
  is?: Prisma.BuchWhereInput
  isNot?: Prisma.BuchWhereInput
}

export type BuchCreateNestedManyWithoutAbteilungInput = {
  create?: Prisma.XOR<Prisma.BuchCreateWithoutAbteilungInput, Prisma.BuchUncheckedCreateWithoutAbteilungInput> | Prisma.BuchCreateWithoutAbteilungInput[] | Prisma.BuchUncheckedCreateWithoutAbteilungInput[]
  connectOrCreate?: Prisma.BuchCreateOrConnectWithoutAbteilungInput | Prisma.BuchCreateOrConnectWithoutAbteilungInput[]
  createMany?: Prisma.BuchCreateManyAbteilungInputEnvelope
  connect?: Prisma.BuchWhereUniqueInput | Prisma.BuchWhereUniqueInput[]
}

export type BuchUncheckedCreateNestedManyWithoutAbteilungInput = {
  create?: Prisma.XOR<Prisma.BuchCreateWithoutAbteilungInput, Prisma.BuchUncheckedCreateWithoutAbteilungInput> | Prisma.BuchCreateWithoutAbteilungInput[] | Prisma.BuchUncheckedCreateWithoutAbteilungInput[]
  connectOrCreate?: Prisma.BuchCreateOrConnectWithoutAbteilungInput | Prisma.BuchCreateOrConnectWithoutAbteilungInput[]
  createMany?: Prisma.BuchCreateManyAbteilungInputEnvelope
  connect?: Prisma.BuchWhereUniqueInput | Prisma.BuchWhereUniqueInput[]
}

export type BuchUpdateManyWithoutAbteilungNestedInput = {
  create?: Prisma.XOR<Prisma.BuchCreateWithoutAbteilungInput, Prisma.BuchUncheckedCreateWithoutAbteilungInput> | Prisma.BuchCreateWithoutAbteilungInput[] | Prisma.BuchUncheckedCreateWithoutAbteilungInput[]
  connectOrCreate?: Prisma.BuchCreateOrConnectWithoutAbteilungInput | Prisma.BuchCreateOrConnectWithoutAbteilungInput[]
  upsert?: Prisma.BuchUpsertWithWhereUniqueWithoutAbteilungInput | Prisma.BuchUpsertWithWhereUniqueWithoutAbteilungInput[]
  createMany?: Prisma.BuchCreateManyAbteilungInputEnvelope
  set?: Prisma.BuchWhereUniqueInput | Prisma.BuchWhereUniqueInput[]
  disconnect?: Prisma.BuchWhereUniqueInput | Prisma.BuchWhereUniqueInput[]
  delete?: Prisma.BuchWhereUniqueInput | Prisma.BuchWhereUniqueInput[]
  connect?: Prisma.BuchWhereUniqueInput | Prisma.BuchWhereUniqueInput[]
  update?: Prisma.BuchUpdateWithWhereUniqueWithoutAbteilungInput | Prisma.BuchUpdateWithWhereUniqueWithoutAbteilungInput[]
  updateMany?: Prisma.BuchUpdateManyWithWhereWithoutAbteilungInput | Prisma.BuchUpdateManyWithWhereWithoutAbteilungInput[]
  deleteMany?: Prisma.BuchScalarWhereInput | Prisma.BuchScalarWhereInput[]
}

export type BuchUncheckedUpdateManyWithoutAbteilungNestedInput = {
  create?: Prisma.XOR<Prisma.BuchCreateWithoutAbteilungInput, Prisma.BuchUncheckedCreateWithoutAbteilungInput> | Prisma.BuchCreateWithoutAbteilungInput[] | Prisma.BuchUncheckedCreateWithoutAbteilungInput[]
  connectOrCreate?: Prisma.BuchCreateOrConnectWithoutAbteilungInput | Prisma.BuchCreateOrConnectWithoutAbteilungInput[]
  upsert?: Prisma.BuchUpsertWithWhereUniqueWithoutAbteilungInput | Prisma.BuchUpsertWithWhereUniqueWithoutAbteilungInput[]
  createMany?: Prisma.BuchCreateManyAbteilungInputEnvelope
  set?: Prisma.BuchWhereUniqueInput | Prisma.BuchWhereUniqueInput[]
  disconnect?: Prisma.BuchWhereUniqueInput | Prisma.BuchWhereUniqueInput[]
  delete?: Prisma.BuchWhereUniqueInput | Prisma.BuchWhereUniqueInput[]
  connect?: Prisma.BuchWhereUniqueInput | Prisma.BuchWhereUniqueInput[]
  update?: Prisma.BuchUpdateWithWhereUniqueWithoutAbteilungInput | Prisma.BuchUpdateWithWhereUniqueWithoutAbteilungInput[]
  updateMany?: Prisma.BuchUpdateManyWithWhereWithoutAbteilungInput | Prisma.BuchUpdateManyWithWhereWithoutAbteilungInput[]
  deleteMany?: Prisma.BuchScalarWhereInput | Prisma.BuchScalarWhereInput[]
}

export type BuchCreateNestedOneWithoutExemplareInput = {
  create?: Prisma.XOR<Prisma.BuchCreateWithoutExemplareInput, Prisma.BuchUncheckedCreateWithoutExemplareInput>
  connectOrCreate?: Prisma.BuchCreateOrConnectWithoutExemplareInput
  connect?: Prisma.BuchWhereUniqueInput
}

export type BuchUpdateOneRequiredWithoutExemplareNestedInput = {
  create?: Prisma.XOR<Prisma.BuchCreateWithoutExemplareInput, Prisma.BuchUncheckedCreateWithoutExemplareInput>
  connectOrCreate?: Prisma.BuchCreateOrConnectWithoutExemplareInput
  upsert?: Prisma.BuchUpsertWithoutExemplareInput
  connect?: Prisma.BuchWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.BuchUpdateToOneWithWhereWithoutExemplareInput, Prisma.BuchUpdateWithoutExemplareInput>, Prisma.BuchUncheckedUpdateWithoutExemplareInput>
}

export type BuchCreateWithoutAbteilungInput = {
  titel: string
  autor: string
  exemplare?: Prisma.ExemplarCreateNestedManyWithoutBuchInput
}

export type BuchUncheckedCreateWithoutAbteilungInput = {
  id?: number
  titel: string
  autor: string
  exemplare?: Prisma.ExemplarUncheckedCreateNestedManyWithoutBuchInput
}

export type BuchCreateOrConnectWithoutAbteilungInput = {
  where: Prisma.BuchWhereUniqueInput
  create: Prisma.XOR<Prisma.BuchCreateWithoutAbteilungInput, Prisma.BuchUncheckedCreateWithoutAbteilungInput>
}

export type BuchCreateManyAbteilungInputEnvelope = {
  data: Prisma.BuchCreateManyAbteilungInput | Prisma.BuchCreateManyAbteilungInput[]
}

export type BuchUpsertWithWhereUniqueWithoutAbteilungInput = {
  where: Prisma.BuchWhereUniqueInput
  update: Prisma.XOR<Prisma.BuchUpdateWithoutAbteilungInput, Prisma.BuchUncheckedUpdateWithoutAbteilungInput>
  create: Prisma.XOR<Prisma.BuchCreateWithoutAbteilungInput, Prisma.BuchUncheckedCreateWithoutAbteilungInput>
}

export type BuchUpdateWithWhereUniqueWithoutAbteilungInput = {
  where: Prisma.BuchWhereUniqueInput
  data: Prisma.XOR<Prisma.BuchUpdateWithoutAbteilungInput, Prisma.BuchUncheckedUpdateWithoutAbteilungInput>
}

export type BuchUpdateManyWithWhereWithoutAbteilungInput = {
  where: Prisma.BuchScalarWhereInput
  data: Prisma.XOR<Prisma.BuchUpdateManyMutationInput, Prisma.BuchUncheckedUpdateManyWithoutAbteilungInput>
}

export type BuchScalarWhereInput = {
  AND?: Prisma.BuchScalarWhereInput | Prisma.BuchScalarWhereInput[]
  OR?: Prisma.BuchScalarWhereInput[]
  NOT?: Prisma.BuchScalarWhereInput | Prisma.BuchScalarWhereInput[]
  id?: Prisma.IntFilter<"Buch"> | number
  titel?: Prisma.StringFilter<"Buch"> | string
  autor?: Prisma.StringFilter<"Buch"> | string
  abteilungId?: Prisma.IntFilter<"Buch"> | number
}

export type BuchCreateWithoutExemplareInput = {
  titel: string
  autor: string
  abteilung: Prisma.AbteilungCreateNestedOneWithoutBuecherInput
}

export type BuchUncheckedCreateWithoutExemplareInput = {
  id?: number
  titel: string
  autor: string
  abteilungId: number
}

export type BuchCreateOrConnectWithoutExemplareInput = {
  where: Prisma.BuchWhereUniqueInput
  create: Prisma.XOR<Prisma.BuchCreateWithoutExemplareInput, Prisma.BuchUncheckedCreateWithoutExemplareInput>
}

export type BuchUpsertWithoutExemplareInput = {
  update: Prisma.XOR<Prisma.BuchUpdateWithoutExemplareInput, Prisma.BuchUncheckedUpdateWithoutExemplareInput>
  create: Prisma.XOR<Prisma.BuchCreateWithoutExemplareInput, Prisma.BuchUncheckedCreateWithoutExemplareInput>
  where?: Prisma.BuchWhereInput
}

export type BuchUpdateToOneWithWhereWithoutExemplareInput = {
  where?: Prisma.BuchWhereInput
  data: Prisma.XOR<Prisma.BuchUpdateWithoutExemplareInput, Prisma.BuchUncheckedUpdateWithoutExemplareInput>
}

export type BuchUpdateWithoutExemplareInput = {
  titel?: Prisma.StringFieldUpdateOperationsInput | string
  autor?: Prisma.StringFieldUpdateOperationsInput | string
  abteilung?: Prisma.AbteilungUpdateOneRequiredWithoutBuecherNestedInput
}

export type BuchUncheckedUpdateWithoutExemplareInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  titel?: Prisma.StringFieldUpdateOperationsInput | string
  autor?: Prisma.StringFieldUpdateOperationsInput | string
  abteilungId?: Prisma.IntFieldUpdateOperationsInput | number
}

export type BuchCreateManyAbteilungInput = {
  id?: number
  titel: string
  autor: string
}

export type BuchUpdateWithoutAbteilungInput = {
  titel?: Prisma.StringFieldUpdateOperationsInput | string
  autor?: Prisma.StringFieldUpdateOperationsInput | string
  exemplare?: Prisma.ExemplarUpdateManyWithoutBuchNestedInput
}

export type BuchUncheckedUpdateWithoutAbteilungInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  titel?: Prisma.StringFieldUpdateOperationsInput | string
  autor?: Prisma.StringFieldUpdateOperationsInput | string
  exemplare?: Prisma.ExemplarUncheckedUpdateManyWithoutBuchNestedInput
}

export type BuchUncheckedUpdateManyWithoutAbteilungInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  titel?: Prisma.StringFieldUpdateOperationsInput | string
  autor?: Prisma.StringFieldUpdateOperationsInput | string
}


/**
 * Count Type BuchCountOutputType
 */

export type BuchCountOutputType = {
  exemplare: number
}

export type BuchCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  exemplare?: boolean | BuchCountOutputTypeCountExemplareArgs
}

/**
 * BuchCountOutputType without action
 */
export type BuchCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the BuchCountOutputType
   */
  select?: Prisma.BuchCountOutputTypeSelect<ExtArgs> | null
}

/**
 * BuchCountOutputType without action
 */
export type BuchCountOutputTypeCountExemplareArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ExemplarWhereInput
}


export type BuchSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  titel?: boolean
  autor?: boolean
  abteilungId?: boolean
  abteilung?: boolean | Prisma.AbteilungDefaultArgs<ExtArgs>
  exemplare?: boolean | Prisma.Buch$exemplareArgs<ExtArgs>
  _count?: boolean | Prisma.BuchCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["buch"]>

export type BuchSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  titel?: boolean
  autor?: boolean
  abteilungId?: boolean
  abteilung?: boolean | Prisma.AbteilungDefaultArgs<ExtArgs>
}, ExtArgs["result"]["buch"]>

export type BuchSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  titel?: boolean
  autor?: boolean
  abteilungId?: boolean
  abteilung?: boolean | Prisma.AbteilungDefaultArgs<ExtArgs>
}, ExtArgs["result"]["buch"]>

export type BuchSelectScalar = {
  id?: boolean
  titel?: boolean
  autor?: boolean
  abteilungId?: boolean
}

export type BuchOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "titel" | "autor" | "abteilungId", ExtArgs["result"]["buch"]>
export type BuchInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  abteilung?: boolean | Prisma.AbteilungDefaultArgs<ExtArgs>
  exemplare?: boolean | Prisma.Buch$exemplareArgs<ExtArgs>
  _count?: boolean | Prisma.BuchCountOutputTypeDefaultArgs<ExtArgs>
}
export type BuchIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  abteilung?: boolean | Prisma.AbteilungDefaultArgs<ExtArgs>
}
export type BuchIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  abteilung?: boolean | Prisma.AbteilungDefaultArgs<ExtArgs>
}

export type $BuchPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Buch"
  objects: {
    abteilung: Prisma.$AbteilungPayload<ExtArgs>
    exemplare: Prisma.$ExemplarPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    titel: string
    autor: string
    abteilungId: number
  }, ExtArgs["result"]["buch"]>
  composites: {}
}

export type BuchGetPayload<S extends boolean | null | undefined | BuchDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$BuchPayload, S>

export type BuchCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<BuchFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: BuchCountAggregateInputType | true
  }

export interface BuchDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Buch'], meta: { name: 'Buch' } }
  /**
   * Find zero or one Buch that matches the filter.
   * @param {BuchFindUniqueArgs} args - Arguments to find a Buch
   * @example
   * // Get one Buch
   * const buch = await prisma.buch.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends BuchFindUniqueArgs>(args: Prisma.SelectSubset<T, BuchFindUniqueArgs<ExtArgs>>): Prisma.Prisma__BuchClient<runtime.Types.Result.GetResult<Prisma.$BuchPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Buch that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {BuchFindUniqueOrThrowArgs} args - Arguments to find a Buch
   * @example
   * // Get one Buch
   * const buch = await prisma.buch.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends BuchFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, BuchFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__BuchClient<runtime.Types.Result.GetResult<Prisma.$BuchPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Buch that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BuchFindFirstArgs} args - Arguments to find a Buch
   * @example
   * // Get one Buch
   * const buch = await prisma.buch.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends BuchFindFirstArgs>(args?: Prisma.SelectSubset<T, BuchFindFirstArgs<ExtArgs>>): Prisma.Prisma__BuchClient<runtime.Types.Result.GetResult<Prisma.$BuchPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Buch that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BuchFindFirstOrThrowArgs} args - Arguments to find a Buch
   * @example
   * // Get one Buch
   * const buch = await prisma.buch.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends BuchFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, BuchFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__BuchClient<runtime.Types.Result.GetResult<Prisma.$BuchPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Buches that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BuchFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Buches
   * const buches = await prisma.buch.findMany()
   * 
   * // Get first 10 Buches
   * const buches = await prisma.buch.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const buchWithIdOnly = await prisma.buch.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends BuchFindManyArgs>(args?: Prisma.SelectSubset<T, BuchFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BuchPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Buch.
   * @param {BuchCreateArgs} args - Arguments to create a Buch.
   * @example
   * // Create one Buch
   * const Buch = await prisma.buch.create({
   *   data: {
   *     // ... data to create a Buch
   *   }
   * })
   * 
   */
  create<T extends BuchCreateArgs>(args: Prisma.SelectSubset<T, BuchCreateArgs<ExtArgs>>): Prisma.Prisma__BuchClient<runtime.Types.Result.GetResult<Prisma.$BuchPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Buches.
   * @param {BuchCreateManyArgs} args - Arguments to create many Buches.
   * @example
   * // Create many Buches
   * const buch = await prisma.buch.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends BuchCreateManyArgs>(args?: Prisma.SelectSubset<T, BuchCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Buches and returns the data saved in the database.
   * @param {BuchCreateManyAndReturnArgs} args - Arguments to create many Buches.
   * @example
   * // Create many Buches
   * const buch = await prisma.buch.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Buches and only return the `id`
   * const buchWithIdOnly = await prisma.buch.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends BuchCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, BuchCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BuchPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Buch.
   * @param {BuchDeleteArgs} args - Arguments to delete one Buch.
   * @example
   * // Delete one Buch
   * const Buch = await prisma.buch.delete({
   *   where: {
   *     // ... filter to delete one Buch
   *   }
   * })
   * 
   */
  delete<T extends BuchDeleteArgs>(args: Prisma.SelectSubset<T, BuchDeleteArgs<ExtArgs>>): Prisma.Prisma__BuchClient<runtime.Types.Result.GetResult<Prisma.$BuchPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Buch.
   * @param {BuchUpdateArgs} args - Arguments to update one Buch.
   * @example
   * // Update one Buch
   * const buch = await prisma.buch.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends BuchUpdateArgs>(args: Prisma.SelectSubset<T, BuchUpdateArgs<ExtArgs>>): Prisma.Prisma__BuchClient<runtime.Types.Result.GetResult<Prisma.$BuchPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Buches.
   * @param {BuchDeleteManyArgs} args - Arguments to filter Buches to delete.
   * @example
   * // Delete a few Buches
   * const { count } = await prisma.buch.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends BuchDeleteManyArgs>(args?: Prisma.SelectSubset<T, BuchDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Buches.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BuchUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Buches
   * const buch = await prisma.buch.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends BuchUpdateManyArgs>(args: Prisma.SelectSubset<T, BuchUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Buches and returns the data updated in the database.
   * @param {BuchUpdateManyAndReturnArgs} args - Arguments to update many Buches.
   * @example
   * // Update many Buches
   * const buch = await prisma.buch.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Buches and only return the `id`
   * const buchWithIdOnly = await prisma.buch.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends BuchUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, BuchUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$BuchPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Buch.
   * @param {BuchUpsertArgs} args - Arguments to update or create a Buch.
   * @example
   * // Update or create a Buch
   * const buch = await prisma.buch.upsert({
   *   create: {
   *     // ... data to create a Buch
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Buch we want to update
   *   }
   * })
   */
  upsert<T extends BuchUpsertArgs>(args: Prisma.SelectSubset<T, BuchUpsertArgs<ExtArgs>>): Prisma.Prisma__BuchClient<runtime.Types.Result.GetResult<Prisma.$BuchPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Buches.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BuchCountArgs} args - Arguments to filter Buches to count.
   * @example
   * // Count the number of Buches
   * const count = await prisma.buch.count({
   *   where: {
   *     // ... the filter for the Buches we want to count
   *   }
   * })
  **/
  count<T extends BuchCountArgs>(
    args?: Prisma.Subset<T, BuchCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], BuchCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Buch.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BuchAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends BuchAggregateArgs>(args: Prisma.Subset<T, BuchAggregateArgs>): Prisma.PrismaPromise<GetBuchAggregateType<T>>

  /**
   * Group by Buch.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {BuchGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends BuchGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: BuchGroupByArgs['orderBy'] }
      : { orderBy?: BuchGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, BuchGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetBuchGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Buch model
 */
readonly fields: BuchFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Buch.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__BuchClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  abteilung<T extends Prisma.AbteilungDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.AbteilungDefaultArgs<ExtArgs>>): Prisma.Prisma__AbteilungClient<runtime.Types.Result.GetResult<Prisma.$AbteilungPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  exemplare<T extends Prisma.Buch$exemplareArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Buch$exemplareArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ExemplarPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Buch model
 */
export interface BuchFieldRefs {
  readonly id: Prisma.FieldRef<"Buch", 'Int'>
  readonly titel: Prisma.FieldRef<"Buch", 'String'>
  readonly autor: Prisma.FieldRef<"Buch", 'String'>
  readonly abteilungId: Prisma.FieldRef<"Buch", 'Int'>
}
    

// Custom InputTypes
/**
 * Buch findUnique
 */
export type BuchFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Buch
   */
  select?: Prisma.BuchSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Buch
   */
  omit?: Prisma.BuchOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BuchInclude<ExtArgs> | null
  /**
   * Filter, which Buch to fetch.
   */
  where: Prisma.BuchWhereUniqueInput
}

/**
 * Buch findUniqueOrThrow
 */
export type BuchFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Buch
   */
  select?: Prisma.BuchSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Buch
   */
  omit?: Prisma.BuchOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BuchInclude<ExtArgs> | null
  /**
   * Filter, which Buch to fetch.
   */
  where: Prisma.BuchWhereUniqueInput
}

/**
 * Buch findFirst
 */
export type BuchFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Buch
   */
  select?: Prisma.BuchSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Buch
   */
  omit?: Prisma.BuchOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BuchInclude<ExtArgs> | null
  /**
   * Filter, which Buch to fetch.
   */
  where?: Prisma.BuchWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Buches to fetch.
   */
  orderBy?: Prisma.BuchOrderByWithRelationInput | Prisma.BuchOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Buches.
   */
  cursor?: Prisma.BuchWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Buches from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Buches.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Buches.
   */
  distinct?: Prisma.BuchScalarFieldEnum | Prisma.BuchScalarFieldEnum[]
}

/**
 * Buch findFirstOrThrow
 */
export type BuchFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Buch
   */
  select?: Prisma.BuchSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Buch
   */
  omit?: Prisma.BuchOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BuchInclude<ExtArgs> | null
  /**
   * Filter, which Buch to fetch.
   */
  where?: Prisma.BuchWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Buches to fetch.
   */
  orderBy?: Prisma.BuchOrderByWithRelationInput | Prisma.BuchOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Buches.
   */
  cursor?: Prisma.BuchWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Buches from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Buches.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Buches.
   */
  distinct?: Prisma.BuchScalarFieldEnum | Prisma.BuchScalarFieldEnum[]
}

/**
 * Buch findMany
 */
export type BuchFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Buch
   */
  select?: Prisma.BuchSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Buch
   */
  omit?: Prisma.BuchOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BuchInclude<ExtArgs> | null
  /**
   * Filter, which Buches to fetch.
   */
  where?: Prisma.BuchWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Buches to fetch.
   */
  orderBy?: Prisma.BuchOrderByWithRelationInput | Prisma.BuchOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Buches.
   */
  cursor?: Prisma.BuchWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Buches from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Buches.
   */
  skip?: number
  distinct?: Prisma.BuchScalarFieldEnum | Prisma.BuchScalarFieldEnum[]
}

/**
 * Buch create
 */
export type BuchCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Buch
   */
  select?: Prisma.BuchSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Buch
   */
  omit?: Prisma.BuchOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BuchInclude<ExtArgs> | null
  /**
   * The data needed to create a Buch.
   */
  data: Prisma.XOR<Prisma.BuchCreateInput, Prisma.BuchUncheckedCreateInput>
}

/**
 * Buch createMany
 */
export type BuchCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Buches.
   */
  data: Prisma.BuchCreateManyInput | Prisma.BuchCreateManyInput[]
}

/**
 * Buch createManyAndReturn
 */
export type BuchCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Buch
   */
  select?: Prisma.BuchSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Buch
   */
  omit?: Prisma.BuchOmit<ExtArgs> | null
  /**
   * The data used to create many Buches.
   */
  data: Prisma.BuchCreateManyInput | Prisma.BuchCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BuchIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Buch update
 */
export type BuchUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Buch
   */
  select?: Prisma.BuchSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Buch
   */
  omit?: Prisma.BuchOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BuchInclude<ExtArgs> | null
  /**
   * The data needed to update a Buch.
   */
  data: Prisma.XOR<Prisma.BuchUpdateInput, Prisma.BuchUncheckedUpdateInput>
  /**
   * Choose, which Buch to update.
   */
  where: Prisma.BuchWhereUniqueInput
}

/**
 * Buch updateMany
 */
export type BuchUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Buches.
   */
  data: Prisma.XOR<Prisma.BuchUpdateManyMutationInput, Prisma.BuchUncheckedUpdateManyInput>
  /**
   * Filter which Buches to update
   */
  where?: Prisma.BuchWhereInput
  /**
   * Limit how many Buches to update.
   */
  limit?: number
}

/**
 * Buch updateManyAndReturn
 */
export type BuchUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Buch
   */
  select?: Prisma.BuchSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Buch
   */
  omit?: Prisma.BuchOmit<ExtArgs> | null
  /**
   * The data used to update Buches.
   */
  data: Prisma.XOR<Prisma.BuchUpdateManyMutationInput, Prisma.BuchUncheckedUpdateManyInput>
  /**
   * Filter which Buches to update
   */
  where?: Prisma.BuchWhereInput
  /**
   * Limit how many Buches to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BuchIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Buch upsert
 */
export type BuchUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Buch
   */
  select?: Prisma.BuchSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Buch
   */
  omit?: Prisma.BuchOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BuchInclude<ExtArgs> | null
  /**
   * The filter to search for the Buch to update in case it exists.
   */
  where: Prisma.BuchWhereUniqueInput
  /**
   * In case the Buch found by the `where` argument doesn't exist, create a new Buch with this data.
   */
  create: Prisma.XOR<Prisma.BuchCreateInput, Prisma.BuchUncheckedCreateInput>
  /**
   * In case the Buch was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.BuchUpdateInput, Prisma.BuchUncheckedUpdateInput>
}

/**
 * Buch delete
 */
export type BuchDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Buch
   */
  select?: Prisma.BuchSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Buch
   */
  omit?: Prisma.BuchOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BuchInclude<ExtArgs> | null
  /**
   * Filter which Buch to delete.
   */
  where: Prisma.BuchWhereUniqueInput
}

/**
 * Buch deleteMany
 */
export type BuchDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Buches to delete
   */
  where?: Prisma.BuchWhereInput
  /**
   * Limit how many Buches to delete.
   */
  limit?: number
}

/**
 * Buch.exemplare
 */
export type Buch$exemplareArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Exemplar
   */
  select?: Prisma.ExemplarSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Exemplar
   */
  omit?: Prisma.ExemplarOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ExemplarInclude<ExtArgs> | null
  where?: Prisma.ExemplarWhereInput
  orderBy?: Prisma.ExemplarOrderByWithRelationInput | Prisma.ExemplarOrderByWithRelationInput[]
  cursor?: Prisma.ExemplarWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ExemplarScalarFieldEnum | Prisma.ExemplarScalarFieldEnum[]
}

/**
 * Buch without action
 */
export type BuchDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Buch
   */
  select?: Prisma.BuchSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Buch
   */
  omit?: Prisma.BuchOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.BuchInclude<ExtArgs> | null
}
