
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Entlehnung` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model Entlehnung
 * 
 */
export type EntlehnungModel = runtime.Types.Result.DefaultSelection<Prisma.$EntlehnungPayload>

export type AggregateEntlehnung = {
  _count: EntlehnungCountAggregateOutputType | null
  _avg: EntlehnungAvgAggregateOutputType | null
  _sum: EntlehnungSumAggregateOutputType | null
  _min: EntlehnungMinAggregateOutputType | null
  _max: EntlehnungMaxAggregateOutputType | null
}

export type EntlehnungAvgAggregateOutputType = {
  id: number | null
  kundeId: number | null
  exemplarId: number | null
  mitarbeiterId: number | null
}

export type EntlehnungSumAggregateOutputType = {
  id: number | null
  kundeId: number | null
  exemplarId: number | null
  mitarbeiterId: number | null
}

export type EntlehnungMinAggregateOutputType = {
  id: number | null
  kundeId: number | null
  exemplarId: number | null
  mitarbeiterId: number | null
  entlehnungsDatum: Date | null
  rueckgabeDatum: Date | null
}

export type EntlehnungMaxAggregateOutputType = {
  id: number | null
  kundeId: number | null
  exemplarId: number | null
  mitarbeiterId: number | null
  entlehnungsDatum: Date | null
  rueckgabeDatum: Date | null
}

export type EntlehnungCountAggregateOutputType = {
  id: number
  kundeId: number
  exemplarId: number
  mitarbeiterId: number
  entlehnungsDatum: number
  rueckgabeDatum: number
  _all: number
}


export type EntlehnungAvgAggregateInputType = {
  id?: true
  kundeId?: true
  exemplarId?: true
  mitarbeiterId?: true
}

export type EntlehnungSumAggregateInputType = {
  id?: true
  kundeId?: true
  exemplarId?: true
  mitarbeiterId?: true
}

export type EntlehnungMinAggregateInputType = {
  id?: true
  kundeId?: true
  exemplarId?: true
  mitarbeiterId?: true
  entlehnungsDatum?: true
  rueckgabeDatum?: true
}

export type EntlehnungMaxAggregateInputType = {
  id?: true
  kundeId?: true
  exemplarId?: true
  mitarbeiterId?: true
  entlehnungsDatum?: true
  rueckgabeDatum?: true
}

export type EntlehnungCountAggregateInputType = {
  id?: true
  kundeId?: true
  exemplarId?: true
  mitarbeiterId?: true
  entlehnungsDatum?: true
  rueckgabeDatum?: true
  _all?: true
}

export type EntlehnungAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Entlehnung to aggregate.
   */
  where?: Prisma.EntlehnungWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Entlehnungs to fetch.
   */
  orderBy?: Prisma.EntlehnungOrderByWithRelationInput | Prisma.EntlehnungOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.EntlehnungWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Entlehnungs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Entlehnungs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Entlehnungs
  **/
  _count?: true | EntlehnungCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: EntlehnungAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: EntlehnungSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: EntlehnungMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: EntlehnungMaxAggregateInputType
}

export type GetEntlehnungAggregateType<T extends EntlehnungAggregateArgs> = {
      [P in keyof T & keyof AggregateEntlehnung]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateEntlehnung[P]>
    : Prisma.GetScalarType<T[P], AggregateEntlehnung[P]>
}




export type EntlehnungGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.EntlehnungWhereInput
  orderBy?: Prisma.EntlehnungOrderByWithAggregationInput | Prisma.EntlehnungOrderByWithAggregationInput[]
  by: Prisma.EntlehnungScalarFieldEnum[] | Prisma.EntlehnungScalarFieldEnum
  having?: Prisma.EntlehnungScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: EntlehnungCountAggregateInputType | true
  _avg?: EntlehnungAvgAggregateInputType
  _sum?: EntlehnungSumAggregateInputType
  _min?: EntlehnungMinAggregateInputType
  _max?: EntlehnungMaxAggregateInputType
}

export type EntlehnungGroupByOutputType = {
  id: number
  kundeId: number
  exemplarId: number
  mitarbeiterId: number
  entlehnungsDatum: Date
  rueckgabeDatum: Date | null
  _count: EntlehnungCountAggregateOutputType | null
  _avg: EntlehnungAvgAggregateOutputType | null
  _sum: EntlehnungSumAggregateOutputType | null
  _min: EntlehnungMinAggregateOutputType | null
  _max: EntlehnungMaxAggregateOutputType | null
}

type GetEntlehnungGroupByPayload<T extends EntlehnungGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<EntlehnungGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof EntlehnungGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], EntlehnungGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], EntlehnungGroupByOutputType[P]>
      }
    >
  >



export type EntlehnungWhereInput = {
  AND?: Prisma.EntlehnungWhereInput | Prisma.EntlehnungWhereInput[]
  OR?: Prisma.EntlehnungWhereInput[]
  NOT?: Prisma.EntlehnungWhereInput | Prisma.EntlehnungWhereInput[]
  id?: Prisma.IntFilter<"Entlehnung"> | number
  kundeId?: Prisma.IntFilter<"Entlehnung"> | number
  exemplarId?: Prisma.IntFilter<"Entlehnung"> | number
  mitarbeiterId?: Prisma.IntFilter<"Entlehnung"> | number
  entlehnungsDatum?: Prisma.DateTimeFilter<"Entlehnung"> | Date | string
  rueckgabeDatum?: Prisma.DateTimeNullableFilter<"Entlehnung"> | Date | string | null
  kunde?: Prisma.XOR<Prisma.KundeScalarRelationFilter, Prisma.KundeWhereInput>
  exemplar?: Prisma.XOR<Prisma.ExemplarScalarRelationFilter, Prisma.ExemplarWhereInput>
  mitarbeiter?: Prisma.XOR<Prisma.MitarbeiterScalarRelationFilter, Prisma.MitarbeiterWhereInput>
}

export type EntlehnungOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  kundeId?: Prisma.SortOrder
  exemplarId?: Prisma.SortOrder
  mitarbeiterId?: Prisma.SortOrder
  entlehnungsDatum?: Prisma.SortOrder
  rueckgabeDatum?: Prisma.SortOrderInput | Prisma.SortOrder
  kunde?: Prisma.KundeOrderByWithRelationInput
  exemplar?: Prisma.ExemplarOrderByWithRelationInput
  mitarbeiter?: Prisma.MitarbeiterOrderByWithRelationInput
}

export type EntlehnungWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.EntlehnungWhereInput | Prisma.EntlehnungWhereInput[]
  OR?: Prisma.EntlehnungWhereInput[]
  NOT?: Prisma.EntlehnungWhereInput | Prisma.EntlehnungWhereInput[]
  kundeId?: Prisma.IntFilter<"Entlehnung"> | number
  exemplarId?: Prisma.IntFilter<"Entlehnung"> | number
  mitarbeiterId?: Prisma.IntFilter<"Entlehnung"> | number
  entlehnungsDatum?: Prisma.DateTimeFilter<"Entlehnung"> | Date | string
  rueckgabeDatum?: Prisma.DateTimeNullableFilter<"Entlehnung"> | Date | string | null
  kunde?: Prisma.XOR<Prisma.KundeScalarRelationFilter, Prisma.KundeWhereInput>
  exemplar?: Prisma.XOR<Prisma.ExemplarScalarRelationFilter, Prisma.ExemplarWhereInput>
  mitarbeiter?: Prisma.XOR<Prisma.MitarbeiterScalarRelationFilter, Prisma.MitarbeiterWhereInput>
}, "id">

export type EntlehnungOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  kundeId?: Prisma.SortOrder
  exemplarId?: Prisma.SortOrder
  mitarbeiterId?: Prisma.SortOrder
  entlehnungsDatum?: Prisma.SortOrder
  rueckgabeDatum?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.EntlehnungCountOrderByAggregateInput
  _avg?: Prisma.EntlehnungAvgOrderByAggregateInput
  _max?: Prisma.EntlehnungMaxOrderByAggregateInput
  _min?: Prisma.EntlehnungMinOrderByAggregateInput
  _sum?: Prisma.EntlehnungSumOrderByAggregateInput
}

export type EntlehnungScalarWhereWithAggregatesInput = {
  AND?: Prisma.EntlehnungScalarWhereWithAggregatesInput | Prisma.EntlehnungScalarWhereWithAggregatesInput[]
  OR?: Prisma.EntlehnungScalarWhereWithAggregatesInput[]
  NOT?: Prisma.EntlehnungScalarWhereWithAggregatesInput | Prisma.EntlehnungScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"Entlehnung"> | number
  kundeId?: Prisma.IntWithAggregatesFilter<"Entlehnung"> | number
  exemplarId?: Prisma.IntWithAggregatesFilter<"Entlehnung"> | number
  mitarbeiterId?: Prisma.IntWithAggregatesFilter<"Entlehnung"> | number
  entlehnungsDatum?: Prisma.DateTimeWithAggregatesFilter<"Entlehnung"> | Date | string
  rueckgabeDatum?: Prisma.DateTimeNullableWithAggregatesFilter<"Entlehnung"> | Date | string | null
}

export type EntlehnungCreateInput = {
  entlehnungsDatum?: Date | string
  rueckgabeDatum?: Date | string | null
  kunde: Prisma.KundeCreateNestedOneWithoutEntlehnungenInput
  exemplar: Prisma.ExemplarCreateNestedOneWithoutEntlehnungInput
  mitarbeiter: Prisma.MitarbeiterCreateNestedOneWithoutEntlehnungsInput
}

export type EntlehnungUncheckedCreateInput = {
  id?: number
  kundeId: number
  exemplarId: number
  mitarbeiterId: number
  entlehnungsDatum?: Date | string
  rueckgabeDatum?: Date | string | null
}

export type EntlehnungUpdateInput = {
  entlehnungsDatum?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  rueckgabeDatum?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  kunde?: Prisma.KundeUpdateOneRequiredWithoutEntlehnungenNestedInput
  exemplar?: Prisma.ExemplarUpdateOneRequiredWithoutEntlehnungNestedInput
  mitarbeiter?: Prisma.MitarbeiterUpdateOneRequiredWithoutEntlehnungsNestedInput
}

export type EntlehnungUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  kundeId?: Prisma.IntFieldUpdateOperationsInput | number
  exemplarId?: Prisma.IntFieldUpdateOperationsInput | number
  mitarbeiterId?: Prisma.IntFieldUpdateOperationsInput | number
  entlehnungsDatum?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  rueckgabeDatum?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type EntlehnungCreateManyInput = {
  id?: number
  kundeId: number
  exemplarId: number
  mitarbeiterId: number
  entlehnungsDatum?: Date | string
  rueckgabeDatum?: Date | string | null
}

export type EntlehnungUpdateManyMutationInput = {
  entlehnungsDatum?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  rueckgabeDatum?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type EntlehnungUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  kundeId?: Prisma.IntFieldUpdateOperationsInput | number
  exemplarId?: Prisma.IntFieldUpdateOperationsInput | number
  mitarbeiterId?: Prisma.IntFieldUpdateOperationsInput | number
  entlehnungsDatum?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  rueckgabeDatum?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type EntlehnungListRelationFilter = {
  every?: Prisma.EntlehnungWhereInput
  some?: Prisma.EntlehnungWhereInput
  none?: Prisma.EntlehnungWhereInput
}

export type EntlehnungOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type EntlehnungCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  kundeId?: Prisma.SortOrder
  exemplarId?: Prisma.SortOrder
  mitarbeiterId?: Prisma.SortOrder
  entlehnungsDatum?: Prisma.SortOrder
  rueckgabeDatum?: Prisma.SortOrder
}

export type EntlehnungAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  kundeId?: Prisma.SortOrder
  exemplarId?: Prisma.SortOrder
  mitarbeiterId?: Prisma.SortOrder
}

export type EntlehnungMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  kundeId?: Prisma.SortOrder
  exemplarId?: Prisma.SortOrder
  mitarbeiterId?: Prisma.SortOrder
  entlehnungsDatum?: Prisma.SortOrder
  rueckgabeDatum?: Prisma.SortOrder
}

export type EntlehnungMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  kundeId?: Prisma.SortOrder
  exemplarId?: Prisma.SortOrder
  mitarbeiterId?: Prisma.SortOrder
  entlehnungsDatum?: Prisma.SortOrder
  rueckgabeDatum?: Prisma.SortOrder
}

export type EntlehnungSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  kundeId?: Prisma.SortOrder
  exemplarId?: Prisma.SortOrder
  mitarbeiterId?: Prisma.SortOrder
}

export type EntlehnungCreateNestedManyWithoutMitarbeiterInput = {
  create?: Prisma.XOR<Prisma.EntlehnungCreateWithoutMitarbeiterInput, Prisma.EntlehnungUncheckedCreateWithoutMitarbeiterInput> | Prisma.EntlehnungCreateWithoutMitarbeiterInput[] | Prisma.EntlehnungUncheckedCreateWithoutMitarbeiterInput[]
  connectOrCreate?: Prisma.EntlehnungCreateOrConnectWithoutMitarbeiterInput | Prisma.EntlehnungCreateOrConnectWithoutMitarbeiterInput[]
  createMany?: Prisma.EntlehnungCreateManyMitarbeiterInputEnvelope
  connect?: Prisma.EntlehnungWhereUniqueInput | Prisma.EntlehnungWhereUniqueInput[]
}

export type EntlehnungUncheckedCreateNestedManyWithoutMitarbeiterInput = {
  create?: Prisma.XOR<Prisma.EntlehnungCreateWithoutMitarbeiterInput, Prisma.EntlehnungUncheckedCreateWithoutMitarbeiterInput> | Prisma.EntlehnungCreateWithoutMitarbeiterInput[] | Prisma.EntlehnungUncheckedCreateWithoutMitarbeiterInput[]
  connectOrCreate?: Prisma.EntlehnungCreateOrConnectWithoutMitarbeiterInput | Prisma.EntlehnungCreateOrConnectWithoutMitarbeiterInput[]
  createMany?: Prisma.EntlehnungCreateManyMitarbeiterInputEnvelope
  connect?: Prisma.EntlehnungWhereUniqueInput | Prisma.EntlehnungWhereUniqueInput[]
}

export type EntlehnungUpdateManyWithoutMitarbeiterNestedInput = {
  create?: Prisma.XOR<Prisma.EntlehnungCreateWithoutMitarbeiterInput, Prisma.EntlehnungUncheckedCreateWithoutMitarbeiterInput> | Prisma.EntlehnungCreateWithoutMitarbeiterInput[] | Prisma.EntlehnungUncheckedCreateWithoutMitarbeiterInput[]
  connectOrCreate?: Prisma.EntlehnungCreateOrConnectWithoutMitarbeiterInput | Prisma.EntlehnungCreateOrConnectWithoutMitarbeiterInput[]
  upsert?: Prisma.EntlehnungUpsertWithWhereUniqueWithoutMitarbeiterInput | Prisma.EntlehnungUpsertWithWhereUniqueWithoutMitarbeiterInput[]
  createMany?: Prisma.EntlehnungCreateManyMitarbeiterInputEnvelope
  set?: Prisma.EntlehnungWhereUniqueInput | Prisma.EntlehnungWhereUniqueInput[]
  disconnect?: Prisma.EntlehnungWhereUniqueInput | Prisma.EntlehnungWhereUniqueInput[]
  delete?: Prisma.EntlehnungWhereUniqueInput | Prisma.EntlehnungWhereUniqueInput[]
  connect?: Prisma.EntlehnungWhereUniqueInput | Prisma.EntlehnungWhereUniqueInput[]
  update?: Prisma.EntlehnungUpdateWithWhereUniqueWithoutMitarbeiterInput | Prisma.EntlehnungUpdateWithWhereUniqueWithoutMitarbeiterInput[]
  updateMany?: Prisma.EntlehnungUpdateManyWithWhereWithoutMitarbeiterInput | Prisma.EntlehnungUpdateManyWithWhereWithoutMitarbeiterInput[]
  deleteMany?: Prisma.EntlehnungScalarWhereInput | Prisma.EntlehnungScalarWhereInput[]
}

export type EntlehnungUncheckedUpdateManyWithoutMitarbeiterNestedInput = {
  create?: Prisma.XOR<Prisma.EntlehnungCreateWithoutMitarbeiterInput, Prisma.EntlehnungUncheckedCreateWithoutMitarbeiterInput> | Prisma.EntlehnungCreateWithoutMitarbeiterInput[] | Prisma.EntlehnungUncheckedCreateWithoutMitarbeiterInput[]
  connectOrCreate?: Prisma.EntlehnungCreateOrConnectWithoutMitarbeiterInput | Prisma.EntlehnungCreateOrConnectWithoutMitarbeiterInput[]
  upsert?: Prisma.EntlehnungUpsertWithWhereUniqueWithoutMitarbeiterInput | Prisma.EntlehnungUpsertWithWhereUniqueWithoutMitarbeiterInput[]
  createMany?: Prisma.EntlehnungCreateManyMitarbeiterInputEnvelope
  set?: Prisma.EntlehnungWhereUniqueInput | Prisma.EntlehnungWhereUniqueInput[]
  disconnect?: Prisma.EntlehnungWhereUniqueInput | Prisma.EntlehnungWhereUniqueInput[]
  delete?: Prisma.EntlehnungWhereUniqueInput | Prisma.EntlehnungWhereUniqueInput[]
  connect?: Prisma.EntlehnungWhereUniqueInput | Prisma.EntlehnungWhereUniqueInput[]
  update?: Prisma.EntlehnungUpdateWithWhereUniqueWithoutMitarbeiterInput | Prisma.EntlehnungUpdateWithWhereUniqueWithoutMitarbeiterInput[]
  updateMany?: Prisma.EntlehnungUpdateManyWithWhereWithoutMitarbeiterInput | Prisma.EntlehnungUpdateManyWithWhereWithoutMitarbeiterInput[]
  deleteMany?: Prisma.EntlehnungScalarWhereInput | Prisma.EntlehnungScalarWhereInput[]
}

export type EntlehnungCreateNestedManyWithoutExemplarInput = {
  create?: Prisma.XOR<Prisma.EntlehnungCreateWithoutExemplarInput, Prisma.EntlehnungUncheckedCreateWithoutExemplarInput> | Prisma.EntlehnungCreateWithoutExemplarInput[] | Prisma.EntlehnungUncheckedCreateWithoutExemplarInput[]
  connectOrCreate?: Prisma.EntlehnungCreateOrConnectWithoutExemplarInput | Prisma.EntlehnungCreateOrConnectWithoutExemplarInput[]
  createMany?: Prisma.EntlehnungCreateManyExemplarInputEnvelope
  connect?: Prisma.EntlehnungWhereUniqueInput | Prisma.EntlehnungWhereUniqueInput[]
}

export type EntlehnungUncheckedCreateNestedManyWithoutExemplarInput = {
  create?: Prisma.XOR<Prisma.EntlehnungCreateWithoutExemplarInput, Prisma.EntlehnungUncheckedCreateWithoutExemplarInput> | Prisma.EntlehnungCreateWithoutExemplarInput[] | Prisma.EntlehnungUncheckedCreateWithoutExemplarInput[]
  connectOrCreate?: Prisma.EntlehnungCreateOrConnectWithoutExemplarInput | Prisma.EntlehnungCreateOrConnectWithoutExemplarInput[]
  createMany?: Prisma.EntlehnungCreateManyExemplarInputEnvelope
  connect?: Prisma.EntlehnungWhereUniqueInput | Prisma.EntlehnungWhereUniqueInput[]
}

export type EntlehnungUpdateManyWithoutExemplarNestedInput = {
  create?: Prisma.XOR<Prisma.EntlehnungCreateWithoutExemplarInput, Prisma.EntlehnungUncheckedCreateWithoutExemplarInput> | Prisma.EntlehnungCreateWithoutExemplarInput[] | Prisma.EntlehnungUncheckedCreateWithoutExemplarInput[]
  connectOrCreate?: Prisma.EntlehnungCreateOrConnectWithoutExemplarInput | Prisma.EntlehnungCreateOrConnectWithoutExemplarInput[]
  upsert?: Prisma.EntlehnungUpsertWithWhereUniqueWithoutExemplarInput | Prisma.EntlehnungUpsertWithWhereUniqueWithoutExemplarInput[]
  createMany?: Prisma.EntlehnungCreateManyExemplarInputEnvelope
  set?: Prisma.EntlehnungWhereUniqueInput | Prisma.EntlehnungWhereUniqueInput[]
  disconnect?: Prisma.EntlehnungWhereUniqueInput | Prisma.EntlehnungWhereUniqueInput[]
  delete?: Prisma.EntlehnungWhereUniqueInput | Prisma.EntlehnungWhereUniqueInput[]
  connect?: Prisma.EntlehnungWhereUniqueInput | Prisma.EntlehnungWhereUniqueInput[]
  update?: Prisma.EntlehnungUpdateWithWhereUniqueWithoutExemplarInput | Prisma.EntlehnungUpdateWithWhereUniqueWithoutExemplarInput[]
  updateMany?: Prisma.EntlehnungUpdateManyWithWhereWithoutExemplarInput | Prisma.EntlehnungUpdateManyWithWhereWithoutExemplarInput[]
  deleteMany?: Prisma.EntlehnungScalarWhereInput | Prisma.EntlehnungScalarWhereInput[]
}

export type EntlehnungUncheckedUpdateManyWithoutExemplarNestedInput = {
  create?: Prisma.XOR<Prisma.EntlehnungCreateWithoutExemplarInput, Prisma.EntlehnungUncheckedCreateWithoutExemplarInput> | Prisma.EntlehnungCreateWithoutExemplarInput[] | Prisma.EntlehnungUncheckedCreateWithoutExemplarInput[]
  connectOrCreate?: Prisma.EntlehnungCreateOrConnectWithoutExemplarInput | Prisma.EntlehnungCreateOrConnectWithoutExemplarInput[]
  upsert?: Prisma.EntlehnungUpsertWithWhereUniqueWithoutExemplarInput | Prisma.EntlehnungUpsertWithWhereUniqueWithoutExemplarInput[]
  createMany?: Prisma.EntlehnungCreateManyExemplarInputEnvelope
  set?: Prisma.EntlehnungWhereUniqueInput | Prisma.EntlehnungWhereUniqueInput[]
  disconnect?: Prisma.EntlehnungWhereUniqueInput | Prisma.EntlehnungWhereUniqueInput[]
  delete?: Prisma.EntlehnungWhereUniqueInput | Prisma.EntlehnungWhereUniqueInput[]
  connect?: Prisma.EntlehnungWhereUniqueInput | Prisma.EntlehnungWhereUniqueInput[]
  update?: Prisma.EntlehnungUpdateWithWhereUniqueWithoutExemplarInput | Prisma.EntlehnungUpdateWithWhereUniqueWithoutExemplarInput[]
  updateMany?: Prisma.EntlehnungUpdateManyWithWhereWithoutExemplarInput | Prisma.EntlehnungUpdateManyWithWhereWithoutExemplarInput[]
  deleteMany?: Prisma.EntlehnungScalarWhereInput | Prisma.EntlehnungScalarWhereInput[]
}

export type EntlehnungCreateNestedManyWithoutKundeInput = {
  create?: Prisma.XOR<Prisma.EntlehnungCreateWithoutKundeInput, Prisma.EntlehnungUncheckedCreateWithoutKundeInput> | Prisma.EntlehnungCreateWithoutKundeInput[] | Prisma.EntlehnungUncheckedCreateWithoutKundeInput[]
  connectOrCreate?: Prisma.EntlehnungCreateOrConnectWithoutKundeInput | Prisma.EntlehnungCreateOrConnectWithoutKundeInput[]
  createMany?: Prisma.EntlehnungCreateManyKundeInputEnvelope
  connect?: Prisma.EntlehnungWhereUniqueInput | Prisma.EntlehnungWhereUniqueInput[]
}

export type EntlehnungUncheckedCreateNestedManyWithoutKundeInput = {
  create?: Prisma.XOR<Prisma.EntlehnungCreateWithoutKundeInput, Prisma.EntlehnungUncheckedCreateWithoutKundeInput> | Prisma.EntlehnungCreateWithoutKundeInput[] | Prisma.EntlehnungUncheckedCreateWithoutKundeInput[]
  connectOrCreate?: Prisma.EntlehnungCreateOrConnectWithoutKundeInput | Prisma.EntlehnungCreateOrConnectWithoutKundeInput[]
  createMany?: Prisma.EntlehnungCreateManyKundeInputEnvelope
  connect?: Prisma.EntlehnungWhereUniqueInput | Prisma.EntlehnungWhereUniqueInput[]
}

export type EntlehnungUpdateManyWithoutKundeNestedInput = {
  create?: Prisma.XOR<Prisma.EntlehnungCreateWithoutKundeInput, Prisma.EntlehnungUncheckedCreateWithoutKundeInput> | Prisma.EntlehnungCreateWithoutKundeInput[] | Prisma.EntlehnungUncheckedCreateWithoutKundeInput[]
  connectOrCreate?: Prisma.EntlehnungCreateOrConnectWithoutKundeInput | Prisma.EntlehnungCreateOrConnectWithoutKundeInput[]
  upsert?: Prisma.EntlehnungUpsertWithWhereUniqueWithoutKundeInput | Prisma.EntlehnungUpsertWithWhereUniqueWithoutKundeInput[]
  createMany?: Prisma.EntlehnungCreateManyKundeInputEnvelope
  set?: Prisma.EntlehnungWhereUniqueInput | Prisma.EntlehnungWhereUniqueInput[]
  disconnect?: Prisma.EntlehnungWhereUniqueInput | Prisma.EntlehnungWhereUniqueInput[]
  delete?: Prisma.EntlehnungWhereUniqueInput | Prisma.EntlehnungWhereUniqueInput[]
  connect?: Prisma.EntlehnungWhereUniqueInput | Prisma.EntlehnungWhereUniqueInput[]
  update?: Prisma.EntlehnungUpdateWithWhereUniqueWithoutKundeInput | Prisma.EntlehnungUpdateWithWhereUniqueWithoutKundeInput[]
  updateMany?: Prisma.EntlehnungUpdateManyWithWhereWithoutKundeInput | Prisma.EntlehnungUpdateManyWithWhereWithoutKundeInput[]
  deleteMany?: Prisma.EntlehnungScalarWhereInput | Prisma.EntlehnungScalarWhereInput[]
}

export type EntlehnungUncheckedUpdateManyWithoutKundeNestedInput = {
  create?: Prisma.XOR<Prisma.EntlehnungCreateWithoutKundeInput, Prisma.EntlehnungUncheckedCreateWithoutKundeInput> | Prisma.EntlehnungCreateWithoutKundeInput[] | Prisma.EntlehnungUncheckedCreateWithoutKundeInput[]
  connectOrCreate?: Prisma.EntlehnungCreateOrConnectWithoutKundeInput | Prisma.EntlehnungCreateOrConnectWithoutKundeInput[]
  upsert?: Prisma.EntlehnungUpsertWithWhereUniqueWithoutKundeInput | Prisma.EntlehnungUpsertWithWhereUniqueWithoutKundeInput[]
  createMany?: Prisma.EntlehnungCreateManyKundeInputEnvelope
  set?: Prisma.EntlehnungWhereUniqueInput | Prisma.EntlehnungWhereUniqueInput[]
  disconnect?: Prisma.EntlehnungWhereUniqueInput | Prisma.EntlehnungWhereUniqueInput[]
  delete?: Prisma.EntlehnungWhereUniqueInput | Prisma.EntlehnungWhereUniqueInput[]
  connect?: Prisma.EntlehnungWhereUniqueInput | Prisma.EntlehnungWhereUniqueInput[]
  update?: Prisma.EntlehnungUpdateWithWhereUniqueWithoutKundeInput | Prisma.EntlehnungUpdateWithWhereUniqueWithoutKundeInput[]
  updateMany?: Prisma.EntlehnungUpdateManyWithWhereWithoutKundeInput | Prisma.EntlehnungUpdateManyWithWhereWithoutKundeInput[]
  deleteMany?: Prisma.EntlehnungScalarWhereInput | Prisma.EntlehnungScalarWhereInput[]
}

export type DateTimeFieldUpdateOperationsInput = {
  set?: Date | string
}

export type NullableDateTimeFieldUpdateOperationsInput = {
  set?: Date | string | null
}

export type EntlehnungCreateWithoutMitarbeiterInput = {
  entlehnungsDatum?: Date | string
  rueckgabeDatum?: Date | string | null
  kunde: Prisma.KundeCreateNestedOneWithoutEntlehnungenInput
  exemplar: Prisma.ExemplarCreateNestedOneWithoutEntlehnungInput
}

export type EntlehnungUncheckedCreateWithoutMitarbeiterInput = {
  id?: number
  kundeId: number
  exemplarId: number
  entlehnungsDatum?: Date | string
  rueckgabeDatum?: Date | string | null
}

export type EntlehnungCreateOrConnectWithoutMitarbeiterInput = {
  where: Prisma.EntlehnungWhereUniqueInput
  create: Prisma.XOR<Prisma.EntlehnungCreateWithoutMitarbeiterInput, Prisma.EntlehnungUncheckedCreateWithoutMitarbeiterInput>
}

export type EntlehnungCreateManyMitarbeiterInputEnvelope = {
  data: Prisma.EntlehnungCreateManyMitarbeiterInput | Prisma.EntlehnungCreateManyMitarbeiterInput[]
}

export type EntlehnungUpsertWithWhereUniqueWithoutMitarbeiterInput = {
  where: Prisma.EntlehnungWhereUniqueInput
  update: Prisma.XOR<Prisma.EntlehnungUpdateWithoutMitarbeiterInput, Prisma.EntlehnungUncheckedUpdateWithoutMitarbeiterInput>
  create: Prisma.XOR<Prisma.EntlehnungCreateWithoutMitarbeiterInput, Prisma.EntlehnungUncheckedCreateWithoutMitarbeiterInput>
}

export type EntlehnungUpdateWithWhereUniqueWithoutMitarbeiterInput = {
  where: Prisma.EntlehnungWhereUniqueInput
  data: Prisma.XOR<Prisma.EntlehnungUpdateWithoutMitarbeiterInput, Prisma.EntlehnungUncheckedUpdateWithoutMitarbeiterInput>
}

export type EntlehnungUpdateManyWithWhereWithoutMitarbeiterInput = {
  where: Prisma.EntlehnungScalarWhereInput
  data: Prisma.XOR<Prisma.EntlehnungUpdateManyMutationInput, Prisma.EntlehnungUncheckedUpdateManyWithoutMitarbeiterInput>
}

export type EntlehnungScalarWhereInput = {
  AND?: Prisma.EntlehnungScalarWhereInput | Prisma.EntlehnungScalarWhereInput[]
  OR?: Prisma.EntlehnungScalarWhereInput[]
  NOT?: Prisma.EntlehnungScalarWhereInput | Prisma.EntlehnungScalarWhereInput[]
  id?: Prisma.IntFilter<"Entlehnung"> | number
  kundeId?: Prisma.IntFilter<"Entlehnung"> | number
  exemplarId?: Prisma.IntFilter<"Entlehnung"> | number
  mitarbeiterId?: Prisma.IntFilter<"Entlehnung"> | number
  entlehnungsDatum?: Prisma.DateTimeFilter<"Entlehnung"> | Date | string
  rueckgabeDatum?: Prisma.DateTimeNullableFilter<"Entlehnung"> | Date | string | null
}

export type EntlehnungCreateWithoutExemplarInput = {
  entlehnungsDatum?: Date | string
  rueckgabeDatum?: Date | string | null
  kunde: Prisma.KundeCreateNestedOneWithoutEntlehnungenInput
  mitarbeiter: Prisma.MitarbeiterCreateNestedOneWithoutEntlehnungsInput
}

export type EntlehnungUncheckedCreateWithoutExemplarInput = {
  id?: number
  kundeId: number
  mitarbeiterId: number
  entlehnungsDatum?: Date | string
  rueckgabeDatum?: Date | string | null
}

export type EntlehnungCreateOrConnectWithoutExemplarInput = {
  where: Prisma.EntlehnungWhereUniqueInput
  create: Prisma.XOR<Prisma.EntlehnungCreateWithoutExemplarInput, Prisma.EntlehnungUncheckedCreateWithoutExemplarInput>
}

export type EntlehnungCreateManyExemplarInputEnvelope = {
  data: Prisma.EntlehnungCreateManyExemplarInput | Prisma.EntlehnungCreateManyExemplarInput[]
}

export type EntlehnungUpsertWithWhereUniqueWithoutExemplarInput = {
  where: Prisma.EntlehnungWhereUniqueInput
  update: Prisma.XOR<Prisma.EntlehnungUpdateWithoutExemplarInput, Prisma.EntlehnungUncheckedUpdateWithoutExemplarInput>
  create: Prisma.XOR<Prisma.EntlehnungCreateWithoutExemplarInput, Prisma.EntlehnungUncheckedCreateWithoutExemplarInput>
}

export type EntlehnungUpdateWithWhereUniqueWithoutExemplarInput = {
  where: Prisma.EntlehnungWhereUniqueInput
  data: Prisma.XOR<Prisma.EntlehnungUpdateWithoutExemplarInput, Prisma.EntlehnungUncheckedUpdateWithoutExemplarInput>
}

export type EntlehnungUpdateManyWithWhereWithoutExemplarInput = {
  where: Prisma.EntlehnungScalarWhereInput
  data: Prisma.XOR<Prisma.EntlehnungUpdateManyMutationInput, Prisma.EntlehnungUncheckedUpdateManyWithoutExemplarInput>
}

export type EntlehnungCreateWithoutKundeInput = {
  entlehnungsDatum?: Date | string
  rueckgabeDatum?: Date | string | null
  exemplar: Prisma.ExemplarCreateNestedOneWithoutEntlehnungInput
  mitarbeiter: Prisma.MitarbeiterCreateNestedOneWithoutEntlehnungsInput
}

export type EntlehnungUncheckedCreateWithoutKundeInput = {
  id?: number
  exemplarId: number
  mitarbeiterId: number
  entlehnungsDatum?: Date | string
  rueckgabeDatum?: Date | string | null
}

export type EntlehnungCreateOrConnectWithoutKundeInput = {
  where: Prisma.EntlehnungWhereUniqueInput
  create: Prisma.XOR<Prisma.EntlehnungCreateWithoutKundeInput, Prisma.EntlehnungUncheckedCreateWithoutKundeInput>
}

export type EntlehnungCreateManyKundeInputEnvelope = {
  data: Prisma.EntlehnungCreateManyKundeInput | Prisma.EntlehnungCreateManyKundeInput[]
}

export type EntlehnungUpsertWithWhereUniqueWithoutKundeInput = {
  where: Prisma.EntlehnungWhereUniqueInput
  update: Prisma.XOR<Prisma.EntlehnungUpdateWithoutKundeInput, Prisma.EntlehnungUncheckedUpdateWithoutKundeInput>
  create: Prisma.XOR<Prisma.EntlehnungCreateWithoutKundeInput, Prisma.EntlehnungUncheckedCreateWithoutKundeInput>
}

export type EntlehnungUpdateWithWhereUniqueWithoutKundeInput = {
  where: Prisma.EntlehnungWhereUniqueInput
  data: Prisma.XOR<Prisma.EntlehnungUpdateWithoutKundeInput, Prisma.EntlehnungUncheckedUpdateWithoutKundeInput>
}

export type EntlehnungUpdateManyWithWhereWithoutKundeInput = {
  where: Prisma.EntlehnungScalarWhereInput
  data: Prisma.XOR<Prisma.EntlehnungUpdateManyMutationInput, Prisma.EntlehnungUncheckedUpdateManyWithoutKundeInput>
}

export type EntlehnungCreateManyMitarbeiterInput = {
  id?: number
  kundeId: number
  exemplarId: number
  entlehnungsDatum?: Date | string
  rueckgabeDatum?: Date | string | null
}

export type EntlehnungUpdateWithoutMitarbeiterInput = {
  entlehnungsDatum?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  rueckgabeDatum?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  kunde?: Prisma.KundeUpdateOneRequiredWithoutEntlehnungenNestedInput
  exemplar?: Prisma.ExemplarUpdateOneRequiredWithoutEntlehnungNestedInput
}

export type EntlehnungUncheckedUpdateWithoutMitarbeiterInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  kundeId?: Prisma.IntFieldUpdateOperationsInput | number
  exemplarId?: Prisma.IntFieldUpdateOperationsInput | number
  entlehnungsDatum?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  rueckgabeDatum?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type EntlehnungUncheckedUpdateManyWithoutMitarbeiterInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  kundeId?: Prisma.IntFieldUpdateOperationsInput | number
  exemplarId?: Prisma.IntFieldUpdateOperationsInput | number
  entlehnungsDatum?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  rueckgabeDatum?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type EntlehnungCreateManyExemplarInput = {
  id?: number
  kundeId: number
  mitarbeiterId: number
  entlehnungsDatum?: Date | string
  rueckgabeDatum?: Date | string | null
}

export type EntlehnungUpdateWithoutExemplarInput = {
  entlehnungsDatum?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  rueckgabeDatum?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  kunde?: Prisma.KundeUpdateOneRequiredWithoutEntlehnungenNestedInput
  mitarbeiter?: Prisma.MitarbeiterUpdateOneRequiredWithoutEntlehnungsNestedInput
}

export type EntlehnungUncheckedUpdateWithoutExemplarInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  kundeId?: Prisma.IntFieldUpdateOperationsInput | number
  mitarbeiterId?: Prisma.IntFieldUpdateOperationsInput | number
  entlehnungsDatum?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  rueckgabeDatum?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type EntlehnungUncheckedUpdateManyWithoutExemplarInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  kundeId?: Prisma.IntFieldUpdateOperationsInput | number
  mitarbeiterId?: Prisma.IntFieldUpdateOperationsInput | number
  entlehnungsDatum?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  rueckgabeDatum?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type EntlehnungCreateManyKundeInput = {
  id?: number
  exemplarId: number
  mitarbeiterId: number
  entlehnungsDatum?: Date | string
  rueckgabeDatum?: Date | string | null
}

export type EntlehnungUpdateWithoutKundeInput = {
  entlehnungsDatum?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  rueckgabeDatum?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  exemplar?: Prisma.ExemplarUpdateOneRequiredWithoutEntlehnungNestedInput
  mitarbeiter?: Prisma.MitarbeiterUpdateOneRequiredWithoutEntlehnungsNestedInput
}

export type EntlehnungUncheckedUpdateWithoutKundeInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  exemplarId?: Prisma.IntFieldUpdateOperationsInput | number
  mitarbeiterId?: Prisma.IntFieldUpdateOperationsInput | number
  entlehnungsDatum?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  rueckgabeDatum?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type EntlehnungUncheckedUpdateManyWithoutKundeInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  exemplarId?: Prisma.IntFieldUpdateOperationsInput | number
  mitarbeiterId?: Prisma.IntFieldUpdateOperationsInput | number
  entlehnungsDatum?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  rueckgabeDatum?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}



export type EntlehnungSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  kundeId?: boolean
  exemplarId?: boolean
  mitarbeiterId?: boolean
  entlehnungsDatum?: boolean
  rueckgabeDatum?: boolean
  kunde?: boolean | Prisma.KundeDefaultArgs<ExtArgs>
  exemplar?: boolean | Prisma.ExemplarDefaultArgs<ExtArgs>
  mitarbeiter?: boolean | Prisma.MitarbeiterDefaultArgs<ExtArgs>
}, ExtArgs["result"]["entlehnung"]>

export type EntlehnungSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  kundeId?: boolean
  exemplarId?: boolean
  mitarbeiterId?: boolean
  entlehnungsDatum?: boolean
  rueckgabeDatum?: boolean
  kunde?: boolean | Prisma.KundeDefaultArgs<ExtArgs>
  exemplar?: boolean | Prisma.ExemplarDefaultArgs<ExtArgs>
  mitarbeiter?: boolean | Prisma.MitarbeiterDefaultArgs<ExtArgs>
}, ExtArgs["result"]["entlehnung"]>

export type EntlehnungSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  kundeId?: boolean
  exemplarId?: boolean
  mitarbeiterId?: boolean
  entlehnungsDatum?: boolean
  rueckgabeDatum?: boolean
  kunde?: boolean | Prisma.KundeDefaultArgs<ExtArgs>
  exemplar?: boolean | Prisma.ExemplarDefaultArgs<ExtArgs>
  mitarbeiter?: boolean | Prisma.MitarbeiterDefaultArgs<ExtArgs>
}, ExtArgs["result"]["entlehnung"]>

export type EntlehnungSelectScalar = {
  id?: boolean
  kundeId?: boolean
  exemplarId?: boolean
  mitarbeiterId?: boolean
  entlehnungsDatum?: boolean
  rueckgabeDatum?: boolean
}

export type EntlehnungOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "kundeId" | "exemplarId" | "mitarbeiterId" | "entlehnungsDatum" | "rueckgabeDatum", ExtArgs["result"]["entlehnung"]>
export type EntlehnungInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  kunde?: boolean | Prisma.KundeDefaultArgs<ExtArgs>
  exemplar?: boolean | Prisma.ExemplarDefaultArgs<ExtArgs>
  mitarbeiter?: boolean | Prisma.MitarbeiterDefaultArgs<ExtArgs>
}
export type EntlehnungIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  kunde?: boolean | Prisma.KundeDefaultArgs<ExtArgs>
  exemplar?: boolean | Prisma.ExemplarDefaultArgs<ExtArgs>
  mitarbeiter?: boolean | Prisma.MitarbeiterDefaultArgs<ExtArgs>
}
export type EntlehnungIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  kunde?: boolean | Prisma.KundeDefaultArgs<ExtArgs>
  exemplar?: boolean | Prisma.ExemplarDefaultArgs<ExtArgs>
  mitarbeiter?: boolean | Prisma.MitarbeiterDefaultArgs<ExtArgs>
}

export type $EntlehnungPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Entlehnung"
  objects: {
    kunde: Prisma.$KundePayload<ExtArgs>
    exemplar: Prisma.$ExemplarPayload<ExtArgs>
    mitarbeiter: Prisma.$MitarbeiterPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    kundeId: number
    exemplarId: number
    mitarbeiterId: number
    entlehnungsDatum: Date
    rueckgabeDatum: Date | null
  }, ExtArgs["result"]["entlehnung"]>
  composites: {}
}

export type EntlehnungGetPayload<S extends boolean | null | undefined | EntlehnungDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$EntlehnungPayload, S>

export type EntlehnungCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<EntlehnungFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: EntlehnungCountAggregateInputType | true
  }

export interface EntlehnungDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Entlehnung'], meta: { name: 'Entlehnung' } }
  /**
   * Find zero or one Entlehnung that matches the filter.
   * @param {EntlehnungFindUniqueArgs} args - Arguments to find a Entlehnung
   * @example
   * // Get one Entlehnung
   * const entlehnung = await prisma.entlehnung.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends EntlehnungFindUniqueArgs>(args: Prisma.SelectSubset<T, EntlehnungFindUniqueArgs<ExtArgs>>): Prisma.Prisma__EntlehnungClient<runtime.Types.Result.GetResult<Prisma.$EntlehnungPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Entlehnung that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {EntlehnungFindUniqueOrThrowArgs} args - Arguments to find a Entlehnung
   * @example
   * // Get one Entlehnung
   * const entlehnung = await prisma.entlehnung.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends EntlehnungFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, EntlehnungFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__EntlehnungClient<runtime.Types.Result.GetResult<Prisma.$EntlehnungPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Entlehnung that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EntlehnungFindFirstArgs} args - Arguments to find a Entlehnung
   * @example
   * // Get one Entlehnung
   * const entlehnung = await prisma.entlehnung.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends EntlehnungFindFirstArgs>(args?: Prisma.SelectSubset<T, EntlehnungFindFirstArgs<ExtArgs>>): Prisma.Prisma__EntlehnungClient<runtime.Types.Result.GetResult<Prisma.$EntlehnungPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Entlehnung that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EntlehnungFindFirstOrThrowArgs} args - Arguments to find a Entlehnung
   * @example
   * // Get one Entlehnung
   * const entlehnung = await prisma.entlehnung.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends EntlehnungFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, EntlehnungFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__EntlehnungClient<runtime.Types.Result.GetResult<Prisma.$EntlehnungPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Entlehnungs that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EntlehnungFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Entlehnungs
   * const entlehnungs = await prisma.entlehnung.findMany()
   * 
   * // Get first 10 Entlehnungs
   * const entlehnungs = await prisma.entlehnung.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const entlehnungWithIdOnly = await prisma.entlehnung.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends EntlehnungFindManyArgs>(args?: Prisma.SelectSubset<T, EntlehnungFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$EntlehnungPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Entlehnung.
   * @param {EntlehnungCreateArgs} args - Arguments to create a Entlehnung.
   * @example
   * // Create one Entlehnung
   * const Entlehnung = await prisma.entlehnung.create({
   *   data: {
   *     // ... data to create a Entlehnung
   *   }
   * })
   * 
   */
  create<T extends EntlehnungCreateArgs>(args: Prisma.SelectSubset<T, EntlehnungCreateArgs<ExtArgs>>): Prisma.Prisma__EntlehnungClient<runtime.Types.Result.GetResult<Prisma.$EntlehnungPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Entlehnungs.
   * @param {EntlehnungCreateManyArgs} args - Arguments to create many Entlehnungs.
   * @example
   * // Create many Entlehnungs
   * const entlehnung = await prisma.entlehnung.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends EntlehnungCreateManyArgs>(args?: Prisma.SelectSubset<T, EntlehnungCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Entlehnungs and returns the data saved in the database.
   * @param {EntlehnungCreateManyAndReturnArgs} args - Arguments to create many Entlehnungs.
   * @example
   * // Create many Entlehnungs
   * const entlehnung = await prisma.entlehnung.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Entlehnungs and only return the `id`
   * const entlehnungWithIdOnly = await prisma.entlehnung.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends EntlehnungCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, EntlehnungCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$EntlehnungPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Entlehnung.
   * @param {EntlehnungDeleteArgs} args - Arguments to delete one Entlehnung.
   * @example
   * // Delete one Entlehnung
   * const Entlehnung = await prisma.entlehnung.delete({
   *   where: {
   *     // ... filter to delete one Entlehnung
   *   }
   * })
   * 
   */
  delete<T extends EntlehnungDeleteArgs>(args: Prisma.SelectSubset<T, EntlehnungDeleteArgs<ExtArgs>>): Prisma.Prisma__EntlehnungClient<runtime.Types.Result.GetResult<Prisma.$EntlehnungPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Entlehnung.
   * @param {EntlehnungUpdateArgs} args - Arguments to update one Entlehnung.
   * @example
   * // Update one Entlehnung
   * const entlehnung = await prisma.entlehnung.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends EntlehnungUpdateArgs>(args: Prisma.SelectSubset<T, EntlehnungUpdateArgs<ExtArgs>>): Prisma.Prisma__EntlehnungClient<runtime.Types.Result.GetResult<Prisma.$EntlehnungPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Entlehnungs.
   * @param {EntlehnungDeleteManyArgs} args - Arguments to filter Entlehnungs to delete.
   * @example
   * // Delete a few Entlehnungs
   * const { count } = await prisma.entlehnung.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends EntlehnungDeleteManyArgs>(args?: Prisma.SelectSubset<T, EntlehnungDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Entlehnungs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EntlehnungUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Entlehnungs
   * const entlehnung = await prisma.entlehnung.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends EntlehnungUpdateManyArgs>(args: Prisma.SelectSubset<T, EntlehnungUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Entlehnungs and returns the data updated in the database.
   * @param {EntlehnungUpdateManyAndReturnArgs} args - Arguments to update many Entlehnungs.
   * @example
   * // Update many Entlehnungs
   * const entlehnung = await prisma.entlehnung.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Entlehnungs and only return the `id`
   * const entlehnungWithIdOnly = await prisma.entlehnung.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends EntlehnungUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, EntlehnungUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$EntlehnungPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Entlehnung.
   * @param {EntlehnungUpsertArgs} args - Arguments to update or create a Entlehnung.
   * @example
   * // Update or create a Entlehnung
   * const entlehnung = await prisma.entlehnung.upsert({
   *   create: {
   *     // ... data to create a Entlehnung
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Entlehnung we want to update
   *   }
   * })
   */
  upsert<T extends EntlehnungUpsertArgs>(args: Prisma.SelectSubset<T, EntlehnungUpsertArgs<ExtArgs>>): Prisma.Prisma__EntlehnungClient<runtime.Types.Result.GetResult<Prisma.$EntlehnungPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Entlehnungs.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EntlehnungCountArgs} args - Arguments to filter Entlehnungs to count.
   * @example
   * // Count the number of Entlehnungs
   * const count = await prisma.entlehnung.count({
   *   where: {
   *     // ... the filter for the Entlehnungs we want to count
   *   }
   * })
  **/
  count<T extends EntlehnungCountArgs>(
    args?: Prisma.Subset<T, EntlehnungCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], EntlehnungCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Entlehnung.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EntlehnungAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends EntlehnungAggregateArgs>(args: Prisma.Subset<T, EntlehnungAggregateArgs>): Prisma.PrismaPromise<GetEntlehnungAggregateType<T>>

  /**
   * Group by Entlehnung.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {EntlehnungGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends EntlehnungGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: EntlehnungGroupByArgs['orderBy'] }
      : { orderBy?: EntlehnungGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, EntlehnungGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetEntlehnungGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Entlehnung model
 */
readonly fields: EntlehnungFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Entlehnung.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__EntlehnungClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  kunde<T extends Prisma.KundeDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.KundeDefaultArgs<ExtArgs>>): Prisma.Prisma__KundeClient<runtime.Types.Result.GetResult<Prisma.$KundePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  exemplar<T extends Prisma.ExemplarDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ExemplarDefaultArgs<ExtArgs>>): Prisma.Prisma__ExemplarClient<runtime.Types.Result.GetResult<Prisma.$ExemplarPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  mitarbeiter<T extends Prisma.MitarbeiterDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.MitarbeiterDefaultArgs<ExtArgs>>): Prisma.Prisma__MitarbeiterClient<runtime.Types.Result.GetResult<Prisma.$MitarbeiterPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Entlehnung model
 */
export interface EntlehnungFieldRefs {
  readonly id: Prisma.FieldRef<"Entlehnung", 'Int'>
  readonly kundeId: Prisma.FieldRef<"Entlehnung", 'Int'>
  readonly exemplarId: Prisma.FieldRef<"Entlehnung", 'Int'>
  readonly mitarbeiterId: Prisma.FieldRef<"Entlehnung", 'Int'>
  readonly entlehnungsDatum: Prisma.FieldRef<"Entlehnung", 'DateTime'>
  readonly rueckgabeDatum: Prisma.FieldRef<"Entlehnung", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Entlehnung findUnique
 */
export type EntlehnungFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Entlehnung
   */
  select?: Prisma.EntlehnungSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Entlehnung
   */
  omit?: Prisma.EntlehnungOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EntlehnungInclude<ExtArgs> | null
  /**
   * Filter, which Entlehnung to fetch.
   */
  where: Prisma.EntlehnungWhereUniqueInput
}

/**
 * Entlehnung findUniqueOrThrow
 */
export type EntlehnungFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Entlehnung
   */
  select?: Prisma.EntlehnungSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Entlehnung
   */
  omit?: Prisma.EntlehnungOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EntlehnungInclude<ExtArgs> | null
  /**
   * Filter, which Entlehnung to fetch.
   */
  where: Prisma.EntlehnungWhereUniqueInput
}

/**
 * Entlehnung findFirst
 */
export type EntlehnungFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Entlehnung
   */
  select?: Prisma.EntlehnungSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Entlehnung
   */
  omit?: Prisma.EntlehnungOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EntlehnungInclude<ExtArgs> | null
  /**
   * Filter, which Entlehnung to fetch.
   */
  where?: Prisma.EntlehnungWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Entlehnungs to fetch.
   */
  orderBy?: Prisma.EntlehnungOrderByWithRelationInput | Prisma.EntlehnungOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Entlehnungs.
   */
  cursor?: Prisma.EntlehnungWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Entlehnungs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Entlehnungs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Entlehnungs.
   */
  distinct?: Prisma.EntlehnungScalarFieldEnum | Prisma.EntlehnungScalarFieldEnum[]
}

/**
 * Entlehnung findFirstOrThrow
 */
export type EntlehnungFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Entlehnung
   */
  select?: Prisma.EntlehnungSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Entlehnung
   */
  omit?: Prisma.EntlehnungOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EntlehnungInclude<ExtArgs> | null
  /**
   * Filter, which Entlehnung to fetch.
   */
  where?: Prisma.EntlehnungWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Entlehnungs to fetch.
   */
  orderBy?: Prisma.EntlehnungOrderByWithRelationInput | Prisma.EntlehnungOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Entlehnungs.
   */
  cursor?: Prisma.EntlehnungWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Entlehnungs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Entlehnungs.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Entlehnungs.
   */
  distinct?: Prisma.EntlehnungScalarFieldEnum | Prisma.EntlehnungScalarFieldEnum[]
}

/**
 * Entlehnung findMany
 */
export type EntlehnungFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Entlehnung
   */
  select?: Prisma.EntlehnungSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Entlehnung
   */
  omit?: Prisma.EntlehnungOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EntlehnungInclude<ExtArgs> | null
  /**
   * Filter, which Entlehnungs to fetch.
   */
  where?: Prisma.EntlehnungWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Entlehnungs to fetch.
   */
  orderBy?: Prisma.EntlehnungOrderByWithRelationInput | Prisma.EntlehnungOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Entlehnungs.
   */
  cursor?: Prisma.EntlehnungWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Entlehnungs from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Entlehnungs.
   */
  skip?: number
  distinct?: Prisma.EntlehnungScalarFieldEnum | Prisma.EntlehnungScalarFieldEnum[]
}

/**
 * Entlehnung create
 */
export type EntlehnungCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Entlehnung
   */
  select?: Prisma.EntlehnungSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Entlehnung
   */
  omit?: Prisma.EntlehnungOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EntlehnungInclude<ExtArgs> | null
  /**
   * The data needed to create a Entlehnung.
   */
  data: Prisma.XOR<Prisma.EntlehnungCreateInput, Prisma.EntlehnungUncheckedCreateInput>
}

/**
 * Entlehnung createMany
 */
export type EntlehnungCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Entlehnungs.
   */
  data: Prisma.EntlehnungCreateManyInput | Prisma.EntlehnungCreateManyInput[]
}

/**
 * Entlehnung createManyAndReturn
 */
export type EntlehnungCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Entlehnung
   */
  select?: Prisma.EntlehnungSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Entlehnung
   */
  omit?: Prisma.EntlehnungOmit<ExtArgs> | null
  /**
   * The data used to create many Entlehnungs.
   */
  data: Prisma.EntlehnungCreateManyInput | Prisma.EntlehnungCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EntlehnungIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Entlehnung update
 */
export type EntlehnungUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Entlehnung
   */
  select?: Prisma.EntlehnungSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Entlehnung
   */
  omit?: Prisma.EntlehnungOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EntlehnungInclude<ExtArgs> | null
  /**
   * The data needed to update a Entlehnung.
   */
  data: Prisma.XOR<Prisma.EntlehnungUpdateInput, Prisma.EntlehnungUncheckedUpdateInput>
  /**
   * Choose, which Entlehnung to update.
   */
  where: Prisma.EntlehnungWhereUniqueInput
}

/**
 * Entlehnung updateMany
 */
export type EntlehnungUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Entlehnungs.
   */
  data: Prisma.XOR<Prisma.EntlehnungUpdateManyMutationInput, Prisma.EntlehnungUncheckedUpdateManyInput>
  /**
   * Filter which Entlehnungs to update
   */
  where?: Prisma.EntlehnungWhereInput
  /**
   * Limit how many Entlehnungs to update.
   */
  limit?: number
}

/**
 * Entlehnung updateManyAndReturn
 */
export type EntlehnungUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Entlehnung
   */
  select?: Prisma.EntlehnungSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Entlehnung
   */
  omit?: Prisma.EntlehnungOmit<ExtArgs> | null
  /**
   * The data used to update Entlehnungs.
   */
  data: Prisma.XOR<Prisma.EntlehnungUpdateManyMutationInput, Prisma.EntlehnungUncheckedUpdateManyInput>
  /**
   * Filter which Entlehnungs to update
   */
  where?: Prisma.EntlehnungWhereInput
  /**
   * Limit how many Entlehnungs to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EntlehnungIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Entlehnung upsert
 */
export type EntlehnungUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Entlehnung
   */
  select?: Prisma.EntlehnungSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Entlehnung
   */
  omit?: Prisma.EntlehnungOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EntlehnungInclude<ExtArgs> | null
  /**
   * The filter to search for the Entlehnung to update in case it exists.
   */
  where: Prisma.EntlehnungWhereUniqueInput
  /**
   * In case the Entlehnung found by the `where` argument doesn't exist, create a new Entlehnung with this data.
   */
  create: Prisma.XOR<Prisma.EntlehnungCreateInput, Prisma.EntlehnungUncheckedCreateInput>
  /**
   * In case the Entlehnung was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.EntlehnungUpdateInput, Prisma.EntlehnungUncheckedUpdateInput>
}

/**
 * Entlehnung delete
 */
export type EntlehnungDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Entlehnung
   */
  select?: Prisma.EntlehnungSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Entlehnung
   */
  omit?: Prisma.EntlehnungOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EntlehnungInclude<ExtArgs> | null
  /**
   * Filter which Entlehnung to delete.
   */
  where: Prisma.EntlehnungWhereUniqueInput
}

/**
 * Entlehnung deleteMany
 */
export type EntlehnungDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Entlehnungs to delete
   */
  where?: Prisma.EntlehnungWhereInput
  /**
   * Limit how many Entlehnungs to delete.
   */
  limit?: number
}

/**
 * Entlehnung without action
 */
export type EntlehnungDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Entlehnung
   */
  select?: Prisma.EntlehnungSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Entlehnung
   */
  omit?: Prisma.EntlehnungOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EntlehnungInclude<ExtArgs> | null
}
