
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Exemplar` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model Exemplar
 * 
 */
export type ExemplarModel = runtime.Types.Result.DefaultSelection<Prisma.$ExemplarPayload>

export type AggregateExemplar = {
  _count: ExemplarCountAggregateOutputType | null
  _avg: ExemplarAvgAggregateOutputType | null
  _sum: ExemplarSumAggregateOutputType | null
  _min: ExemplarMinAggregateOutputType | null
  _max: ExemplarMaxAggregateOutputType | null
}

export type ExemplarAvgAggregateOutputType = {
  id: number | null
  buchId: number | null
  filialeId: number | null
}

export type ExemplarSumAggregateOutputType = {
  id: number | null
  buchId: number | null
  filialeId: number | null
}

export type ExemplarMinAggregateOutputType = {
  id: number | null
  buchId: number | null
  filialeId: number | null
}

export type ExemplarMaxAggregateOutputType = {
  id: number | null
  buchId: number | null
  filialeId: number | null
}

export type ExemplarCountAggregateOutputType = {
  id: number
  buchId: number
  filialeId: number
  _all: number
}


export type ExemplarAvgAggregateInputType = {
  id?: true
  buchId?: true
  filialeId?: true
}

export type ExemplarSumAggregateInputType = {
  id?: true
  buchId?: true
  filialeId?: true
}

export type ExemplarMinAggregateInputType = {
  id?: true
  buchId?: true
  filialeId?: true
}

export type ExemplarMaxAggregateInputType = {
  id?: true
  buchId?: true
  filialeId?: true
}

export type ExemplarCountAggregateInputType = {
  id?: true
  buchId?: true
  filialeId?: true
  _all?: true
}

export type ExemplarAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Exemplar to aggregate.
   */
  where?: Prisma.ExemplarWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Exemplars to fetch.
   */
  orderBy?: Prisma.ExemplarOrderByWithRelationInput | Prisma.ExemplarOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ExemplarWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Exemplars from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Exemplars.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Exemplars
  **/
  _count?: true | ExemplarCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: ExemplarAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: ExemplarSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ExemplarMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ExemplarMaxAggregateInputType
}

export type GetExemplarAggregateType<T extends ExemplarAggregateArgs> = {
      [P in keyof T & keyof AggregateExemplar]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateExemplar[P]>
    : Prisma.GetScalarType<T[P], AggregateExemplar[P]>
}




export type ExemplarGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ExemplarWhereInput
  orderBy?: Prisma.ExemplarOrderByWithAggregationInput | Prisma.ExemplarOrderByWithAggregationInput[]
  by: Prisma.ExemplarScalarFieldEnum[] | Prisma.ExemplarScalarFieldEnum
  having?: Prisma.ExemplarScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ExemplarCountAggregateInputType | true
  _avg?: ExemplarAvgAggregateInputType
  _sum?: ExemplarSumAggregateInputType
  _min?: ExemplarMinAggregateInputType
  _max?: ExemplarMaxAggregateInputType
}

export type ExemplarGroupByOutputType = {
  id: number
  buchId: number
  filialeId: number
  _count: ExemplarCountAggregateOutputType | null
  _avg: ExemplarAvgAggregateOutputType | null
  _sum: ExemplarSumAggregateOutputType | null
  _min: ExemplarMinAggregateOutputType | null
  _max: ExemplarMaxAggregateOutputType | null
}

type GetExemplarGroupByPayload<T extends ExemplarGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ExemplarGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ExemplarGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ExemplarGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ExemplarGroupByOutputType[P]>
      }
    >
  >



export type ExemplarWhereInput = {
  AND?: Prisma.ExemplarWhereInput | Prisma.ExemplarWhereInput[]
  OR?: Prisma.ExemplarWhereInput[]
  NOT?: Prisma.ExemplarWhereInput | Prisma.ExemplarWhereInput[]
  id?: Prisma.IntFilter<"Exemplar"> | number
  buchId?: Prisma.IntFilter<"Exemplar"> | number
  filialeId?: Prisma.IntFilter<"Exemplar"> | number
  buch?: Prisma.XOR<Prisma.BuchScalarRelationFilter, Prisma.BuchWhereInput>
  filiale?: Prisma.XOR<Prisma.FilialeScalarRelationFilter, Prisma.FilialeWhereInput>
  entlehnung?: Prisma.EntlehnungListRelationFilter
}

export type ExemplarOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  buchId?: Prisma.SortOrder
  filialeId?: Prisma.SortOrder
  buch?: Prisma.BuchOrderByWithRelationInput
  filiale?: Prisma.FilialeOrderByWithRelationInput
  entlehnung?: Prisma.EntlehnungOrderByRelationAggregateInput
}

export type ExemplarWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.ExemplarWhereInput | Prisma.ExemplarWhereInput[]
  OR?: Prisma.ExemplarWhereInput[]
  NOT?: Prisma.ExemplarWhereInput | Prisma.ExemplarWhereInput[]
  buchId?: Prisma.IntFilter<"Exemplar"> | number
  filialeId?: Prisma.IntFilter<"Exemplar"> | number
  buch?: Prisma.XOR<Prisma.BuchScalarRelationFilter, Prisma.BuchWhereInput>
  filiale?: Prisma.XOR<Prisma.FilialeScalarRelationFilter, Prisma.FilialeWhereInput>
  entlehnung?: Prisma.EntlehnungListRelationFilter
}, "id">

export type ExemplarOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  buchId?: Prisma.SortOrder
  filialeId?: Prisma.SortOrder
  _count?: Prisma.ExemplarCountOrderByAggregateInput
  _avg?: Prisma.ExemplarAvgOrderByAggregateInput
  _max?: Prisma.ExemplarMaxOrderByAggregateInput
  _min?: Prisma.ExemplarMinOrderByAggregateInput
  _sum?: Prisma.ExemplarSumOrderByAggregateInput
}

export type ExemplarScalarWhereWithAggregatesInput = {
  AND?: Prisma.ExemplarScalarWhereWithAggregatesInput | Prisma.ExemplarScalarWhereWithAggregatesInput[]
  OR?: Prisma.ExemplarScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ExemplarScalarWhereWithAggregatesInput | Prisma.ExemplarScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"Exemplar"> | number
  buchId?: Prisma.IntWithAggregatesFilter<"Exemplar"> | number
  filialeId?: Prisma.IntWithAggregatesFilter<"Exemplar"> | number
}

export type ExemplarCreateInput = {
  buch: Prisma.BuchCreateNestedOneWithoutExemplareInput
  filiale: Prisma.FilialeCreateNestedOneWithoutExemplareInput
  entlehnung?: Prisma.EntlehnungCreateNestedManyWithoutExemplarInput
}

export type ExemplarUncheckedCreateInput = {
  id?: number
  buchId: number
  filialeId: number
  entlehnung?: Prisma.EntlehnungUncheckedCreateNestedManyWithoutExemplarInput
}

export type ExemplarUpdateInput = {
  buch?: Prisma.BuchUpdateOneRequiredWithoutExemplareNestedInput
  filiale?: Prisma.FilialeUpdateOneRequiredWithoutExemplareNestedInput
  entlehnung?: Prisma.EntlehnungUpdateManyWithoutExemplarNestedInput
}

export type ExemplarUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  buchId?: Prisma.IntFieldUpdateOperationsInput | number
  filialeId?: Prisma.IntFieldUpdateOperationsInput | number
  entlehnung?: Prisma.EntlehnungUncheckedUpdateManyWithoutExemplarNestedInput
}

export type ExemplarCreateManyInput = {
  id?: number
  buchId: number
  filialeId: number
}

export type ExemplarUpdateManyMutationInput = {

}

export type ExemplarUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  buchId?: Prisma.IntFieldUpdateOperationsInput | number
  filialeId?: Prisma.IntFieldUpdateOperationsInput | number
}

export type ExemplarListRelationFilter = {
  every?: Prisma.ExemplarWhereInput
  some?: Prisma.ExemplarWhereInput
  none?: Prisma.ExemplarWhereInput
}

export type ExemplarOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type ExemplarCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  buchId?: Prisma.SortOrder
  filialeId?: Prisma.SortOrder
}

export type ExemplarAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  buchId?: Prisma.SortOrder
  filialeId?: Prisma.SortOrder
}

export type ExemplarMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  buchId?: Prisma.SortOrder
  filialeId?: Prisma.SortOrder
}

export type ExemplarMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  buchId?: Prisma.SortOrder
  filialeId?: Prisma.SortOrder
}

export type ExemplarSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  buchId?: Prisma.SortOrder
  filialeId?: Prisma.SortOrder
}

export type ExemplarScalarRelationFilter = {
  is?: Prisma.ExemplarWhereInput
  isNot?: Prisma.ExemplarWhereInput
}

export type ExemplarCreateNestedManyWithoutFilialeInput = {
  create?: Prisma.XOR<Prisma.ExemplarCreateWithoutFilialeInput, Prisma.ExemplarUncheckedCreateWithoutFilialeInput> | Prisma.ExemplarCreateWithoutFilialeInput[] | Prisma.ExemplarUncheckedCreateWithoutFilialeInput[]
  connectOrCreate?: Prisma.ExemplarCreateOrConnectWithoutFilialeInput | Prisma.ExemplarCreateOrConnectWithoutFilialeInput[]
  createMany?: Prisma.ExemplarCreateManyFilialeInputEnvelope
  connect?: Prisma.ExemplarWhereUniqueInput | Prisma.ExemplarWhereUniqueInput[]
}

export type ExemplarUncheckedCreateNestedManyWithoutFilialeInput = {
  create?: Prisma.XOR<Prisma.ExemplarCreateWithoutFilialeInput, Prisma.ExemplarUncheckedCreateWithoutFilialeInput> | Prisma.ExemplarCreateWithoutFilialeInput[] | Prisma.ExemplarUncheckedCreateWithoutFilialeInput[]
  connectOrCreate?: Prisma.ExemplarCreateOrConnectWithoutFilialeInput | Prisma.ExemplarCreateOrConnectWithoutFilialeInput[]
  createMany?: Prisma.ExemplarCreateManyFilialeInputEnvelope
  connect?: Prisma.ExemplarWhereUniqueInput | Prisma.ExemplarWhereUniqueInput[]
}

export type ExemplarUpdateManyWithoutFilialeNestedInput = {
  create?: Prisma.XOR<Prisma.ExemplarCreateWithoutFilialeInput, Prisma.ExemplarUncheckedCreateWithoutFilialeInput> | Prisma.ExemplarCreateWithoutFilialeInput[] | Prisma.ExemplarUncheckedCreateWithoutFilialeInput[]
  connectOrCreate?: Prisma.ExemplarCreateOrConnectWithoutFilialeInput | Prisma.ExemplarCreateOrConnectWithoutFilialeInput[]
  upsert?: Prisma.ExemplarUpsertWithWhereUniqueWithoutFilialeInput | Prisma.ExemplarUpsertWithWhereUniqueWithoutFilialeInput[]
  createMany?: Prisma.ExemplarCreateManyFilialeInputEnvelope
  set?: Prisma.ExemplarWhereUniqueInput | Prisma.ExemplarWhereUniqueInput[]
  disconnect?: Prisma.ExemplarWhereUniqueInput | Prisma.ExemplarWhereUniqueInput[]
  delete?: Prisma.ExemplarWhereUniqueInput | Prisma.ExemplarWhereUniqueInput[]
  connect?: Prisma.ExemplarWhereUniqueInput | Prisma.ExemplarWhereUniqueInput[]
  update?: Prisma.ExemplarUpdateWithWhereUniqueWithoutFilialeInput | Prisma.ExemplarUpdateWithWhereUniqueWithoutFilialeInput[]
  updateMany?: Prisma.ExemplarUpdateManyWithWhereWithoutFilialeInput | Prisma.ExemplarUpdateManyWithWhereWithoutFilialeInput[]
  deleteMany?: Prisma.ExemplarScalarWhereInput | Prisma.ExemplarScalarWhereInput[]
}

export type ExemplarUncheckedUpdateManyWithoutFilialeNestedInput = {
  create?: Prisma.XOR<Prisma.ExemplarCreateWithoutFilialeInput, Prisma.ExemplarUncheckedCreateWithoutFilialeInput> | Prisma.ExemplarCreateWithoutFilialeInput[] | Prisma.ExemplarUncheckedCreateWithoutFilialeInput[]
  connectOrCreate?: Prisma.ExemplarCreateOrConnectWithoutFilialeInput | Prisma.ExemplarCreateOrConnectWithoutFilialeInput[]
  upsert?: Prisma.ExemplarUpsertWithWhereUniqueWithoutFilialeInput | Prisma.ExemplarUpsertWithWhereUniqueWithoutFilialeInput[]
  createMany?: Prisma.ExemplarCreateManyFilialeInputEnvelope
  set?: Prisma.ExemplarWhereUniqueInput | Prisma.ExemplarWhereUniqueInput[]
  disconnect?: Prisma.ExemplarWhereUniqueInput | Prisma.ExemplarWhereUniqueInput[]
  delete?: Prisma.ExemplarWhereUniqueInput | Prisma.ExemplarWhereUniqueInput[]
  connect?: Prisma.ExemplarWhereUniqueInput | Prisma.ExemplarWhereUniqueInput[]
  update?: Prisma.ExemplarUpdateWithWhereUniqueWithoutFilialeInput | Prisma.ExemplarUpdateWithWhereUniqueWithoutFilialeInput[]
  updateMany?: Prisma.ExemplarUpdateManyWithWhereWithoutFilialeInput | Prisma.ExemplarUpdateManyWithWhereWithoutFilialeInput[]
  deleteMany?: Prisma.ExemplarScalarWhereInput | Prisma.ExemplarScalarWhereInput[]
}

export type ExemplarCreateNestedManyWithoutBuchInput = {
  create?: Prisma.XOR<Prisma.ExemplarCreateWithoutBuchInput, Prisma.ExemplarUncheckedCreateWithoutBuchInput> | Prisma.ExemplarCreateWithoutBuchInput[] | Prisma.ExemplarUncheckedCreateWithoutBuchInput[]
  connectOrCreate?: Prisma.ExemplarCreateOrConnectWithoutBuchInput | Prisma.ExemplarCreateOrConnectWithoutBuchInput[]
  createMany?: Prisma.ExemplarCreateManyBuchInputEnvelope
  connect?: Prisma.ExemplarWhereUniqueInput | Prisma.ExemplarWhereUniqueInput[]
}

export type ExemplarUncheckedCreateNestedManyWithoutBuchInput = {
  create?: Prisma.XOR<Prisma.ExemplarCreateWithoutBuchInput, Prisma.ExemplarUncheckedCreateWithoutBuchInput> | Prisma.ExemplarCreateWithoutBuchInput[] | Prisma.ExemplarUncheckedCreateWithoutBuchInput[]
  connectOrCreate?: Prisma.ExemplarCreateOrConnectWithoutBuchInput | Prisma.ExemplarCreateOrConnectWithoutBuchInput[]
  createMany?: Prisma.ExemplarCreateManyBuchInputEnvelope
  connect?: Prisma.ExemplarWhereUniqueInput | Prisma.ExemplarWhereUniqueInput[]
}

export type ExemplarUpdateManyWithoutBuchNestedInput = {
  create?: Prisma.XOR<Prisma.ExemplarCreateWithoutBuchInput, Prisma.ExemplarUncheckedCreateWithoutBuchInput> | Prisma.ExemplarCreateWithoutBuchInput[] | Prisma.ExemplarUncheckedCreateWithoutBuchInput[]
  connectOrCreate?: Prisma.ExemplarCreateOrConnectWithoutBuchInput | Prisma.ExemplarCreateOrConnectWithoutBuchInput[]
  upsert?: Prisma.ExemplarUpsertWithWhereUniqueWithoutBuchInput | Prisma.ExemplarUpsertWithWhereUniqueWithoutBuchInput[]
  createMany?: Prisma.ExemplarCreateManyBuchInputEnvelope
  set?: Prisma.ExemplarWhereUniqueInput | Prisma.ExemplarWhereUniqueInput[]
  disconnect?: Prisma.ExemplarWhereUniqueInput | Prisma.ExemplarWhereUniqueInput[]
  delete?: Prisma.ExemplarWhereUniqueInput | Prisma.ExemplarWhereUniqueInput[]
  connect?: Prisma.ExemplarWhereUniqueInput | Prisma.ExemplarWhereUniqueInput[]
  update?: Prisma.ExemplarUpdateWithWhereUniqueWithoutBuchInput | Prisma.ExemplarUpdateWithWhereUniqueWithoutBuchInput[]
  updateMany?: Prisma.ExemplarUpdateManyWithWhereWithoutBuchInput | Prisma.ExemplarUpdateManyWithWhereWithoutBuchInput[]
  deleteMany?: Prisma.ExemplarScalarWhereInput | Prisma.ExemplarScalarWhereInput[]
}

export type ExemplarUncheckedUpdateManyWithoutBuchNestedInput = {
  create?: Prisma.XOR<Prisma.ExemplarCreateWithoutBuchInput, Prisma.ExemplarUncheckedCreateWithoutBuchInput> | Prisma.ExemplarCreateWithoutBuchInput[] | Prisma.ExemplarUncheckedCreateWithoutBuchInput[]
  connectOrCreate?: Prisma.ExemplarCreateOrConnectWithoutBuchInput | Prisma.ExemplarCreateOrConnectWithoutBuchInput[]
  upsert?: Prisma.ExemplarUpsertWithWhereUniqueWithoutBuchInput | Prisma.ExemplarUpsertWithWhereUniqueWithoutBuchInput[]
  createMany?: Prisma.ExemplarCreateManyBuchInputEnvelope
  set?: Prisma.ExemplarWhereUniqueInput | Prisma.ExemplarWhereUniqueInput[]
  disconnect?: Prisma.ExemplarWhereUniqueInput | Prisma.ExemplarWhereUniqueInput[]
  delete?: Prisma.ExemplarWhereUniqueInput | Prisma.ExemplarWhereUniqueInput[]
  connect?: Prisma.ExemplarWhereUniqueInput | Prisma.ExemplarWhereUniqueInput[]
  update?: Prisma.ExemplarUpdateWithWhereUniqueWithoutBuchInput | Prisma.ExemplarUpdateWithWhereUniqueWithoutBuchInput[]
  updateMany?: Prisma.ExemplarUpdateManyWithWhereWithoutBuchInput | Prisma.ExemplarUpdateManyWithWhereWithoutBuchInput[]
  deleteMany?: Prisma.ExemplarScalarWhereInput | Prisma.ExemplarScalarWhereInput[]
}

export type ExemplarCreateNestedOneWithoutEntlehnungInput = {
  create?: Prisma.XOR<Prisma.ExemplarCreateWithoutEntlehnungInput, Prisma.ExemplarUncheckedCreateWithoutEntlehnungInput>
  connectOrCreate?: Prisma.ExemplarCreateOrConnectWithoutEntlehnungInput
  connect?: Prisma.ExemplarWhereUniqueInput
}

export type ExemplarUpdateOneRequiredWithoutEntlehnungNestedInput = {
  create?: Prisma.XOR<Prisma.ExemplarCreateWithoutEntlehnungInput, Prisma.ExemplarUncheckedCreateWithoutEntlehnungInput>
  connectOrCreate?: Prisma.ExemplarCreateOrConnectWithoutEntlehnungInput
  upsert?: Prisma.ExemplarUpsertWithoutEntlehnungInput
  connect?: Prisma.ExemplarWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ExemplarUpdateToOneWithWhereWithoutEntlehnungInput, Prisma.ExemplarUpdateWithoutEntlehnungInput>, Prisma.ExemplarUncheckedUpdateWithoutEntlehnungInput>
}

export type ExemplarCreateWithoutFilialeInput = {
  buch: Prisma.BuchCreateNestedOneWithoutExemplareInput
  entlehnung?: Prisma.EntlehnungCreateNestedManyWithoutExemplarInput
}

export type ExemplarUncheckedCreateWithoutFilialeInput = {
  id?: number
  buchId: number
  entlehnung?: Prisma.EntlehnungUncheckedCreateNestedManyWithoutExemplarInput
}

export type ExemplarCreateOrConnectWithoutFilialeInput = {
  where: Prisma.ExemplarWhereUniqueInput
  create: Prisma.XOR<Prisma.ExemplarCreateWithoutFilialeInput, Prisma.ExemplarUncheckedCreateWithoutFilialeInput>
}

export type ExemplarCreateManyFilialeInputEnvelope = {
  data: Prisma.ExemplarCreateManyFilialeInput | Prisma.ExemplarCreateManyFilialeInput[]
}

export type ExemplarUpsertWithWhereUniqueWithoutFilialeInput = {
  where: Prisma.ExemplarWhereUniqueInput
  update: Prisma.XOR<Prisma.ExemplarUpdateWithoutFilialeInput, Prisma.ExemplarUncheckedUpdateWithoutFilialeInput>
  create: Prisma.XOR<Prisma.ExemplarCreateWithoutFilialeInput, Prisma.ExemplarUncheckedCreateWithoutFilialeInput>
}

export type ExemplarUpdateWithWhereUniqueWithoutFilialeInput = {
  where: Prisma.ExemplarWhereUniqueInput
  data: Prisma.XOR<Prisma.ExemplarUpdateWithoutFilialeInput, Prisma.ExemplarUncheckedUpdateWithoutFilialeInput>
}

export type ExemplarUpdateManyWithWhereWithoutFilialeInput = {
  where: Prisma.ExemplarScalarWhereInput
  data: Prisma.XOR<Prisma.ExemplarUpdateManyMutationInput, Prisma.ExemplarUncheckedUpdateManyWithoutFilialeInput>
}

export type ExemplarScalarWhereInput = {
  AND?: Prisma.ExemplarScalarWhereInput | Prisma.ExemplarScalarWhereInput[]
  OR?: Prisma.ExemplarScalarWhereInput[]
  NOT?: Prisma.ExemplarScalarWhereInput | Prisma.ExemplarScalarWhereInput[]
  id?: Prisma.IntFilter<"Exemplar"> | number
  buchId?: Prisma.IntFilter<"Exemplar"> | number
  filialeId?: Prisma.IntFilter<"Exemplar"> | number
}

export type ExemplarCreateWithoutBuchInput = {
  filiale: Prisma.FilialeCreateNestedOneWithoutExemplareInput
  entlehnung?: Prisma.EntlehnungCreateNestedManyWithoutExemplarInput
}

export type ExemplarUncheckedCreateWithoutBuchInput = {
  id?: number
  filialeId: number
  entlehnung?: Prisma.EntlehnungUncheckedCreateNestedManyWithoutExemplarInput
}

export type ExemplarCreateOrConnectWithoutBuchInput = {
  where: Prisma.ExemplarWhereUniqueInput
  create: Prisma.XOR<Prisma.ExemplarCreateWithoutBuchInput, Prisma.ExemplarUncheckedCreateWithoutBuchInput>
}

export type ExemplarCreateManyBuchInputEnvelope = {
  data: Prisma.ExemplarCreateManyBuchInput | Prisma.ExemplarCreateManyBuchInput[]
}

export type ExemplarUpsertWithWhereUniqueWithoutBuchInput = {
  where: Prisma.ExemplarWhereUniqueInput
  update: Prisma.XOR<Prisma.ExemplarUpdateWithoutBuchInput, Prisma.ExemplarUncheckedUpdateWithoutBuchInput>
  create: Prisma.XOR<Prisma.ExemplarCreateWithoutBuchInput, Prisma.ExemplarUncheckedCreateWithoutBuchInput>
}

export type ExemplarUpdateWithWhereUniqueWithoutBuchInput = {
  where: Prisma.ExemplarWhereUniqueInput
  data: Prisma.XOR<Prisma.ExemplarUpdateWithoutBuchInput, Prisma.ExemplarUncheckedUpdateWithoutBuchInput>
}

export type ExemplarUpdateManyWithWhereWithoutBuchInput = {
  where: Prisma.ExemplarScalarWhereInput
  data: Prisma.XOR<Prisma.ExemplarUpdateManyMutationInput, Prisma.ExemplarUncheckedUpdateManyWithoutBuchInput>
}

export type ExemplarCreateWithoutEntlehnungInput = {
  buch: Prisma.BuchCreateNestedOneWithoutExemplareInput
  filiale: Prisma.FilialeCreateNestedOneWithoutExemplareInput
}

export type ExemplarUncheckedCreateWithoutEntlehnungInput = {
  id?: number
  buchId: number
  filialeId: number
}

export type ExemplarCreateOrConnectWithoutEntlehnungInput = {
  where: Prisma.ExemplarWhereUniqueInput
  create: Prisma.XOR<Prisma.ExemplarCreateWithoutEntlehnungInput, Prisma.ExemplarUncheckedCreateWithoutEntlehnungInput>
}

export type ExemplarUpsertWithoutEntlehnungInput = {
  update: Prisma.XOR<Prisma.ExemplarUpdateWithoutEntlehnungInput, Prisma.ExemplarUncheckedUpdateWithoutEntlehnungInput>
  create: Prisma.XOR<Prisma.ExemplarCreateWithoutEntlehnungInput, Prisma.ExemplarUncheckedCreateWithoutEntlehnungInput>
  where?: Prisma.ExemplarWhereInput
}

export type ExemplarUpdateToOneWithWhereWithoutEntlehnungInput = {
  where?: Prisma.ExemplarWhereInput
  data: Prisma.XOR<Prisma.ExemplarUpdateWithoutEntlehnungInput, Prisma.ExemplarUncheckedUpdateWithoutEntlehnungInput>
}

export type ExemplarUpdateWithoutEntlehnungInput = {
  buch?: Prisma.BuchUpdateOneRequiredWithoutExemplareNestedInput
  filiale?: Prisma.FilialeUpdateOneRequiredWithoutExemplareNestedInput
}

export type ExemplarUncheckedUpdateWithoutEntlehnungInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  buchId?: Prisma.IntFieldUpdateOperationsInput | number
  filialeId?: Prisma.IntFieldUpdateOperationsInput | number
}

export type ExemplarCreateManyFilialeInput = {
  id?: number
  buchId: number
}

export type ExemplarUpdateWithoutFilialeInput = {
  buch?: Prisma.BuchUpdateOneRequiredWithoutExemplareNestedInput
  entlehnung?: Prisma.EntlehnungUpdateManyWithoutExemplarNestedInput
}

export type ExemplarUncheckedUpdateWithoutFilialeInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  buchId?: Prisma.IntFieldUpdateOperationsInput | number
  entlehnung?: Prisma.EntlehnungUncheckedUpdateManyWithoutExemplarNestedInput
}

export type ExemplarUncheckedUpdateManyWithoutFilialeInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  buchId?: Prisma.IntFieldUpdateOperationsInput | number
}

export type ExemplarCreateManyBuchInput = {
  id?: number
  filialeId: number
}

export type ExemplarUpdateWithoutBuchInput = {
  filiale?: Prisma.FilialeUpdateOneRequiredWithoutExemplareNestedInput
  entlehnung?: Prisma.EntlehnungUpdateManyWithoutExemplarNestedInput
}

export type ExemplarUncheckedUpdateWithoutBuchInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  filialeId?: Prisma.IntFieldUpdateOperationsInput | number
  entlehnung?: Prisma.EntlehnungUncheckedUpdateManyWithoutExemplarNestedInput
}

export type ExemplarUncheckedUpdateManyWithoutBuchInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  filialeId?: Prisma.IntFieldUpdateOperationsInput | number
}


/**
 * Count Type ExemplarCountOutputType
 */

export type ExemplarCountOutputType = {
  entlehnung: number
}

export type ExemplarCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  entlehnung?: boolean | ExemplarCountOutputTypeCountEntlehnungArgs
}

/**
 * ExemplarCountOutputType without action
 */
export type ExemplarCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ExemplarCountOutputType
   */
  select?: Prisma.ExemplarCountOutputTypeSelect<ExtArgs> | null
}

/**
 * ExemplarCountOutputType without action
 */
export type ExemplarCountOutputTypeCountEntlehnungArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.EntlehnungWhereInput
}


export type ExemplarSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  buchId?: boolean
  filialeId?: boolean
  buch?: boolean | Prisma.BuchDefaultArgs<ExtArgs>
  filiale?: boolean | Prisma.FilialeDefaultArgs<ExtArgs>
  entlehnung?: boolean | Prisma.Exemplar$entlehnungArgs<ExtArgs>
  _count?: boolean | Prisma.ExemplarCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["exemplar"]>

export type ExemplarSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  buchId?: boolean
  filialeId?: boolean
  buch?: boolean | Prisma.BuchDefaultArgs<ExtArgs>
  filiale?: boolean | Prisma.FilialeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["exemplar"]>

export type ExemplarSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  buchId?: boolean
  filialeId?: boolean
  buch?: boolean | Prisma.BuchDefaultArgs<ExtArgs>
  filiale?: boolean | Prisma.FilialeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["exemplar"]>

export type ExemplarSelectScalar = {
  id?: boolean
  buchId?: boolean
  filialeId?: boolean
}

export type ExemplarOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "buchId" | "filialeId", ExtArgs["result"]["exemplar"]>
export type ExemplarInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  buch?: boolean | Prisma.BuchDefaultArgs<ExtArgs>
  filiale?: boolean | Prisma.FilialeDefaultArgs<ExtArgs>
  entlehnung?: boolean | Prisma.Exemplar$entlehnungArgs<ExtArgs>
  _count?: boolean | Prisma.ExemplarCountOutputTypeDefaultArgs<ExtArgs>
}
export type ExemplarIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  buch?: boolean | Prisma.BuchDefaultArgs<ExtArgs>
  filiale?: boolean | Prisma.FilialeDefaultArgs<ExtArgs>
}
export type ExemplarIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  buch?: boolean | Prisma.BuchDefaultArgs<ExtArgs>
  filiale?: boolean | Prisma.FilialeDefaultArgs<ExtArgs>
}

export type $ExemplarPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Exemplar"
  objects: {
    buch: Prisma.$BuchPayload<ExtArgs>
    filiale: Prisma.$FilialePayload<ExtArgs>
    entlehnung: Prisma.$EntlehnungPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    buchId: number
    filialeId: number
  }, ExtArgs["result"]["exemplar"]>
  composites: {}
}

export type ExemplarGetPayload<S extends boolean | null | undefined | ExemplarDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ExemplarPayload, S>

export type ExemplarCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ExemplarFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ExemplarCountAggregateInputType | true
  }

export interface ExemplarDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Exemplar'], meta: { name: 'Exemplar' } }
  /**
   * Find zero or one Exemplar that matches the filter.
   * @param {ExemplarFindUniqueArgs} args - Arguments to find a Exemplar
   * @example
   * // Get one Exemplar
   * const exemplar = await prisma.exemplar.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ExemplarFindUniqueArgs>(args: Prisma.SelectSubset<T, ExemplarFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ExemplarClient<runtime.Types.Result.GetResult<Prisma.$ExemplarPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Exemplar that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ExemplarFindUniqueOrThrowArgs} args - Arguments to find a Exemplar
   * @example
   * // Get one Exemplar
   * const exemplar = await prisma.exemplar.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ExemplarFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ExemplarFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ExemplarClient<runtime.Types.Result.GetResult<Prisma.$ExemplarPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Exemplar that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ExemplarFindFirstArgs} args - Arguments to find a Exemplar
   * @example
   * // Get one Exemplar
   * const exemplar = await prisma.exemplar.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ExemplarFindFirstArgs>(args?: Prisma.SelectSubset<T, ExemplarFindFirstArgs<ExtArgs>>): Prisma.Prisma__ExemplarClient<runtime.Types.Result.GetResult<Prisma.$ExemplarPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Exemplar that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ExemplarFindFirstOrThrowArgs} args - Arguments to find a Exemplar
   * @example
   * // Get one Exemplar
   * const exemplar = await prisma.exemplar.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ExemplarFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ExemplarFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ExemplarClient<runtime.Types.Result.GetResult<Prisma.$ExemplarPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Exemplars that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ExemplarFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Exemplars
   * const exemplars = await prisma.exemplar.findMany()
   * 
   * // Get first 10 Exemplars
   * const exemplars = await prisma.exemplar.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const exemplarWithIdOnly = await prisma.exemplar.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ExemplarFindManyArgs>(args?: Prisma.SelectSubset<T, ExemplarFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ExemplarPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Exemplar.
   * @param {ExemplarCreateArgs} args - Arguments to create a Exemplar.
   * @example
   * // Create one Exemplar
   * const Exemplar = await prisma.exemplar.create({
   *   data: {
   *     // ... data to create a Exemplar
   *   }
   * })
   * 
   */
  create<T extends ExemplarCreateArgs>(args: Prisma.SelectSubset<T, ExemplarCreateArgs<ExtArgs>>): Prisma.Prisma__ExemplarClient<runtime.Types.Result.GetResult<Prisma.$ExemplarPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Exemplars.
   * @param {ExemplarCreateManyArgs} args - Arguments to create many Exemplars.
   * @example
   * // Create many Exemplars
   * const exemplar = await prisma.exemplar.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ExemplarCreateManyArgs>(args?: Prisma.SelectSubset<T, ExemplarCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Exemplars and returns the data saved in the database.
   * @param {ExemplarCreateManyAndReturnArgs} args - Arguments to create many Exemplars.
   * @example
   * // Create many Exemplars
   * const exemplar = await prisma.exemplar.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Exemplars and only return the `id`
   * const exemplarWithIdOnly = await prisma.exemplar.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ExemplarCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ExemplarCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ExemplarPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Exemplar.
   * @param {ExemplarDeleteArgs} args - Arguments to delete one Exemplar.
   * @example
   * // Delete one Exemplar
   * const Exemplar = await prisma.exemplar.delete({
   *   where: {
   *     // ... filter to delete one Exemplar
   *   }
   * })
   * 
   */
  delete<T extends ExemplarDeleteArgs>(args: Prisma.SelectSubset<T, ExemplarDeleteArgs<ExtArgs>>): Prisma.Prisma__ExemplarClient<runtime.Types.Result.GetResult<Prisma.$ExemplarPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Exemplar.
   * @param {ExemplarUpdateArgs} args - Arguments to update one Exemplar.
   * @example
   * // Update one Exemplar
   * const exemplar = await prisma.exemplar.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ExemplarUpdateArgs>(args: Prisma.SelectSubset<T, ExemplarUpdateArgs<ExtArgs>>): Prisma.Prisma__ExemplarClient<runtime.Types.Result.GetResult<Prisma.$ExemplarPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Exemplars.
   * @param {ExemplarDeleteManyArgs} args - Arguments to filter Exemplars to delete.
   * @example
   * // Delete a few Exemplars
   * const { count } = await prisma.exemplar.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ExemplarDeleteManyArgs>(args?: Prisma.SelectSubset<T, ExemplarDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Exemplars.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ExemplarUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Exemplars
   * const exemplar = await prisma.exemplar.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ExemplarUpdateManyArgs>(args: Prisma.SelectSubset<T, ExemplarUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Exemplars and returns the data updated in the database.
   * @param {ExemplarUpdateManyAndReturnArgs} args - Arguments to update many Exemplars.
   * @example
   * // Update many Exemplars
   * const exemplar = await prisma.exemplar.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Exemplars and only return the `id`
   * const exemplarWithIdOnly = await prisma.exemplar.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ExemplarUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ExemplarUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ExemplarPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Exemplar.
   * @param {ExemplarUpsertArgs} args - Arguments to update or create a Exemplar.
   * @example
   * // Update or create a Exemplar
   * const exemplar = await prisma.exemplar.upsert({
   *   create: {
   *     // ... data to create a Exemplar
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Exemplar we want to update
   *   }
   * })
   */
  upsert<T extends ExemplarUpsertArgs>(args: Prisma.SelectSubset<T, ExemplarUpsertArgs<ExtArgs>>): Prisma.Prisma__ExemplarClient<runtime.Types.Result.GetResult<Prisma.$ExemplarPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Exemplars.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ExemplarCountArgs} args - Arguments to filter Exemplars to count.
   * @example
   * // Count the number of Exemplars
   * const count = await prisma.exemplar.count({
   *   where: {
   *     // ... the filter for the Exemplars we want to count
   *   }
   * })
  **/
  count<T extends ExemplarCountArgs>(
    args?: Prisma.Subset<T, ExemplarCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ExemplarCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Exemplar.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ExemplarAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ExemplarAggregateArgs>(args: Prisma.Subset<T, ExemplarAggregateArgs>): Prisma.PrismaPromise<GetExemplarAggregateType<T>>

  /**
   * Group by Exemplar.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ExemplarGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ExemplarGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ExemplarGroupByArgs['orderBy'] }
      : { orderBy?: ExemplarGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ExemplarGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetExemplarGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Exemplar model
 */
readonly fields: ExemplarFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Exemplar.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ExemplarClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  buch<T extends Prisma.BuchDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.BuchDefaultArgs<ExtArgs>>): Prisma.Prisma__BuchClient<runtime.Types.Result.GetResult<Prisma.$BuchPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  filiale<T extends Prisma.FilialeDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.FilialeDefaultArgs<ExtArgs>>): Prisma.Prisma__FilialeClient<runtime.Types.Result.GetResult<Prisma.$FilialePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  entlehnung<T extends Prisma.Exemplar$entlehnungArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Exemplar$entlehnungArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$EntlehnungPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Exemplar model
 */
export interface ExemplarFieldRefs {
  readonly id: Prisma.FieldRef<"Exemplar", 'Int'>
  readonly buchId: Prisma.FieldRef<"Exemplar", 'Int'>
  readonly filialeId: Prisma.FieldRef<"Exemplar", 'Int'>
}
    

// Custom InputTypes
/**
 * Exemplar findUnique
 */
export type ExemplarFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Exemplar
   */
  select?: Prisma.ExemplarSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Exemplar
   */
  omit?: Prisma.ExemplarOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ExemplarInclude<ExtArgs> | null
  /**
   * Filter, which Exemplar to fetch.
   */
  where: Prisma.ExemplarWhereUniqueInput
}

/**
 * Exemplar findUniqueOrThrow
 */
export type ExemplarFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Exemplar
   */
  select?: Prisma.ExemplarSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Exemplar
   */
  omit?: Prisma.ExemplarOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ExemplarInclude<ExtArgs> | null
  /**
   * Filter, which Exemplar to fetch.
   */
  where: Prisma.ExemplarWhereUniqueInput
}

/**
 * Exemplar findFirst
 */
export type ExemplarFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Exemplar
   */
  select?: Prisma.ExemplarSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Exemplar
   */
  omit?: Prisma.ExemplarOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ExemplarInclude<ExtArgs> | null
  /**
   * Filter, which Exemplar to fetch.
   */
  where?: Prisma.ExemplarWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Exemplars to fetch.
   */
  orderBy?: Prisma.ExemplarOrderByWithRelationInput | Prisma.ExemplarOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Exemplars.
   */
  cursor?: Prisma.ExemplarWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Exemplars from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Exemplars.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Exemplars.
   */
  distinct?: Prisma.ExemplarScalarFieldEnum | Prisma.ExemplarScalarFieldEnum[]
}

/**
 * Exemplar findFirstOrThrow
 */
export type ExemplarFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Exemplar
   */
  select?: Prisma.ExemplarSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Exemplar
   */
  omit?: Prisma.ExemplarOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ExemplarInclude<ExtArgs> | null
  /**
   * Filter, which Exemplar to fetch.
   */
  where?: Prisma.ExemplarWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Exemplars to fetch.
   */
  orderBy?: Prisma.ExemplarOrderByWithRelationInput | Prisma.ExemplarOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Exemplars.
   */
  cursor?: Prisma.ExemplarWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Exemplars from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Exemplars.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Exemplars.
   */
  distinct?: Prisma.ExemplarScalarFieldEnum | Prisma.ExemplarScalarFieldEnum[]
}

/**
 * Exemplar findMany
 */
export type ExemplarFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Exemplar
   */
  select?: Prisma.ExemplarSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Exemplar
   */
  omit?: Prisma.ExemplarOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ExemplarInclude<ExtArgs> | null
  /**
   * Filter, which Exemplars to fetch.
   */
  where?: Prisma.ExemplarWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Exemplars to fetch.
   */
  orderBy?: Prisma.ExemplarOrderByWithRelationInput | Prisma.ExemplarOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Exemplars.
   */
  cursor?: Prisma.ExemplarWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Exemplars from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Exemplars.
   */
  skip?: number
  distinct?: Prisma.ExemplarScalarFieldEnum | Prisma.ExemplarScalarFieldEnum[]
}

/**
 * Exemplar create
 */
export type ExemplarCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Exemplar
   */
  select?: Prisma.ExemplarSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Exemplar
   */
  omit?: Prisma.ExemplarOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ExemplarInclude<ExtArgs> | null
  /**
   * The data needed to create a Exemplar.
   */
  data: Prisma.XOR<Prisma.ExemplarCreateInput, Prisma.ExemplarUncheckedCreateInput>
}

/**
 * Exemplar createMany
 */
export type ExemplarCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Exemplars.
   */
  data: Prisma.ExemplarCreateManyInput | Prisma.ExemplarCreateManyInput[]
}

/**
 * Exemplar createManyAndReturn
 */
export type ExemplarCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Exemplar
   */
  select?: Prisma.ExemplarSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Exemplar
   */
  omit?: Prisma.ExemplarOmit<ExtArgs> | null
  /**
   * The data used to create many Exemplars.
   */
  data: Prisma.ExemplarCreateManyInput | Prisma.ExemplarCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ExemplarIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Exemplar update
 */
export type ExemplarUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Exemplar
   */
  select?: Prisma.ExemplarSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Exemplar
   */
  omit?: Prisma.ExemplarOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ExemplarInclude<ExtArgs> | null
  /**
   * The data needed to update a Exemplar.
   */
  data: Prisma.XOR<Prisma.ExemplarUpdateInput, Prisma.ExemplarUncheckedUpdateInput>
  /**
   * Choose, which Exemplar to update.
   */
  where: Prisma.ExemplarWhereUniqueInput
}

/**
 * Exemplar updateMany
 */
export type ExemplarUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Exemplars.
   */
  data: Prisma.XOR<Prisma.ExemplarUpdateManyMutationInput, Prisma.ExemplarUncheckedUpdateManyInput>
  /**
   * Filter which Exemplars to update
   */
  where?: Prisma.ExemplarWhereInput
  /**
   * Limit how many Exemplars to update.
   */
  limit?: number
}

/**
 * Exemplar updateManyAndReturn
 */
export type ExemplarUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Exemplar
   */
  select?: Prisma.ExemplarSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Exemplar
   */
  omit?: Prisma.ExemplarOmit<ExtArgs> | null
  /**
   * The data used to update Exemplars.
   */
  data: Prisma.XOR<Prisma.ExemplarUpdateManyMutationInput, Prisma.ExemplarUncheckedUpdateManyInput>
  /**
   * Filter which Exemplars to update
   */
  where?: Prisma.ExemplarWhereInput
  /**
   * Limit how many Exemplars to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ExemplarIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Exemplar upsert
 */
export type ExemplarUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Exemplar
   */
  select?: Prisma.ExemplarSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Exemplar
   */
  omit?: Prisma.ExemplarOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ExemplarInclude<ExtArgs> | null
  /**
   * The filter to search for the Exemplar to update in case it exists.
   */
  where: Prisma.ExemplarWhereUniqueInput
  /**
   * In case the Exemplar found by the `where` argument doesn't exist, create a new Exemplar with this data.
   */
  create: Prisma.XOR<Prisma.ExemplarCreateInput, Prisma.ExemplarUncheckedCreateInput>
  /**
   * In case the Exemplar was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ExemplarUpdateInput, Prisma.ExemplarUncheckedUpdateInput>
}

/**
 * Exemplar delete
 */
export type ExemplarDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Exemplar
   */
  select?: Prisma.ExemplarSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Exemplar
   */
  omit?: Prisma.ExemplarOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ExemplarInclude<ExtArgs> | null
  /**
   * Filter which Exemplar to delete.
   */
  where: Prisma.ExemplarWhereUniqueInput
}

/**
 * Exemplar deleteMany
 */
export type ExemplarDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Exemplars to delete
   */
  where?: Prisma.ExemplarWhereInput
  /**
   * Limit how many Exemplars to delete.
   */
  limit?: number
}

/**
 * Exemplar.entlehnung
 */
export type Exemplar$entlehnungArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Entlehnung
   */
  select?: Prisma.EntlehnungSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Entlehnung
   */
  omit?: Prisma.EntlehnungOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EntlehnungInclude<ExtArgs> | null
  where?: Prisma.EntlehnungWhereInput
  orderBy?: Prisma.EntlehnungOrderByWithRelationInput | Prisma.EntlehnungOrderByWithRelationInput[]
  cursor?: Prisma.EntlehnungWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.EntlehnungScalarFieldEnum | Prisma.EntlehnungScalarFieldEnum[]
}

/**
 * Exemplar without action
 */
export type ExemplarDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Exemplar
   */
  select?: Prisma.ExemplarSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Exemplar
   */
  omit?: Prisma.ExemplarOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ExemplarInclude<ExtArgs> | null
}
