
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Filiale` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model Filiale
 * 
 */
export type FilialeModel = runtime.Types.Result.DefaultSelection<Prisma.$FilialePayload>

export type AggregateFiliale = {
  _count: FilialeCountAggregateOutputType | null
  _avg: FilialeAvgAggregateOutputType | null
  _sum: FilialeSumAggregateOutputType | null
  _min: FilialeMinAggregateOutputType | null
  _max: FilialeMaxAggregateOutputType | null
}

export type FilialeAvgAggregateOutputType = {
  id: number | null
}

export type FilialeSumAggregateOutputType = {
  id: number | null
}

export type FilialeMinAggregateOutputType = {
  id: number | null
  name: string | null
}

export type FilialeMaxAggregateOutputType = {
  id: number | null
  name: string | null
}

export type FilialeCountAggregateOutputType = {
  id: number
  name: number
  _all: number
}


export type FilialeAvgAggregateInputType = {
  id?: true
}

export type FilialeSumAggregateInputType = {
  id?: true
}

export type FilialeMinAggregateInputType = {
  id?: true
  name?: true
}

export type FilialeMaxAggregateInputType = {
  id?: true
  name?: true
}

export type FilialeCountAggregateInputType = {
  id?: true
  name?: true
  _all?: true
}

export type FilialeAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Filiale to aggregate.
   */
  where?: Prisma.FilialeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Filiales to fetch.
   */
  orderBy?: Prisma.FilialeOrderByWithRelationInput | Prisma.FilialeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.FilialeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Filiales from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Filiales.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Filiales
  **/
  _count?: true | FilialeCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: FilialeAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: FilialeSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: FilialeMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: FilialeMaxAggregateInputType
}

export type GetFilialeAggregateType<T extends FilialeAggregateArgs> = {
      [P in keyof T & keyof AggregateFiliale]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateFiliale[P]>
    : Prisma.GetScalarType<T[P], AggregateFiliale[P]>
}




export type FilialeGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.FilialeWhereInput
  orderBy?: Prisma.FilialeOrderByWithAggregationInput | Prisma.FilialeOrderByWithAggregationInput[]
  by: Prisma.FilialeScalarFieldEnum[] | Prisma.FilialeScalarFieldEnum
  having?: Prisma.FilialeScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: FilialeCountAggregateInputType | true
  _avg?: FilialeAvgAggregateInputType
  _sum?: FilialeSumAggregateInputType
  _min?: FilialeMinAggregateInputType
  _max?: FilialeMaxAggregateInputType
}

export type FilialeGroupByOutputType = {
  id: number
  name: string
  _count: FilialeCountAggregateOutputType | null
  _avg: FilialeAvgAggregateOutputType | null
  _sum: FilialeSumAggregateOutputType | null
  _min: FilialeMinAggregateOutputType | null
  _max: FilialeMaxAggregateOutputType | null
}

type GetFilialeGroupByPayload<T extends FilialeGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<FilialeGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof FilialeGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], FilialeGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], FilialeGroupByOutputType[P]>
      }
    >
  >



export type FilialeWhereInput = {
  AND?: Prisma.FilialeWhereInput | Prisma.FilialeWhereInput[]
  OR?: Prisma.FilialeWhereInput[]
  NOT?: Prisma.FilialeWhereInput | Prisma.FilialeWhereInput[]
  id?: Prisma.IntFilter<"Filiale"> | number
  name?: Prisma.StringFilter<"Filiale"> | string
  abteilung?: Prisma.AbteilungListRelationFilter
  mitarbeiter?: Prisma.MitarbeiterListRelationFilter
  exemplare?: Prisma.ExemplarListRelationFilter
}

export type FilialeOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  abteilung?: Prisma.AbteilungOrderByRelationAggregateInput
  mitarbeiter?: Prisma.MitarbeiterOrderByRelationAggregateInput
  exemplare?: Prisma.ExemplarOrderByRelationAggregateInput
}

export type FilialeWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  AND?: Prisma.FilialeWhereInput | Prisma.FilialeWhereInput[]
  OR?: Prisma.FilialeWhereInput[]
  NOT?: Prisma.FilialeWhereInput | Prisma.FilialeWhereInput[]
  name?: Prisma.StringFilter<"Filiale"> | string
  abteilung?: Prisma.AbteilungListRelationFilter
  mitarbeiter?: Prisma.MitarbeiterListRelationFilter
  exemplare?: Prisma.ExemplarListRelationFilter
}, "id">

export type FilialeOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  _count?: Prisma.FilialeCountOrderByAggregateInput
  _avg?: Prisma.FilialeAvgOrderByAggregateInput
  _max?: Prisma.FilialeMaxOrderByAggregateInput
  _min?: Prisma.FilialeMinOrderByAggregateInput
  _sum?: Prisma.FilialeSumOrderByAggregateInput
}

export type FilialeScalarWhereWithAggregatesInput = {
  AND?: Prisma.FilialeScalarWhereWithAggregatesInput | Prisma.FilialeScalarWhereWithAggregatesInput[]
  OR?: Prisma.FilialeScalarWhereWithAggregatesInput[]
  NOT?: Prisma.FilialeScalarWhereWithAggregatesInput | Prisma.FilialeScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"Filiale"> | number
  name?: Prisma.StringWithAggregatesFilter<"Filiale"> | string
}

export type FilialeCreateInput = {
  name: string
  abteilung?: Prisma.AbteilungCreateNestedManyWithoutFilialeInput
  mitarbeiter?: Prisma.MitarbeiterCreateNestedManyWithoutFilialeInput
  exemplare?: Prisma.ExemplarCreateNestedManyWithoutFilialeInput
}

export type FilialeUncheckedCreateInput = {
  id?: number
  name: string
  abteilung?: Prisma.AbteilungUncheckedCreateNestedManyWithoutFilialeInput
  mitarbeiter?: Prisma.MitarbeiterUncheckedCreateNestedManyWithoutFilialeInput
  exemplare?: Prisma.ExemplarUncheckedCreateNestedManyWithoutFilialeInput
}

export type FilialeUpdateInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  abteilung?: Prisma.AbteilungUpdateManyWithoutFilialeNestedInput
  mitarbeiter?: Prisma.MitarbeiterUpdateManyWithoutFilialeNestedInput
  exemplare?: Prisma.ExemplarUpdateManyWithoutFilialeNestedInput
}

export type FilialeUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  abteilung?: Prisma.AbteilungUncheckedUpdateManyWithoutFilialeNestedInput
  mitarbeiter?: Prisma.MitarbeiterUncheckedUpdateManyWithoutFilialeNestedInput
  exemplare?: Prisma.ExemplarUncheckedUpdateManyWithoutFilialeNestedInput
}

export type FilialeCreateManyInput = {
  id?: number
  name: string
}

export type FilialeUpdateManyMutationInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
}

export type FilialeUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
}

export type FilialeCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
}

export type FilialeAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type FilialeMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
}

export type FilialeMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
}

export type FilialeSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type FilialeScalarRelationFilter = {
  is?: Prisma.FilialeWhereInput
  isNot?: Prisma.FilialeWhereInput
}

export type StringFieldUpdateOperationsInput = {
  set?: string
}

export type IntFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type FilialeCreateNestedOneWithoutAbteilungInput = {
  create?: Prisma.XOR<Prisma.FilialeCreateWithoutAbteilungInput, Prisma.FilialeUncheckedCreateWithoutAbteilungInput>
  connectOrCreate?: Prisma.FilialeCreateOrConnectWithoutAbteilungInput
  connect?: Prisma.FilialeWhereUniqueInput
}

export type FilialeUpdateOneRequiredWithoutAbteilungNestedInput = {
  create?: Prisma.XOR<Prisma.FilialeCreateWithoutAbteilungInput, Prisma.FilialeUncheckedCreateWithoutAbteilungInput>
  connectOrCreate?: Prisma.FilialeCreateOrConnectWithoutAbteilungInput
  upsert?: Prisma.FilialeUpsertWithoutAbteilungInput
  connect?: Prisma.FilialeWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.FilialeUpdateToOneWithWhereWithoutAbteilungInput, Prisma.FilialeUpdateWithoutAbteilungInput>, Prisma.FilialeUncheckedUpdateWithoutAbteilungInput>
}

export type FilialeCreateNestedOneWithoutMitarbeiterInput = {
  create?: Prisma.XOR<Prisma.FilialeCreateWithoutMitarbeiterInput, Prisma.FilialeUncheckedCreateWithoutMitarbeiterInput>
  connectOrCreate?: Prisma.FilialeCreateOrConnectWithoutMitarbeiterInput
  connect?: Prisma.FilialeWhereUniqueInput
}

export type FilialeUpdateOneRequiredWithoutMitarbeiterNestedInput = {
  create?: Prisma.XOR<Prisma.FilialeCreateWithoutMitarbeiterInput, Prisma.FilialeUncheckedCreateWithoutMitarbeiterInput>
  connectOrCreate?: Prisma.FilialeCreateOrConnectWithoutMitarbeiterInput
  upsert?: Prisma.FilialeUpsertWithoutMitarbeiterInput
  connect?: Prisma.FilialeWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.FilialeUpdateToOneWithWhereWithoutMitarbeiterInput, Prisma.FilialeUpdateWithoutMitarbeiterInput>, Prisma.FilialeUncheckedUpdateWithoutMitarbeiterInput>
}

export type FilialeCreateNestedOneWithoutExemplareInput = {
  create?: Prisma.XOR<Prisma.FilialeCreateWithoutExemplareInput, Prisma.FilialeUncheckedCreateWithoutExemplareInput>
  connectOrCreate?: Prisma.FilialeCreateOrConnectWithoutExemplareInput
  connect?: Prisma.FilialeWhereUniqueInput
}

export type FilialeUpdateOneRequiredWithoutExemplareNestedInput = {
  create?: Prisma.XOR<Prisma.FilialeCreateWithoutExemplareInput, Prisma.FilialeUncheckedCreateWithoutExemplareInput>
  connectOrCreate?: Prisma.FilialeCreateOrConnectWithoutExemplareInput
  upsert?: Prisma.FilialeUpsertWithoutExemplareInput
  connect?: Prisma.FilialeWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.FilialeUpdateToOneWithWhereWithoutExemplareInput, Prisma.FilialeUpdateWithoutExemplareInput>, Prisma.FilialeUncheckedUpdateWithoutExemplareInput>
}

export type FilialeCreateWithoutAbteilungInput = {
  name: string
  mitarbeiter?: Prisma.MitarbeiterCreateNestedManyWithoutFilialeInput
  exemplare?: Prisma.ExemplarCreateNestedManyWithoutFilialeInput
}

export type FilialeUncheckedCreateWithoutAbteilungInput = {
  id?: number
  name: string
  mitarbeiter?: Prisma.MitarbeiterUncheckedCreateNestedManyWithoutFilialeInput
  exemplare?: Prisma.ExemplarUncheckedCreateNestedManyWithoutFilialeInput
}

export type FilialeCreateOrConnectWithoutAbteilungInput = {
  where: Prisma.FilialeWhereUniqueInput
  create: Prisma.XOR<Prisma.FilialeCreateWithoutAbteilungInput, Prisma.FilialeUncheckedCreateWithoutAbteilungInput>
}

export type FilialeUpsertWithoutAbteilungInput = {
  update: Prisma.XOR<Prisma.FilialeUpdateWithoutAbteilungInput, Prisma.FilialeUncheckedUpdateWithoutAbteilungInput>
  create: Prisma.XOR<Prisma.FilialeCreateWithoutAbteilungInput, Prisma.FilialeUncheckedCreateWithoutAbteilungInput>
  where?: Prisma.FilialeWhereInput
}

export type FilialeUpdateToOneWithWhereWithoutAbteilungInput = {
  where?: Prisma.FilialeWhereInput
  data: Prisma.XOR<Prisma.FilialeUpdateWithoutAbteilungInput, Prisma.FilialeUncheckedUpdateWithoutAbteilungInput>
}

export type FilialeUpdateWithoutAbteilungInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  mitarbeiter?: Prisma.MitarbeiterUpdateManyWithoutFilialeNestedInput
  exemplare?: Prisma.ExemplarUpdateManyWithoutFilialeNestedInput
}

export type FilialeUncheckedUpdateWithoutAbteilungInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  mitarbeiter?: Prisma.MitarbeiterUncheckedUpdateManyWithoutFilialeNestedInput
  exemplare?: Prisma.ExemplarUncheckedUpdateManyWithoutFilialeNestedInput
}

export type FilialeCreateWithoutMitarbeiterInput = {
  name: string
  abteilung?: Prisma.AbteilungCreateNestedManyWithoutFilialeInput
  exemplare?: Prisma.ExemplarCreateNestedManyWithoutFilialeInput
}

export type FilialeUncheckedCreateWithoutMitarbeiterInput = {
  id?: number
  name: string
  abteilung?: Prisma.AbteilungUncheckedCreateNestedManyWithoutFilialeInput
  exemplare?: Prisma.ExemplarUncheckedCreateNestedManyWithoutFilialeInput
}

export type FilialeCreateOrConnectWithoutMitarbeiterInput = {
  where: Prisma.FilialeWhereUniqueInput
  create: Prisma.XOR<Prisma.FilialeCreateWithoutMitarbeiterInput, Prisma.FilialeUncheckedCreateWithoutMitarbeiterInput>
}

export type FilialeUpsertWithoutMitarbeiterInput = {
  update: Prisma.XOR<Prisma.FilialeUpdateWithoutMitarbeiterInput, Prisma.FilialeUncheckedUpdateWithoutMitarbeiterInput>
  create: Prisma.XOR<Prisma.FilialeCreateWithoutMitarbeiterInput, Prisma.FilialeUncheckedCreateWithoutMitarbeiterInput>
  where?: Prisma.FilialeWhereInput
}

export type FilialeUpdateToOneWithWhereWithoutMitarbeiterInput = {
  where?: Prisma.FilialeWhereInput
  data: Prisma.XOR<Prisma.FilialeUpdateWithoutMitarbeiterInput, Prisma.FilialeUncheckedUpdateWithoutMitarbeiterInput>
}

export type FilialeUpdateWithoutMitarbeiterInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  abteilung?: Prisma.AbteilungUpdateManyWithoutFilialeNestedInput
  exemplare?: Prisma.ExemplarUpdateManyWithoutFilialeNestedInput
}

export type FilialeUncheckedUpdateWithoutMitarbeiterInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  abteilung?: Prisma.AbteilungUncheckedUpdateManyWithoutFilialeNestedInput
  exemplare?: Prisma.ExemplarUncheckedUpdateManyWithoutFilialeNestedInput
}

export type FilialeCreateWithoutExemplareInput = {
  name: string
  abteilung?: Prisma.AbteilungCreateNestedManyWithoutFilialeInput
  mitarbeiter?: Prisma.MitarbeiterCreateNestedManyWithoutFilialeInput
}

export type FilialeUncheckedCreateWithoutExemplareInput = {
  id?: number
  name: string
  abteilung?: Prisma.AbteilungUncheckedCreateNestedManyWithoutFilialeInput
  mitarbeiter?: Prisma.MitarbeiterUncheckedCreateNestedManyWithoutFilialeInput
}

export type FilialeCreateOrConnectWithoutExemplareInput = {
  where: Prisma.FilialeWhereUniqueInput
  create: Prisma.XOR<Prisma.FilialeCreateWithoutExemplareInput, Prisma.FilialeUncheckedCreateWithoutExemplareInput>
}

export type FilialeUpsertWithoutExemplareInput = {
  update: Prisma.XOR<Prisma.FilialeUpdateWithoutExemplareInput, Prisma.FilialeUncheckedUpdateWithoutExemplareInput>
  create: Prisma.XOR<Prisma.FilialeCreateWithoutExemplareInput, Prisma.FilialeUncheckedCreateWithoutExemplareInput>
  where?: Prisma.FilialeWhereInput
}

export type FilialeUpdateToOneWithWhereWithoutExemplareInput = {
  where?: Prisma.FilialeWhereInput
  data: Prisma.XOR<Prisma.FilialeUpdateWithoutExemplareInput, Prisma.FilialeUncheckedUpdateWithoutExemplareInput>
}

export type FilialeUpdateWithoutExemplareInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  abteilung?: Prisma.AbteilungUpdateManyWithoutFilialeNestedInput
  mitarbeiter?: Prisma.MitarbeiterUpdateManyWithoutFilialeNestedInput
}

export type FilialeUncheckedUpdateWithoutExemplareInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  abteilung?: Prisma.AbteilungUncheckedUpdateManyWithoutFilialeNestedInput
  mitarbeiter?: Prisma.MitarbeiterUncheckedUpdateManyWithoutFilialeNestedInput
}


/**
 * Count Type FilialeCountOutputType
 */

export type FilialeCountOutputType = {
  abteilung: number
  mitarbeiter: number
  exemplare: number
}

export type FilialeCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  abteilung?: boolean | FilialeCountOutputTypeCountAbteilungArgs
  mitarbeiter?: boolean | FilialeCountOutputTypeCountMitarbeiterArgs
  exemplare?: boolean | FilialeCountOutputTypeCountExemplareArgs
}

/**
 * FilialeCountOutputType without action
 */
export type FilialeCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FilialeCountOutputType
   */
  select?: Prisma.FilialeCountOutputTypeSelect<ExtArgs> | null
}

/**
 * FilialeCountOutputType without action
 */
export type FilialeCountOutputTypeCountAbteilungArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AbteilungWhereInput
}

/**
 * FilialeCountOutputType without action
 */
export type FilialeCountOutputTypeCountMitarbeiterArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.MitarbeiterWhereInput
}

/**
 * FilialeCountOutputType without action
 */
export type FilialeCountOutputTypeCountExemplareArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ExemplarWhereInput
}


export type FilialeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  abteilung?: boolean | Prisma.Filiale$abteilungArgs<ExtArgs>
  mitarbeiter?: boolean | Prisma.Filiale$mitarbeiterArgs<ExtArgs>
  exemplare?: boolean | Prisma.Filiale$exemplareArgs<ExtArgs>
  _count?: boolean | Prisma.FilialeCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["filiale"]>

export type FilialeSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
}, ExtArgs["result"]["filiale"]>

export type FilialeSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
}, ExtArgs["result"]["filiale"]>

export type FilialeSelectScalar = {
  id?: boolean
  name?: boolean
}

export type FilialeOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name", ExtArgs["result"]["filiale"]>
export type FilialeInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  abteilung?: boolean | Prisma.Filiale$abteilungArgs<ExtArgs>
  mitarbeiter?: boolean | Prisma.Filiale$mitarbeiterArgs<ExtArgs>
  exemplare?: boolean | Prisma.Filiale$exemplareArgs<ExtArgs>
  _count?: boolean | Prisma.FilialeCountOutputTypeDefaultArgs<ExtArgs>
}
export type FilialeIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type FilialeIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $FilialePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Filiale"
  objects: {
    abteilung: Prisma.$AbteilungPayload<ExtArgs>[]
    mitarbeiter: Prisma.$MitarbeiterPayload<ExtArgs>[]
    exemplare: Prisma.$ExemplarPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    name: string
  }, ExtArgs["result"]["filiale"]>
  composites: {}
}

export type FilialeGetPayload<S extends boolean | null | undefined | FilialeDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$FilialePayload, S>

export type FilialeCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<FilialeFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: FilialeCountAggregateInputType | true
  }

export interface FilialeDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Filiale'], meta: { name: 'Filiale' } }
  /**
   * Find zero or one Filiale that matches the filter.
   * @param {FilialeFindUniqueArgs} args - Arguments to find a Filiale
   * @example
   * // Get one Filiale
   * const filiale = await prisma.filiale.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends FilialeFindUniqueArgs>(args: Prisma.SelectSubset<T, FilialeFindUniqueArgs<ExtArgs>>): Prisma.Prisma__FilialeClient<runtime.Types.Result.GetResult<Prisma.$FilialePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Filiale that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {FilialeFindUniqueOrThrowArgs} args - Arguments to find a Filiale
   * @example
   * // Get one Filiale
   * const filiale = await prisma.filiale.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends FilialeFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, FilialeFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__FilialeClient<runtime.Types.Result.GetResult<Prisma.$FilialePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Filiale that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FilialeFindFirstArgs} args - Arguments to find a Filiale
   * @example
   * // Get one Filiale
   * const filiale = await prisma.filiale.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends FilialeFindFirstArgs>(args?: Prisma.SelectSubset<T, FilialeFindFirstArgs<ExtArgs>>): Prisma.Prisma__FilialeClient<runtime.Types.Result.GetResult<Prisma.$FilialePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Filiale that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FilialeFindFirstOrThrowArgs} args - Arguments to find a Filiale
   * @example
   * // Get one Filiale
   * const filiale = await prisma.filiale.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends FilialeFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, FilialeFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__FilialeClient<runtime.Types.Result.GetResult<Prisma.$FilialePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Filiales that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FilialeFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Filiales
   * const filiales = await prisma.filiale.findMany()
   * 
   * // Get first 10 Filiales
   * const filiales = await prisma.filiale.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const filialeWithIdOnly = await prisma.filiale.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends FilialeFindManyArgs>(args?: Prisma.SelectSubset<T, FilialeFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FilialePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Filiale.
   * @param {FilialeCreateArgs} args - Arguments to create a Filiale.
   * @example
   * // Create one Filiale
   * const Filiale = await prisma.filiale.create({
   *   data: {
   *     // ... data to create a Filiale
   *   }
   * })
   * 
   */
  create<T extends FilialeCreateArgs>(args: Prisma.SelectSubset<T, FilialeCreateArgs<ExtArgs>>): Prisma.Prisma__FilialeClient<runtime.Types.Result.GetResult<Prisma.$FilialePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Filiales.
   * @param {FilialeCreateManyArgs} args - Arguments to create many Filiales.
   * @example
   * // Create many Filiales
   * const filiale = await prisma.filiale.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends FilialeCreateManyArgs>(args?: Prisma.SelectSubset<T, FilialeCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Filiales and returns the data saved in the database.
   * @param {FilialeCreateManyAndReturnArgs} args - Arguments to create many Filiales.
   * @example
   * // Create many Filiales
   * const filiale = await prisma.filiale.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Filiales and only return the `id`
   * const filialeWithIdOnly = await prisma.filiale.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends FilialeCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, FilialeCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FilialePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Filiale.
   * @param {FilialeDeleteArgs} args - Arguments to delete one Filiale.
   * @example
   * // Delete one Filiale
   * const Filiale = await prisma.filiale.delete({
   *   where: {
   *     // ... filter to delete one Filiale
   *   }
   * })
   * 
   */
  delete<T extends FilialeDeleteArgs>(args: Prisma.SelectSubset<T, FilialeDeleteArgs<ExtArgs>>): Prisma.Prisma__FilialeClient<runtime.Types.Result.GetResult<Prisma.$FilialePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Filiale.
   * @param {FilialeUpdateArgs} args - Arguments to update one Filiale.
   * @example
   * // Update one Filiale
   * const filiale = await prisma.filiale.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends FilialeUpdateArgs>(args: Prisma.SelectSubset<T, FilialeUpdateArgs<ExtArgs>>): Prisma.Prisma__FilialeClient<runtime.Types.Result.GetResult<Prisma.$FilialePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Filiales.
   * @param {FilialeDeleteManyArgs} args - Arguments to filter Filiales to delete.
   * @example
   * // Delete a few Filiales
   * const { count } = await prisma.filiale.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends FilialeDeleteManyArgs>(args?: Prisma.SelectSubset<T, FilialeDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Filiales.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FilialeUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Filiales
   * const filiale = await prisma.filiale.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends FilialeUpdateManyArgs>(args: Prisma.SelectSubset<T, FilialeUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Filiales and returns the data updated in the database.
   * @param {FilialeUpdateManyAndReturnArgs} args - Arguments to update many Filiales.
   * @example
   * // Update many Filiales
   * const filiale = await prisma.filiale.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Filiales and only return the `id`
   * const filialeWithIdOnly = await prisma.filiale.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends FilialeUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, FilialeUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FilialePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Filiale.
   * @param {FilialeUpsertArgs} args - Arguments to update or create a Filiale.
   * @example
   * // Update or create a Filiale
   * const filiale = await prisma.filiale.upsert({
   *   create: {
   *     // ... data to create a Filiale
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Filiale we want to update
   *   }
   * })
   */
  upsert<T extends FilialeUpsertArgs>(args: Prisma.SelectSubset<T, FilialeUpsertArgs<ExtArgs>>): Prisma.Prisma__FilialeClient<runtime.Types.Result.GetResult<Prisma.$FilialePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Filiales.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FilialeCountArgs} args - Arguments to filter Filiales to count.
   * @example
   * // Count the number of Filiales
   * const count = await prisma.filiale.count({
   *   where: {
   *     // ... the filter for the Filiales we want to count
   *   }
   * })
  **/
  count<T extends FilialeCountArgs>(
    args?: Prisma.Subset<T, FilialeCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], FilialeCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Filiale.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FilialeAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends FilialeAggregateArgs>(args: Prisma.Subset<T, FilialeAggregateArgs>): Prisma.PrismaPromise<GetFilialeAggregateType<T>>

  /**
   * Group by Filiale.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FilialeGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends FilialeGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: FilialeGroupByArgs['orderBy'] }
      : { orderBy?: FilialeGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, FilialeGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetFilialeGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Filiale model
 */
readonly fields: FilialeFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Filiale.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__FilialeClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  abteilung<T extends Prisma.Filiale$abteilungArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Filiale$abteilungArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AbteilungPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  mitarbeiter<T extends Prisma.Filiale$mitarbeiterArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Filiale$mitarbeiterArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MitarbeiterPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  exemplare<T extends Prisma.Filiale$exemplareArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Filiale$exemplareArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ExemplarPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Filiale model
 */
export interface FilialeFieldRefs {
  readonly id: Prisma.FieldRef<"Filiale", 'Int'>
  readonly name: Prisma.FieldRef<"Filiale", 'String'>
}
    

// Custom InputTypes
/**
 * Filiale findUnique
 */
export type FilialeFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Filiale
   */
  select?: Prisma.FilialeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Filiale
   */
  omit?: Prisma.FilialeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FilialeInclude<ExtArgs> | null
  /**
   * Filter, which Filiale to fetch.
   */
  where: Prisma.FilialeWhereUniqueInput
}

/**
 * Filiale findUniqueOrThrow
 */
export type FilialeFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Filiale
   */
  select?: Prisma.FilialeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Filiale
   */
  omit?: Prisma.FilialeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FilialeInclude<ExtArgs> | null
  /**
   * Filter, which Filiale to fetch.
   */
  where: Prisma.FilialeWhereUniqueInput
}

/**
 * Filiale findFirst
 */
export type FilialeFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Filiale
   */
  select?: Prisma.FilialeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Filiale
   */
  omit?: Prisma.FilialeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FilialeInclude<ExtArgs> | null
  /**
   * Filter, which Filiale to fetch.
   */
  where?: Prisma.FilialeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Filiales to fetch.
   */
  orderBy?: Prisma.FilialeOrderByWithRelationInput | Prisma.FilialeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Filiales.
   */
  cursor?: Prisma.FilialeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Filiales from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Filiales.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Filiales.
   */
  distinct?: Prisma.FilialeScalarFieldEnum | Prisma.FilialeScalarFieldEnum[]
}

/**
 * Filiale findFirstOrThrow
 */
export type FilialeFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Filiale
   */
  select?: Prisma.FilialeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Filiale
   */
  omit?: Prisma.FilialeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FilialeInclude<ExtArgs> | null
  /**
   * Filter, which Filiale to fetch.
   */
  where?: Prisma.FilialeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Filiales to fetch.
   */
  orderBy?: Prisma.FilialeOrderByWithRelationInput | Prisma.FilialeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Filiales.
   */
  cursor?: Prisma.FilialeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Filiales from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Filiales.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Filiales.
   */
  distinct?: Prisma.FilialeScalarFieldEnum | Prisma.FilialeScalarFieldEnum[]
}

/**
 * Filiale findMany
 */
export type FilialeFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Filiale
   */
  select?: Prisma.FilialeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Filiale
   */
  omit?: Prisma.FilialeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FilialeInclude<ExtArgs> | null
  /**
   * Filter, which Filiales to fetch.
   */
  where?: Prisma.FilialeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Filiales to fetch.
   */
  orderBy?: Prisma.FilialeOrderByWithRelationInput | Prisma.FilialeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Filiales.
   */
  cursor?: Prisma.FilialeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Filiales from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Filiales.
   */
  skip?: number
  distinct?: Prisma.FilialeScalarFieldEnum | Prisma.FilialeScalarFieldEnum[]
}

/**
 * Filiale create
 */
export type FilialeCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Filiale
   */
  select?: Prisma.FilialeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Filiale
   */
  omit?: Prisma.FilialeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FilialeInclude<ExtArgs> | null
  /**
   * The data needed to create a Filiale.
   */
  data: Prisma.XOR<Prisma.FilialeCreateInput, Prisma.FilialeUncheckedCreateInput>
}

/**
 * Filiale createMany
 */
export type FilialeCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Filiales.
   */
  data: Prisma.FilialeCreateManyInput | Prisma.FilialeCreateManyInput[]
}

/**
 * Filiale createManyAndReturn
 */
export type FilialeCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Filiale
   */
  select?: Prisma.FilialeSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Filiale
   */
  omit?: Prisma.FilialeOmit<ExtArgs> | null
  /**
   * The data used to create many Filiales.
   */
  data: Prisma.FilialeCreateManyInput | Prisma.FilialeCreateManyInput[]
}

/**
 * Filiale update
 */
export type FilialeUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Filiale
   */
  select?: Prisma.FilialeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Filiale
   */
  omit?: Prisma.FilialeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FilialeInclude<ExtArgs> | null
  /**
   * The data needed to update a Filiale.
   */
  data: Prisma.XOR<Prisma.FilialeUpdateInput, Prisma.FilialeUncheckedUpdateInput>
  /**
   * Choose, which Filiale to update.
   */
  where: Prisma.FilialeWhereUniqueInput
}

/**
 * Filiale updateMany
 */
export type FilialeUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Filiales.
   */
  data: Prisma.XOR<Prisma.FilialeUpdateManyMutationInput, Prisma.FilialeUncheckedUpdateManyInput>
  /**
   * Filter which Filiales to update
   */
  where?: Prisma.FilialeWhereInput
  /**
   * Limit how many Filiales to update.
   */
  limit?: number
}

/**
 * Filiale updateManyAndReturn
 */
export type FilialeUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Filiale
   */
  select?: Prisma.FilialeSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Filiale
   */
  omit?: Prisma.FilialeOmit<ExtArgs> | null
  /**
   * The data used to update Filiales.
   */
  data: Prisma.XOR<Prisma.FilialeUpdateManyMutationInput, Prisma.FilialeUncheckedUpdateManyInput>
  /**
   * Filter which Filiales to update
   */
  where?: Prisma.FilialeWhereInput
  /**
   * Limit how many Filiales to update.
   */
  limit?: number
}

/**
 * Filiale upsert
 */
export type FilialeUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Filiale
   */
  select?: Prisma.FilialeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Filiale
   */
  omit?: Prisma.FilialeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FilialeInclude<ExtArgs> | null
  /**
   * The filter to search for the Filiale to update in case it exists.
   */
  where: Prisma.FilialeWhereUniqueInput
  /**
   * In case the Filiale found by the `where` argument doesn't exist, create a new Filiale with this data.
   */
  create: Prisma.XOR<Prisma.FilialeCreateInput, Prisma.FilialeUncheckedCreateInput>
  /**
   * In case the Filiale was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.FilialeUpdateInput, Prisma.FilialeUncheckedUpdateInput>
}

/**
 * Filiale delete
 */
export type FilialeDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Filiale
   */
  select?: Prisma.FilialeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Filiale
   */
  omit?: Prisma.FilialeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FilialeInclude<ExtArgs> | null
  /**
   * Filter which Filiale to delete.
   */
  where: Prisma.FilialeWhereUniqueInput
}

/**
 * Filiale deleteMany
 */
export type FilialeDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Filiales to delete
   */
  where?: Prisma.FilialeWhereInput
  /**
   * Limit how many Filiales to delete.
   */
  limit?: number
}

/**
 * Filiale.abteilung
 */
export type Filiale$abteilungArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Abteilung
   */
  select?: Prisma.AbteilungSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Abteilung
   */
  omit?: Prisma.AbteilungOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AbteilungInclude<ExtArgs> | null
  where?: Prisma.AbteilungWhereInput
  orderBy?: Prisma.AbteilungOrderByWithRelationInput | Prisma.AbteilungOrderByWithRelationInput[]
  cursor?: Prisma.AbteilungWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.AbteilungScalarFieldEnum | Prisma.AbteilungScalarFieldEnum[]
}

/**
 * Filiale.mitarbeiter
 */
export type Filiale$mitarbeiterArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Mitarbeiter
   */
  select?: Prisma.MitarbeiterSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Mitarbeiter
   */
  omit?: Prisma.MitarbeiterOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MitarbeiterInclude<ExtArgs> | null
  where?: Prisma.MitarbeiterWhereInput
  orderBy?: Prisma.MitarbeiterOrderByWithRelationInput | Prisma.MitarbeiterOrderByWithRelationInput[]
  cursor?: Prisma.MitarbeiterWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.MitarbeiterScalarFieldEnum | Prisma.MitarbeiterScalarFieldEnum[]
}

/**
 * Filiale.exemplare
 */
export type Filiale$exemplareArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Exemplar
   */
  select?: Prisma.ExemplarSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Exemplar
   */
  omit?: Prisma.ExemplarOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ExemplarInclude<ExtArgs> | null
  where?: Prisma.ExemplarWhereInput
  orderBy?: Prisma.ExemplarOrderByWithRelationInput | Prisma.ExemplarOrderByWithRelationInput[]
  cursor?: Prisma.ExemplarWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ExemplarScalarFieldEnum | Prisma.ExemplarScalarFieldEnum[]
}

/**
 * Filiale without action
 */
export type FilialeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Filiale
   */
  select?: Prisma.FilialeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Filiale
   */
  omit?: Prisma.FilialeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FilialeInclude<ExtArgs> | null
}
