
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Kunde` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums.ts"
import type * as Prisma from "../internal/prismaNamespace.ts"

/**
 * Model Kunde
 * 
 */
export type KundeModel = runtime.Types.Result.DefaultSelection<Prisma.$KundePayload>

export type AggregateKunde = {
  _count: KundeCountAggregateOutputType | null
  _avg: KundeAvgAggregateOutputType | null
  _sum: KundeSumAggregateOutputType | null
  _min: KundeMinAggregateOutputType | null
  _max: KundeMaxAggregateOutputType | null
}

export type KundeAvgAggregateOutputType = {
  id: number | null
}

export type KundeSumAggregateOutputType = {
  id: number | null
}

export type KundeMinAggregateOutputType = {
  id: number | null
  name: string | null
  email: string | null
}

export type KundeMaxAggregateOutputType = {
  id: number | null
  name: string | null
  email: string | null
}

export type KundeCountAggregateOutputType = {
  id: number
  name: number
  email: number
  _all: number
}


export type KundeAvgAggregateInputType = {
  id?: true
}

export type KundeSumAggregateInputType = {
  id?: true
}

export type KundeMinAggregateInputType = {
  id?: true
  name?: true
  email?: true
}

export type KundeMaxAggregateInputType = {
  id?: true
  name?: true
  email?: true
}

export type KundeCountAggregateInputType = {
  id?: true
  name?: true
  email?: true
  _all?: true
}

export type KundeAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Kunde to aggregate.
   */
  where?: Prisma.KundeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Kundes to fetch.
   */
  orderBy?: Prisma.KundeOrderByWithRelationInput | Prisma.KundeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.KundeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Kundes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Kundes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Kundes
  **/
  _count?: true | KundeCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: KundeAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: KundeSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: KundeMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: KundeMaxAggregateInputType
}

export type GetKundeAggregateType<T extends KundeAggregateArgs> = {
      [P in keyof T & keyof AggregateKunde]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateKunde[P]>
    : Prisma.GetScalarType<T[P], AggregateKunde[P]>
}




export type KundeGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.KundeWhereInput
  orderBy?: Prisma.KundeOrderByWithAggregationInput | Prisma.KundeOrderByWithAggregationInput[]
  by: Prisma.KundeScalarFieldEnum[] | Prisma.KundeScalarFieldEnum
  having?: Prisma.KundeScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: KundeCountAggregateInputType | true
  _avg?: KundeAvgAggregateInputType
  _sum?: KundeSumAggregateInputType
  _min?: KundeMinAggregateInputType
  _max?: KundeMaxAggregateInputType
}

export type KundeGroupByOutputType = {
  id: number
  name: string
  email: string | null
  _count: KundeCountAggregateOutputType | null
  _avg: KundeAvgAggregateOutputType | null
  _sum: KundeSumAggregateOutputType | null
  _min: KundeMinAggregateOutputType | null
  _max: KundeMaxAggregateOutputType | null
}

type GetKundeGroupByPayload<T extends KundeGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<KundeGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof KundeGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], KundeGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], KundeGroupByOutputType[P]>
      }
    >
  >



export type KundeWhereInput = {
  AND?: Prisma.KundeWhereInput | Prisma.KundeWhereInput[]
  OR?: Prisma.KundeWhereInput[]
  NOT?: Prisma.KundeWhereInput | Prisma.KundeWhereInput[]
  id?: Prisma.IntFilter<"Kunde"> | number
  name?: Prisma.StringFilter<"Kunde"> | string
  email?: Prisma.StringNullableFilter<"Kunde"> | string | null
  entlehnungen?: Prisma.EntlehnungListRelationFilter
}

export type KundeOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  email?: Prisma.SortOrderInput | Prisma.SortOrder
  entlehnungen?: Prisma.EntlehnungOrderByRelationAggregateInput
}

export type KundeWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  email?: string
  AND?: Prisma.KundeWhereInput | Prisma.KundeWhereInput[]
  OR?: Prisma.KundeWhereInput[]
  NOT?: Prisma.KundeWhereInput | Prisma.KundeWhereInput[]
  name?: Prisma.StringFilter<"Kunde"> | string
  entlehnungen?: Prisma.EntlehnungListRelationFilter
}, "id" | "email">

export type KundeOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  email?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.KundeCountOrderByAggregateInput
  _avg?: Prisma.KundeAvgOrderByAggregateInput
  _max?: Prisma.KundeMaxOrderByAggregateInput
  _min?: Prisma.KundeMinOrderByAggregateInput
  _sum?: Prisma.KundeSumOrderByAggregateInput
}

export type KundeScalarWhereWithAggregatesInput = {
  AND?: Prisma.KundeScalarWhereWithAggregatesInput | Prisma.KundeScalarWhereWithAggregatesInput[]
  OR?: Prisma.KundeScalarWhereWithAggregatesInput[]
  NOT?: Prisma.KundeScalarWhereWithAggregatesInput | Prisma.KundeScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"Kunde"> | number
  name?: Prisma.StringWithAggregatesFilter<"Kunde"> | string
  email?: Prisma.StringNullableWithAggregatesFilter<"Kunde"> | string | null
}

export type KundeCreateInput = {
  name: string
  email?: string | null
  entlehnungen?: Prisma.EntlehnungCreateNestedManyWithoutKundeInput
}

export type KundeUncheckedCreateInput = {
  id?: number
  name: string
  email?: string | null
  entlehnungen?: Prisma.EntlehnungUncheckedCreateNestedManyWithoutKundeInput
}

export type KundeUpdateInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  entlehnungen?: Prisma.EntlehnungUpdateManyWithoutKundeNestedInput
}

export type KundeUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  entlehnungen?: Prisma.EntlehnungUncheckedUpdateManyWithoutKundeNestedInput
}

export type KundeCreateManyInput = {
  id?: number
  name: string
  email?: string | null
}

export type KundeUpdateManyMutationInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type KundeUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type KundeCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  email?: Prisma.SortOrder
}

export type KundeAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type KundeMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  email?: Prisma.SortOrder
}

export type KundeMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  email?: Prisma.SortOrder
}

export type KundeSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
}

export type KundeScalarRelationFilter = {
  is?: Prisma.KundeWhereInput
  isNot?: Prisma.KundeWhereInput
}

export type NullableStringFieldUpdateOperationsInput = {
  set?: string | null
}

export type KundeCreateNestedOneWithoutEntlehnungenInput = {
  create?: Prisma.XOR<Prisma.KundeCreateWithoutEntlehnungenInput, Prisma.KundeUncheckedCreateWithoutEntlehnungenInput>
  connectOrCreate?: Prisma.KundeCreateOrConnectWithoutEntlehnungenInput
  connect?: Prisma.KundeWhereUniqueInput
}

export type KundeUpdateOneRequiredWithoutEntlehnungenNestedInput = {
  create?: Prisma.XOR<Prisma.KundeCreateWithoutEntlehnungenInput, Prisma.KundeUncheckedCreateWithoutEntlehnungenInput>
  connectOrCreate?: Prisma.KundeCreateOrConnectWithoutEntlehnungenInput
  upsert?: Prisma.KundeUpsertWithoutEntlehnungenInput
  connect?: Prisma.KundeWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.KundeUpdateToOneWithWhereWithoutEntlehnungenInput, Prisma.KundeUpdateWithoutEntlehnungenInput>, Prisma.KundeUncheckedUpdateWithoutEntlehnungenInput>
}

export type KundeCreateWithoutEntlehnungenInput = {
  name: string
  email?: string | null
}

export type KundeUncheckedCreateWithoutEntlehnungenInput = {
  id?: number
  name: string
  email?: string | null
}

export type KundeCreateOrConnectWithoutEntlehnungenInput = {
  where: Prisma.KundeWhereUniqueInput
  create: Prisma.XOR<Prisma.KundeCreateWithoutEntlehnungenInput, Prisma.KundeUncheckedCreateWithoutEntlehnungenInput>
}

export type KundeUpsertWithoutEntlehnungenInput = {
  update: Prisma.XOR<Prisma.KundeUpdateWithoutEntlehnungenInput, Prisma.KundeUncheckedUpdateWithoutEntlehnungenInput>
  create: Prisma.XOR<Prisma.KundeCreateWithoutEntlehnungenInput, Prisma.KundeUncheckedCreateWithoutEntlehnungenInput>
  where?: Prisma.KundeWhereInput
}

export type KundeUpdateToOneWithWhereWithoutEntlehnungenInput = {
  where?: Prisma.KundeWhereInput
  data: Prisma.XOR<Prisma.KundeUpdateWithoutEntlehnungenInput, Prisma.KundeUncheckedUpdateWithoutEntlehnungenInput>
}

export type KundeUpdateWithoutEntlehnungenInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type KundeUncheckedUpdateWithoutEntlehnungenInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  name?: Prisma.StringFieldUpdateOperationsInput | string
  email?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}


/**
 * Count Type KundeCountOutputType
 */

export type KundeCountOutputType = {
  entlehnungen: number
}

export type KundeCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  entlehnungen?: boolean | KundeCountOutputTypeCountEntlehnungenArgs
}

/**
 * KundeCountOutputType without action
 */
export type KundeCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KundeCountOutputType
   */
  select?: Prisma.KundeCountOutputTypeSelect<ExtArgs> | null
}

/**
 * KundeCountOutputType without action
 */
export type KundeCountOutputTypeCountEntlehnungenArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.EntlehnungWhereInput
}


export type KundeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  email?: boolean
  entlehnungen?: boolean | Prisma.Kunde$entlehnungenArgs<ExtArgs>
  _count?: boolean | Prisma.KundeCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["kunde"]>

export type KundeSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  email?: boolean
}, ExtArgs["result"]["kunde"]>

export type KundeSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  email?: boolean
}, ExtArgs["result"]["kunde"]>

export type KundeSelectScalar = {
  id?: boolean
  name?: boolean
  email?: boolean
}

export type KundeOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "email", ExtArgs["result"]["kunde"]>
export type KundeInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  entlehnungen?: boolean | Prisma.Kunde$entlehnungenArgs<ExtArgs>
  _count?: boolean | Prisma.KundeCountOutputTypeDefaultArgs<ExtArgs>
}
export type KundeIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type KundeIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $KundePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Kunde"
  objects: {
    entlehnungen: Prisma.$EntlehnungPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    name: string
    email: string | null
  }, ExtArgs["result"]["kunde"]>
  composites: {}
}

export type KundeGetPayload<S extends boolean | null | undefined | KundeDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$KundePayload, S>

export type KundeCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<KundeFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: KundeCountAggregateInputType | true
  }

export interface KundeDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Kunde'], meta: { name: 'Kunde' } }
  /**
   * Find zero or one Kunde that matches the filter.
   * @param {KundeFindUniqueArgs} args - Arguments to find a Kunde
   * @example
   * // Get one Kunde
   * const kunde = await prisma.kunde.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends KundeFindUniqueArgs>(args: Prisma.SelectSubset<T, KundeFindUniqueArgs<ExtArgs>>): Prisma.Prisma__KundeClient<runtime.Types.Result.GetResult<Prisma.$KundePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Kunde that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {KundeFindUniqueOrThrowArgs} args - Arguments to find a Kunde
   * @example
   * // Get one Kunde
   * const kunde = await prisma.kunde.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends KundeFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, KundeFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__KundeClient<runtime.Types.Result.GetResult<Prisma.$KundePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Kunde that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {KundeFindFirstArgs} args - Arguments to find a Kunde
   * @example
   * // Get one Kunde
   * const kunde = await prisma.kunde.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends KundeFindFirstArgs>(args?: Prisma.SelectSubset<T, KundeFindFirstArgs<ExtArgs>>): Prisma.Prisma__KundeClient<runtime.Types.Result.GetResult<Prisma.$KundePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Kunde that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {KundeFindFirstOrThrowArgs} args - Arguments to find a Kunde
   * @example
   * // Get one Kunde
   * const kunde = await prisma.kunde.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends KundeFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, KundeFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__KundeClient<runtime.Types.Result.GetResult<Prisma.$KundePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Kundes that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {KundeFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Kundes
   * const kundes = await prisma.kunde.findMany()
   * 
   * // Get first 10 Kundes
   * const kundes = await prisma.kunde.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const kundeWithIdOnly = await prisma.kunde.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends KundeFindManyArgs>(args?: Prisma.SelectSubset<T, KundeFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$KundePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Kunde.
   * @param {KundeCreateArgs} args - Arguments to create a Kunde.
   * @example
   * // Create one Kunde
   * const Kunde = await prisma.kunde.create({
   *   data: {
   *     // ... data to create a Kunde
   *   }
   * })
   * 
   */
  create<T extends KundeCreateArgs>(args: Prisma.SelectSubset<T, KundeCreateArgs<ExtArgs>>): Prisma.Prisma__KundeClient<runtime.Types.Result.GetResult<Prisma.$KundePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Kundes.
   * @param {KundeCreateManyArgs} args - Arguments to create many Kundes.
   * @example
   * // Create many Kundes
   * const kunde = await prisma.kunde.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends KundeCreateManyArgs>(args?: Prisma.SelectSubset<T, KundeCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Kundes and returns the data saved in the database.
   * @param {KundeCreateManyAndReturnArgs} args - Arguments to create many Kundes.
   * @example
   * // Create many Kundes
   * const kunde = await prisma.kunde.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Kundes and only return the `id`
   * const kundeWithIdOnly = await prisma.kunde.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends KundeCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, KundeCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$KundePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Kunde.
   * @param {KundeDeleteArgs} args - Arguments to delete one Kunde.
   * @example
   * // Delete one Kunde
   * const Kunde = await prisma.kunde.delete({
   *   where: {
   *     // ... filter to delete one Kunde
   *   }
   * })
   * 
   */
  delete<T extends KundeDeleteArgs>(args: Prisma.SelectSubset<T, KundeDeleteArgs<ExtArgs>>): Prisma.Prisma__KundeClient<runtime.Types.Result.GetResult<Prisma.$KundePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Kunde.
   * @param {KundeUpdateArgs} args - Arguments to update one Kunde.
   * @example
   * // Update one Kunde
   * const kunde = await prisma.kunde.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends KundeUpdateArgs>(args: Prisma.SelectSubset<T, KundeUpdateArgs<ExtArgs>>): Prisma.Prisma__KundeClient<runtime.Types.Result.GetResult<Prisma.$KundePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Kundes.
   * @param {KundeDeleteManyArgs} args - Arguments to filter Kundes to delete.
   * @example
   * // Delete a few Kundes
   * const { count } = await prisma.kunde.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends KundeDeleteManyArgs>(args?: Prisma.SelectSubset<T, KundeDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Kundes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {KundeUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Kundes
   * const kunde = await prisma.kunde.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends KundeUpdateManyArgs>(args: Prisma.SelectSubset<T, KundeUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Kundes and returns the data updated in the database.
   * @param {KundeUpdateManyAndReturnArgs} args - Arguments to update many Kundes.
   * @example
   * // Update many Kundes
   * const kunde = await prisma.kunde.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Kundes and only return the `id`
   * const kundeWithIdOnly = await prisma.kunde.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends KundeUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, KundeUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$KundePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Kunde.
   * @param {KundeUpsertArgs} args - Arguments to update or create a Kunde.
   * @example
   * // Update or create a Kunde
   * const kunde = await prisma.kunde.upsert({
   *   create: {
   *     // ... data to create a Kunde
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Kunde we want to update
   *   }
   * })
   */
  upsert<T extends KundeUpsertArgs>(args: Prisma.SelectSubset<T, KundeUpsertArgs<ExtArgs>>): Prisma.Prisma__KundeClient<runtime.Types.Result.GetResult<Prisma.$KundePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Kundes.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {KundeCountArgs} args - Arguments to filter Kundes to count.
   * @example
   * // Count the number of Kundes
   * const count = await prisma.kunde.count({
   *   where: {
   *     // ... the filter for the Kundes we want to count
   *   }
   * })
  **/
  count<T extends KundeCountArgs>(
    args?: Prisma.Subset<T, KundeCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], KundeCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Kunde.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {KundeAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends KundeAggregateArgs>(args: Prisma.Subset<T, KundeAggregateArgs>): Prisma.PrismaPromise<GetKundeAggregateType<T>>

  /**
   * Group by Kunde.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {KundeGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends KundeGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: KundeGroupByArgs['orderBy'] }
      : { orderBy?: KundeGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, KundeGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetKundeGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Kunde model
 */
readonly fields: KundeFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Kunde.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__KundeClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  entlehnungen<T extends Prisma.Kunde$entlehnungenArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Kunde$entlehnungenArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$EntlehnungPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Kunde model
 */
export interface KundeFieldRefs {
  readonly id: Prisma.FieldRef<"Kunde", 'Int'>
  readonly name: Prisma.FieldRef<"Kunde", 'String'>
  readonly email: Prisma.FieldRef<"Kunde", 'String'>
}
    

// Custom InputTypes
/**
 * Kunde findUnique
 */
export type KundeFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Kunde
   */
  select?: Prisma.KundeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Kunde
   */
  omit?: Prisma.KundeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KundeInclude<ExtArgs> | null
  /**
   * Filter, which Kunde to fetch.
   */
  where: Prisma.KundeWhereUniqueInput
}

/**
 * Kunde findUniqueOrThrow
 */
export type KundeFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Kunde
   */
  select?: Prisma.KundeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Kunde
   */
  omit?: Prisma.KundeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KundeInclude<ExtArgs> | null
  /**
   * Filter, which Kunde to fetch.
   */
  where: Prisma.KundeWhereUniqueInput
}

/**
 * Kunde findFirst
 */
export type KundeFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Kunde
   */
  select?: Prisma.KundeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Kunde
   */
  omit?: Prisma.KundeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KundeInclude<ExtArgs> | null
  /**
   * Filter, which Kunde to fetch.
   */
  where?: Prisma.KundeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Kundes to fetch.
   */
  orderBy?: Prisma.KundeOrderByWithRelationInput | Prisma.KundeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Kundes.
   */
  cursor?: Prisma.KundeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Kundes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Kundes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Kundes.
   */
  distinct?: Prisma.KundeScalarFieldEnum | Prisma.KundeScalarFieldEnum[]
}

/**
 * Kunde findFirstOrThrow
 */
export type KundeFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Kunde
   */
  select?: Prisma.KundeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Kunde
   */
  omit?: Prisma.KundeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KundeInclude<ExtArgs> | null
  /**
   * Filter, which Kunde to fetch.
   */
  where?: Prisma.KundeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Kundes to fetch.
   */
  orderBy?: Prisma.KundeOrderByWithRelationInput | Prisma.KundeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Kundes.
   */
  cursor?: Prisma.KundeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Kundes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Kundes.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Kundes.
   */
  distinct?: Prisma.KundeScalarFieldEnum | Prisma.KundeScalarFieldEnum[]
}

/**
 * Kunde findMany
 */
export type KundeFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Kunde
   */
  select?: Prisma.KundeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Kunde
   */
  omit?: Prisma.KundeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KundeInclude<ExtArgs> | null
  /**
   * Filter, which Kundes to fetch.
   */
  where?: Prisma.KundeWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Kundes to fetch.
   */
  orderBy?: Prisma.KundeOrderByWithRelationInput | Prisma.KundeOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Kundes.
   */
  cursor?: Prisma.KundeWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Kundes from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Kundes.
   */
  skip?: number
  distinct?: Prisma.KundeScalarFieldEnum | Prisma.KundeScalarFieldEnum[]
}

/**
 * Kunde create
 */
export type KundeCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Kunde
   */
  select?: Prisma.KundeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Kunde
   */
  omit?: Prisma.KundeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KundeInclude<ExtArgs> | null
  /**
   * The data needed to create a Kunde.
   */
  data: Prisma.XOR<Prisma.KundeCreateInput, Prisma.KundeUncheckedCreateInput>
}

/**
 * Kunde createMany
 */
export type KundeCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Kundes.
   */
  data: Prisma.KundeCreateManyInput | Prisma.KundeCreateManyInput[]
}

/**
 * Kunde createManyAndReturn
 */
export type KundeCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Kunde
   */
  select?: Prisma.KundeSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Kunde
   */
  omit?: Prisma.KundeOmit<ExtArgs> | null
  /**
   * The data used to create many Kundes.
   */
  data: Prisma.KundeCreateManyInput | Prisma.KundeCreateManyInput[]
}

/**
 * Kunde update
 */
export type KundeUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Kunde
   */
  select?: Prisma.KundeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Kunde
   */
  omit?: Prisma.KundeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KundeInclude<ExtArgs> | null
  /**
   * The data needed to update a Kunde.
   */
  data: Prisma.XOR<Prisma.KundeUpdateInput, Prisma.KundeUncheckedUpdateInput>
  /**
   * Choose, which Kunde to update.
   */
  where: Prisma.KundeWhereUniqueInput
}

/**
 * Kunde updateMany
 */
export type KundeUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Kundes.
   */
  data: Prisma.XOR<Prisma.KundeUpdateManyMutationInput, Prisma.KundeUncheckedUpdateManyInput>
  /**
   * Filter which Kundes to update
   */
  where?: Prisma.KundeWhereInput
  /**
   * Limit how many Kundes to update.
   */
  limit?: number
}

/**
 * Kunde updateManyAndReturn
 */
export type KundeUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Kunde
   */
  select?: Prisma.KundeSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Kunde
   */
  omit?: Prisma.KundeOmit<ExtArgs> | null
  /**
   * The data used to update Kundes.
   */
  data: Prisma.XOR<Prisma.KundeUpdateManyMutationInput, Prisma.KundeUncheckedUpdateManyInput>
  /**
   * Filter which Kundes to update
   */
  where?: Prisma.KundeWhereInput
  /**
   * Limit how many Kundes to update.
   */
  limit?: number
}

/**
 * Kunde upsert
 */
export type KundeUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Kunde
   */
  select?: Prisma.KundeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Kunde
   */
  omit?: Prisma.KundeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KundeInclude<ExtArgs> | null
  /**
   * The filter to search for the Kunde to update in case it exists.
   */
  where: Prisma.KundeWhereUniqueInput
  /**
   * In case the Kunde found by the `where` argument doesn't exist, create a new Kunde with this data.
   */
  create: Prisma.XOR<Prisma.KundeCreateInput, Prisma.KundeUncheckedCreateInput>
  /**
   * In case the Kunde was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.KundeUpdateInput, Prisma.KundeUncheckedUpdateInput>
}

/**
 * Kunde delete
 */
export type KundeDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Kunde
   */
  select?: Prisma.KundeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Kunde
   */
  omit?: Prisma.KundeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KundeInclude<ExtArgs> | null
  /**
   * Filter which Kunde to delete.
   */
  where: Prisma.KundeWhereUniqueInput
}

/**
 * Kunde deleteMany
 */
export type KundeDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Kundes to delete
   */
  where?: Prisma.KundeWhereInput
  /**
   * Limit how many Kundes to delete.
   */
  limit?: number
}

/**
 * Kunde.entlehnungen
 */
export type Kunde$entlehnungenArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Entlehnung
   */
  select?: Prisma.EntlehnungSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Entlehnung
   */
  omit?: Prisma.EntlehnungOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.EntlehnungInclude<ExtArgs> | null
  where?: Prisma.EntlehnungWhereInput
  orderBy?: Prisma.EntlehnungOrderByWithRelationInput | Prisma.EntlehnungOrderByWithRelationInput[]
  cursor?: Prisma.EntlehnungWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.EntlehnungScalarFieldEnum | Prisma.EntlehnungScalarFieldEnum[]
}

/**
 * Kunde without action
 */
export type KundeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Kunde
   */
  select?: Prisma.KundeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Kunde
   */
  omit?: Prisma.KundeOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KundeInclude<ExtArgs> | null
}
