
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the client.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/library"
import type * as Prisma from "../models.ts"
import { type PrismaClient } from "./class.ts"

export type * from '../models.ts'

export type DMMF = typeof runtime.DMMF

export type PrismaPromise<T> = runtime.Types.Public.PrismaPromise<T>

/**
 * Prisma Errors
 */

export const PrismaClientKnownRequestError = runtime.PrismaClientKnownRequestError
export type PrismaClientKnownRequestError = runtime.PrismaClientKnownRequestError

export const PrismaClientUnknownRequestError = runtime.PrismaClientUnknownRequestError
export type PrismaClientUnknownRequestError = runtime.PrismaClientUnknownRequestError

export const PrismaClientRustPanicError = runtime.PrismaClientRustPanicError
export type PrismaClientRustPanicError = runtime.PrismaClientRustPanicError

export const PrismaClientInitializationError = runtime.PrismaClientInitializationError
export type PrismaClientInitializationError = runtime.PrismaClientInitializationError

export const PrismaClientValidationError = runtime.PrismaClientValidationError
export type PrismaClientValidationError = runtime.PrismaClientValidationError

/**
 * Re-export of sql-template-tag
 */
export const sql = runtime.sqltag
export const empty = runtime.empty
export const join = runtime.join
export const raw = runtime.raw
export const Sql = runtime.Sql
export type Sql = runtime.Sql



/**
 * Decimal.js
 */
export const Decimal = runtime.Decimal
export type Decimal = runtime.Decimal

export type DecimalJsLike = runtime.DecimalJsLike

/**
 * Metrics
 */
export type Metrics = runtime.Metrics
export type Metric<T> = runtime.Metric<T>
export type MetricHistogram = runtime.MetricHistogram
export type MetricHistogramBucket = runtime.MetricHistogramBucket

/**
* Extensions
*/
export type Extension = runtime.Types.Extensions.UserArgs
export const getExtensionContext = runtime.Extensions.getExtensionContext
export type Args<T, F extends runtime.Operation> = runtime.Types.Public.Args<T, F>
export type Payload<T, F extends runtime.Operation = never> = runtime.Types.Public.Payload<T, F>
export type Result<T, A, F extends runtime.Operation> = runtime.Types.Public.Result<T, A, F>
export type Exact<A, W> = runtime.Types.Public.Exact<A, W>

export type PrismaVersion = {
  client: string
  engine: string
}

/**
 * Prisma Client JS version: 6.19.2
 * Query Engine version: c2990dca591cba766e3b7ef5d9e8a84796e47ab7
 */
export const prismaVersion: PrismaVersion = {
  client: "6.19.2",
  engine: "c2990dca591cba766e3b7ef5d9e8a84796e47ab7"
}

/**
 * Utility Types
 */

export type Bytes = runtime.Bytes
export type JsonObject = runtime.JsonObject
export type JsonArray = runtime.JsonArray
export type JsonValue = runtime.JsonValue
export type InputJsonObject = runtime.InputJsonObject
export type InputJsonArray = runtime.InputJsonArray
export type InputJsonValue = runtime.InputJsonValue


export const NullTypes = {
  DbNull: runtime.objectEnumValues.classes.DbNull as (new (secret: never) => typeof runtime.objectEnumValues.instances.DbNull),
  JsonNull: runtime.objectEnumValues.classes.JsonNull as (new (secret: never) => typeof runtime.objectEnumValues.instances.JsonNull),
  AnyNull: runtime.objectEnumValues.classes.AnyNull as (new (secret: never) => typeof runtime.objectEnumValues.instances.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.objectEnumValues.instances.DbNull
/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.objectEnumValues.instances.JsonNull
/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.objectEnumValues.instances.AnyNull


type SelectAndInclude = {
  select: any
  include: any
}

type SelectAndOmit = {
  select: any
  omit: any
}

/**
 * From T, pick a set of properties whose keys are in the union K
 */
type Prisma__Pick<T, K extends keyof T> = {
    [P in K]: T[P];
};

export type Enumerable<T> = T | Array<T>;

/**
 * Subset
 * @desc From `T` pick properties that exist in `U`. Simple version of Intersection
 */
export type Subset<T, U> = {
  [key in keyof T]: key extends keyof U ? T[key] : never;
};

/**
 * SelectSubset
 * @desc From `T` pick properties that exist in `U`. Simple version of Intersection.
 * Additionally, it validates, if both select and include are present. If the case, it errors.
 */
export type SelectSubset<T, U> = {
  [key in keyof T]: key extends keyof U ? T[key] : never
} &
  (T extends SelectAndInclude
    ? 'Please either choose `select` or `include`.'
    : T extends SelectAndOmit
      ? 'Please either choose `select` or `omit`.'
      : {})

/**
 * Subset + Intersection
 * @desc From `T` pick properties that exist in `U` and intersect `K`
 */
export type SubsetIntersection<T, U, K> = {
  [key in keyof T]: key extends keyof U ? T[key] : never
} &
  K

type Without<T, U> = { [P in Exclude<keyof T, keyof U>]?: never };

/**
 * XOR is needed to have a real mutually exclusive union type
 * https://stackoverflow.com/questions/42123407/does-typescript-support-mutually-exclusive-types
 */
export type XOR<T, U> =
  T extends object ?
  U extends object ?
    (Without<T, U> & U) | (Without<U, T> & T)
  : U : T


/**
 * Is T a Record?
 */
type IsObject<T extends any> = T extends Array<any>
? False
: T extends Date
? False
: T extends Uint8Array
? False
: T extends BigInt
? False
: T extends object
? True
: False


/**
 * If it's T[], return T
 */
export type UnEnumerate<T extends unknown> = T extends Array<infer U> ? U : T

/**
 * From ts-toolbelt
 */

type __Either<O extends object, K extends Key> = Omit<O, K> &
  {
    // Merge all but K
    [P in K]: Prisma__Pick<O, P & keyof O> // With K possibilities
  }[K]

type EitherStrict<O extends object, K extends Key> = Strict<__Either<O, K>>

type EitherLoose<O extends object, K extends Key> = ComputeRaw<__Either<O, K>>

type _Either<
  O extends object,
  K extends Key,
  strict extends Boolean
> = {
  1: EitherStrict<O, K>
  0: EitherLoose<O, K>
}[strict]

export type Either<
  O extends object,
  K extends Key,
  strict extends Boolean = 1
> = O extends unknown ? _Either<O, K, strict> : never

export type Union = any

export type PatchUndefined<O extends object, O1 extends object> = {
  [K in keyof O]: O[K] extends undefined ? At<O1, K> : O[K]
} & {}

/** Helper Types for "Merge" **/
export type IntersectOf<U extends Union> = (
  U extends unknown ? (k: U) => void : never
) extends (k: infer I) => void
  ? I
  : never

export type Overwrite<O extends object, O1 extends object> = {
    [K in keyof O]: K extends keyof O1 ? O1[K] : O[K];
} & {};

type _Merge<U extends object> = IntersectOf<Overwrite<U, {
    [K in keyof U]-?: At<U, K>;
}>>;

type Key = string | number | symbol;
type AtStrict<O extends object, K extends Key> = O[K & keyof O];
type AtLoose<O extends object, K extends Key> = O extends unknown ? AtStrict<O, K> : never;
export type At<O extends object, K extends Key, strict extends Boolean = 1> = {
    1: AtStrict<O, K>;
    0: AtLoose<O, K>;
}[strict];

export type ComputeRaw<A extends any> = A extends Function ? A : {
  [K in keyof A]: A[K];
} & {};

export type OptionalFlat<O> = {
  [K in keyof O]?: O[K];
} & {};

type _Record<K extends keyof any, T> = {
  [P in K]: T;
};

// cause typescript not to expand types and preserve names
type NoExpand<T> = T extends unknown ? T : never;

// this type assumes the passed object is entirely optional
export type AtLeast<O extends object, K extends string> = NoExpand<
  O extends unknown
  ? | (K extends keyof O ? { [P in K]: O[P] } & O : O)
    | {[P in keyof O as P extends K ? P : never]-?: O[P]} & O
  : never>;

type _Strict<U, _U = U> = U extends unknown ? U & OptionalFlat<_Record<Exclude<Keys<_U>, keyof U>, never>> : never;

export type Strict<U extends object> = ComputeRaw<_Strict<U>>;
/** End Helper Types for "Merge" **/

export type Merge<U extends object> = ComputeRaw<_Merge<Strict<U>>>;

export type Boolean = True | False

export type True = 1

export type False = 0

export type Not<B extends Boolean> = {
  0: 1
  1: 0
}[B]

export type Extends<A1 extends any, A2 extends any> = [A1] extends [never]
  ? 0 // anything `never` is false
  : A1 extends A2
  ? 1
  : 0

export type Has<U extends Union, U1 extends Union> = Not<
  Extends<Exclude<U1, U>, U1>
>

export type Or<B1 extends Boolean, B2 extends Boolean> = {
  0: {
    0: 0
    1: 1
  }
  1: {
    0: 1
    1: 1
  }
}[B1][B2]

export type Keys<U extends Union> = U extends unknown ? keyof U : never

export type GetScalarType<T, O> = O extends object ? {
  [P in keyof T]: P extends keyof O
    ? O[P]
    : never
} : never

type FieldPaths<
  T,
  U = Omit<T, '_avg' | '_sum' | '_count' | '_min' | '_max'>
> = IsObject<T> extends True ? U : T

export type GetHavingFields<T> = {
  [K in keyof T]: Or<
    Or<Extends<'OR', K>, Extends<'AND', K>>,
    Extends<'NOT', K>
  > extends True
    ? // infer is only needed to not hit TS limit
      // based on the brilliant idea of Pierre-Antoine Mills
      // https://github.com/microsoft/TypeScript/issues/30188#issuecomment-478938437
      T[K] extends infer TK
      ? GetHavingFields<UnEnumerate<TK> extends object ? Merge<UnEnumerate<TK>> : never>
      : never
    : {} extends FieldPaths<T[K]>
    ? never
    : K
}[keyof T]

/**
 * Convert tuple to union
 */
type _TupleToUnion<T> = T extends (infer E)[] ? E : never
type TupleToUnion<K extends readonly any[]> = _TupleToUnion<K>
export type MaybeTupleToUnion<T> = T extends any[] ? TupleToUnion<T> : T

/**
 * Like `Pick`, but additionally can also accept an array of keys
 */
export type PickEnumerable<T, K extends Enumerable<keyof T> | keyof T> = Prisma__Pick<T, MaybeTupleToUnion<K>>

/**
 * Exclude all keys with underscores
 */
export type ExcludeUnderscoreKeys<T extends string> = T extends `_${string}` ? never : T


export type FieldRef<Model, FieldType> = runtime.FieldRef<Model, FieldType>

type FieldRefInputType<Model, FieldType> = Model extends never ? never : FieldRef<Model, FieldType>


export const ModelName = {
  Filiale: 'Filiale',
  Abteilung: 'Abteilung',
  Mitarbeiter: 'Mitarbeiter',
  Buch: 'Buch',
  Exemplar: 'Exemplar',
  Kunde: 'Kunde',
  Entlehnung: 'Entlehnung'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]



export interface TypeMapCb<GlobalOmitOptions = {}> extends runtime.Types.Utils.Fn<{extArgs: runtime.Types.Extensions.InternalArgs }, runtime.Types.Utils.Record<string, any>> {
  returns: TypeMap<this['params']['extArgs'], GlobalOmitOptions>
}

export type TypeMap<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> = {
  globalOmitOptions: {
    omit: GlobalOmitOptions
  }
  meta: {
    modelProps: "filiale" | "abteilung" | "mitarbeiter" | "buch" | "exemplar" | "kunde" | "entlehnung"
    txIsolationLevel: TransactionIsolationLevel
  }
  model: {
    Filiale: {
      payload: Prisma.$FilialePayload<ExtArgs>
      fields: Prisma.FilialeFieldRefs
      operations: {
        findUnique: {
          args: Prisma.FilialeFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FilialePayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.FilialeFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FilialePayload>
        }
        findFirst: {
          args: Prisma.FilialeFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FilialePayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.FilialeFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FilialePayload>
        }
        findMany: {
          args: Prisma.FilialeFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FilialePayload>[]
        }
        create: {
          args: Prisma.FilialeCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FilialePayload>
        }
        createMany: {
          args: Prisma.FilialeCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.FilialeCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FilialePayload>[]
        }
        delete: {
          args: Prisma.FilialeDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FilialePayload>
        }
        update: {
          args: Prisma.FilialeUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FilialePayload>
        }
        deleteMany: {
          args: Prisma.FilialeDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.FilialeUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.FilialeUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FilialePayload>[]
        }
        upsert: {
          args: Prisma.FilialeUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$FilialePayload>
        }
        aggregate: {
          args: Prisma.FilialeAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateFiliale>
        }
        groupBy: {
          args: Prisma.FilialeGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.FilialeGroupByOutputType>[]
        }
        count: {
          args: Prisma.FilialeCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.FilialeCountAggregateOutputType> | number
        }
      }
    }
    Abteilung: {
      payload: Prisma.$AbteilungPayload<ExtArgs>
      fields: Prisma.AbteilungFieldRefs
      operations: {
        findUnique: {
          args: Prisma.AbteilungFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AbteilungPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.AbteilungFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AbteilungPayload>
        }
        findFirst: {
          args: Prisma.AbteilungFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AbteilungPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.AbteilungFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AbteilungPayload>
        }
        findMany: {
          args: Prisma.AbteilungFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AbteilungPayload>[]
        }
        create: {
          args: Prisma.AbteilungCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AbteilungPayload>
        }
        createMany: {
          args: Prisma.AbteilungCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.AbteilungCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AbteilungPayload>[]
        }
        delete: {
          args: Prisma.AbteilungDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AbteilungPayload>
        }
        update: {
          args: Prisma.AbteilungUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AbteilungPayload>
        }
        deleteMany: {
          args: Prisma.AbteilungDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.AbteilungUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.AbteilungUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AbteilungPayload>[]
        }
        upsert: {
          args: Prisma.AbteilungUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$AbteilungPayload>
        }
        aggregate: {
          args: Prisma.AbteilungAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateAbteilung>
        }
        groupBy: {
          args: Prisma.AbteilungGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AbteilungGroupByOutputType>[]
        }
        count: {
          args: Prisma.AbteilungCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AbteilungCountAggregateOutputType> | number
        }
      }
    }
    Mitarbeiter: {
      payload: Prisma.$MitarbeiterPayload<ExtArgs>
      fields: Prisma.MitarbeiterFieldRefs
      operations: {
        findUnique: {
          args: Prisma.MitarbeiterFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MitarbeiterPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.MitarbeiterFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MitarbeiterPayload>
        }
        findFirst: {
          args: Prisma.MitarbeiterFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MitarbeiterPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.MitarbeiterFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MitarbeiterPayload>
        }
        findMany: {
          args: Prisma.MitarbeiterFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MitarbeiterPayload>[]
        }
        create: {
          args: Prisma.MitarbeiterCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MitarbeiterPayload>
        }
        createMany: {
          args: Prisma.MitarbeiterCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.MitarbeiterCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MitarbeiterPayload>[]
        }
        delete: {
          args: Prisma.MitarbeiterDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MitarbeiterPayload>
        }
        update: {
          args: Prisma.MitarbeiterUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MitarbeiterPayload>
        }
        deleteMany: {
          args: Prisma.MitarbeiterDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.MitarbeiterUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.MitarbeiterUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MitarbeiterPayload>[]
        }
        upsert: {
          args: Prisma.MitarbeiterUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$MitarbeiterPayload>
        }
        aggregate: {
          args: Prisma.MitarbeiterAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateMitarbeiter>
        }
        groupBy: {
          args: Prisma.MitarbeiterGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.MitarbeiterGroupByOutputType>[]
        }
        count: {
          args: Prisma.MitarbeiterCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.MitarbeiterCountAggregateOutputType> | number
        }
      }
    }
    Buch: {
      payload: Prisma.$BuchPayload<ExtArgs>
      fields: Prisma.BuchFieldRefs
      operations: {
        findUnique: {
          args: Prisma.BuchFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BuchPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.BuchFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BuchPayload>
        }
        findFirst: {
          args: Prisma.BuchFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BuchPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.BuchFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BuchPayload>
        }
        findMany: {
          args: Prisma.BuchFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BuchPayload>[]
        }
        create: {
          args: Prisma.BuchCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BuchPayload>
        }
        createMany: {
          args: Prisma.BuchCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.BuchCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BuchPayload>[]
        }
        delete: {
          args: Prisma.BuchDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BuchPayload>
        }
        update: {
          args: Prisma.BuchUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BuchPayload>
        }
        deleteMany: {
          args: Prisma.BuchDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.BuchUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.BuchUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BuchPayload>[]
        }
        upsert: {
          args: Prisma.BuchUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BuchPayload>
        }
        aggregate: {
          args: Prisma.BuchAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateBuch>
        }
        groupBy: {
          args: Prisma.BuchGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.BuchGroupByOutputType>[]
        }
        count: {
          args: Prisma.BuchCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.BuchCountAggregateOutputType> | number
        }
      }
    }
    Exemplar: {
      payload: Prisma.$ExemplarPayload<ExtArgs>
      fields: Prisma.ExemplarFieldRefs
      operations: {
        findUnique: {
          args: Prisma.ExemplarFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ExemplarPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.ExemplarFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ExemplarPayload>
        }
        findFirst: {
          args: Prisma.ExemplarFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ExemplarPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.ExemplarFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ExemplarPayload>
        }
        findMany: {
          args: Prisma.ExemplarFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ExemplarPayload>[]
        }
        create: {
          args: Prisma.ExemplarCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ExemplarPayload>
        }
        createMany: {
          args: Prisma.ExemplarCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.ExemplarCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ExemplarPayload>[]
        }
        delete: {
          args: Prisma.ExemplarDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ExemplarPayload>
        }
        update: {
          args: Prisma.ExemplarUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ExemplarPayload>
        }
        deleteMany: {
          args: Prisma.ExemplarDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.ExemplarUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.ExemplarUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ExemplarPayload>[]
        }
        upsert: {
          args: Prisma.ExemplarUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ExemplarPayload>
        }
        aggregate: {
          args: Prisma.ExemplarAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateExemplar>
        }
        groupBy: {
          args: Prisma.ExemplarGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ExemplarGroupByOutputType>[]
        }
        count: {
          args: Prisma.ExemplarCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.ExemplarCountAggregateOutputType> | number
        }
      }
    }
    Kunde: {
      payload: Prisma.$KundePayload<ExtArgs>
      fields: Prisma.KundeFieldRefs
      operations: {
        findUnique: {
          args: Prisma.KundeFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KundePayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.KundeFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KundePayload>
        }
        findFirst: {
          args: Prisma.KundeFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KundePayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.KundeFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KundePayload>
        }
        findMany: {
          args: Prisma.KundeFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KundePayload>[]
        }
        create: {
          args: Prisma.KundeCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KundePayload>
        }
        createMany: {
          args: Prisma.KundeCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.KundeCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KundePayload>[]
        }
        delete: {
          args: Prisma.KundeDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KundePayload>
        }
        update: {
          args: Prisma.KundeUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KundePayload>
        }
        deleteMany: {
          args: Prisma.KundeDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.KundeUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.KundeUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KundePayload>[]
        }
        upsert: {
          args: Prisma.KundeUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$KundePayload>
        }
        aggregate: {
          args: Prisma.KundeAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateKunde>
        }
        groupBy: {
          args: Prisma.KundeGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.KundeGroupByOutputType>[]
        }
        count: {
          args: Prisma.KundeCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.KundeCountAggregateOutputType> | number
        }
      }
    }
    Entlehnung: {
      payload: Prisma.$EntlehnungPayload<ExtArgs>
      fields: Prisma.EntlehnungFieldRefs
      operations: {
        findUnique: {
          args: Prisma.EntlehnungFindUniqueArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$EntlehnungPayload> | null
        }
        findUniqueOrThrow: {
          args: Prisma.EntlehnungFindUniqueOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$EntlehnungPayload>
        }
        findFirst: {
          args: Prisma.EntlehnungFindFirstArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$EntlehnungPayload> | null
        }
        findFirstOrThrow: {
          args: Prisma.EntlehnungFindFirstOrThrowArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$EntlehnungPayload>
        }
        findMany: {
          args: Prisma.EntlehnungFindManyArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$EntlehnungPayload>[]
        }
        create: {
          args: Prisma.EntlehnungCreateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$EntlehnungPayload>
        }
        createMany: {
          args: Prisma.EntlehnungCreateManyArgs<ExtArgs>
          result: BatchPayload
        }
        createManyAndReturn: {
          args: Prisma.EntlehnungCreateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$EntlehnungPayload>[]
        }
        delete: {
          args: Prisma.EntlehnungDeleteArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$EntlehnungPayload>
        }
        update: {
          args: Prisma.EntlehnungUpdateArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$EntlehnungPayload>
        }
        deleteMany: {
          args: Prisma.EntlehnungDeleteManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateMany: {
          args: Prisma.EntlehnungUpdateManyArgs<ExtArgs>
          result: BatchPayload
        }
        updateManyAndReturn: {
          args: Prisma.EntlehnungUpdateManyAndReturnArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$EntlehnungPayload>[]
        }
        upsert: {
          args: Prisma.EntlehnungUpsertArgs<ExtArgs>
          result: runtime.Types.Utils.PayloadToResult<Prisma.$EntlehnungPayload>
        }
        aggregate: {
          args: Prisma.EntlehnungAggregateArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.AggregateEntlehnung>
        }
        groupBy: {
          args: Prisma.EntlehnungGroupByArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.EntlehnungGroupByOutputType>[]
        }
        count: {
          args: Prisma.EntlehnungCountArgs<ExtArgs>
          result: runtime.Types.Utils.Optional<Prisma.EntlehnungCountAggregateOutputType> | number
        }
      }
    }
  }
} & {
  other: {
    payload: any
    operations: {
      $executeRaw: {
        args: [query: TemplateStringsArray | Sql, ...values: any[]],
        result: any
      }
      $executeRawUnsafe: {
        args: [query: string, ...values: any[]],
        result: any
      }
      $queryRaw: {
        args: [query: TemplateStringsArray | Sql, ...values: any[]],
        result: any
      }
      $queryRawUnsafe: {
        args: [query: string, ...values: any[]],
        result: any
      }
    }
  }
}

/**
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const FilialeScalarFieldEnum = {
  id: 'id',
  name: 'name'
} as const

export type FilialeScalarFieldEnum = (typeof FilialeScalarFieldEnum)[keyof typeof FilialeScalarFieldEnum]


export const AbteilungScalarFieldEnum = {
  id: 'id',
  name: 'name',
  filialeId: 'filialeId'
} as const

export type AbteilungScalarFieldEnum = (typeof AbteilungScalarFieldEnum)[keyof typeof AbteilungScalarFieldEnum]


export const MitarbeiterScalarFieldEnum = {
  id: 'id',
  name: 'name',
  filialeId: 'filialeId'
} as const

export type MitarbeiterScalarFieldEnum = (typeof MitarbeiterScalarFieldEnum)[keyof typeof MitarbeiterScalarFieldEnum]


export const BuchScalarFieldEnum = {
  id: 'id',
  titel: 'titel',
  autor: 'autor',
  abteilungId: 'abteilungId'
} as const

export type BuchScalarFieldEnum = (typeof BuchScalarFieldEnum)[keyof typeof BuchScalarFieldEnum]


export const ExemplarScalarFieldEnum = {
  id: 'id',
  buchId: 'buchId',
  filialeId: 'filialeId'
} as const

export type ExemplarScalarFieldEnum = (typeof ExemplarScalarFieldEnum)[keyof typeof ExemplarScalarFieldEnum]


export const KundeScalarFieldEnum = {
  id: 'id',
  name: 'name',
  email: 'email'
} as const

export type KundeScalarFieldEnum = (typeof KundeScalarFieldEnum)[keyof typeof KundeScalarFieldEnum]


export const EntlehnungScalarFieldEnum = {
  id: 'id',
  kundeId: 'kundeId',
  exemplarId: 'exemplarId',
  mitarbeiterId: 'mitarbeiterId',
  entlehnungsDatum: 'entlehnungsDatum',
  rueckgabeDatum: 'rueckgabeDatum'
} as const

export type EntlehnungScalarFieldEnum = (typeof EntlehnungScalarFieldEnum)[keyof typeof EntlehnungScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]



/**
 * Field references
 */


/**
 * Reference to a field of type 'Int'
 */
export type IntFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Int'>
    


/**
 * Reference to a field of type 'String'
 */
export type StringFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'String'>
    


/**
 * Reference to a field of type 'DateTime'
 */
export type DateTimeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'DateTime'>
    


/**
 * Reference to a field of type 'Float'
 */
export type FloatFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Float'>
    

/**
 * Batch Payload for updateMany & deleteMany & createMany
 */
export type BatchPayload = {
  count: number
}


export type Datasource = {
  url?: string
}
export type Datasources = {
  db?: Datasource
}

export const defineExtension = runtime.Extensions.defineExtension as unknown as runtime.Types.Extensions.ExtendsHook<"define", TypeMapCb, runtime.Types.Extensions.DefaultArgs>
export type DefaultPrismaClient = PrismaClient
export type ErrorFormat = 'pretty' | 'colorless' | 'minimal'
export interface PrismaClientOptions {
  /**
   * Overwrites the datasource url from your schema.prisma file
   */
  datasources?: Datasources
  /**
   * Overwrites the datasource url from your schema.prisma file
   */
  datasourceUrl?: string
  /**
   * @default "colorless"
   */
  errorFormat?: ErrorFormat
  /**
   * @example
   * ```
   * // Shorthand for `emit: 'stdout'`
   * log: ['query', 'info', 'warn', 'error']
   * 
   * // Emit as events only
   * log: [
   *   { emit: 'event', level: 'query' },
   *   { emit: 'event', level: 'info' },
   *   { emit: 'event', level: 'warn' }
   *   { emit: 'event', level: 'error' }
   * ]
   * 
   * / Emit as events and log to stdout
   * og: [
   *  { emit: 'stdout', level: 'query' },
   *  { emit: 'stdout', level: 'info' },
   *  { emit: 'stdout', level: 'warn' }
   *  { emit: 'stdout', level: 'error' }
   * 
   * ```
   * Read more in our [docs](https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-client/logging#the-log-option).
   */
  log?: (LogLevel | LogDefinition)[]
  /**
   * The default values for transactionOptions
   * maxWait ?= 2000
   * timeout ?= 5000
   */
  transactionOptions?: {
    maxWait?: number
    timeout?: number
    isolationLevel?: TransactionIsolationLevel
  }
  /**
   * Instance of a Driver Adapter, e.g., like one provided by `@prisma/adapter-planetscale`
   */
  adapter?: runtime.SqlDriverAdapterFactory | null
  /**
   * Global configuration for omitting model fields by default.
   * 
   * @example
   * ```
   * const prisma = new PrismaClient({
   *   omit: {
   *     user: {
   *       password: true
   *     }
   *   }
   * })
   * ```
   */
  omit?: GlobalOmitConfig
}
export type GlobalOmitConfig = {
  filiale?: Prisma.FilialeOmit
  abteilung?: Prisma.AbteilungOmit
  mitarbeiter?: Prisma.MitarbeiterOmit
  buch?: Prisma.BuchOmit
  exemplar?: Prisma.ExemplarOmit
  kunde?: Prisma.KundeOmit
  entlehnung?: Prisma.EntlehnungOmit
}

/* Types for Logging */
export type LogLevel = 'info' | 'query' | 'warn' | 'error'
export type LogDefinition = {
  level: LogLevel
  emit: 'stdout' | 'event'
}

export type CheckIsLogLevel<T> = T extends LogLevel ? T : never;

export type GetLogType<T> = CheckIsLogLevel<
  T extends LogDefinition ? T['level'] : T
>;

export type GetEvents<T extends any[]> = T extends Array<LogLevel | LogDefinition>
  ? GetLogType<T[number]>
  : never;

export type QueryEvent = {
  timestamp: Date
  query: string
  params: string
  duration: number
  target: string
}

export type LogEvent = {
  timestamp: Date
  message: string
  target: string
}
/* End Types for Logging */


export type PrismaAction =
  | 'findUnique'
  | 'findUniqueOrThrow'
  | 'findMany'
  | 'findFirst'
  | 'findFirstOrThrow'
  | 'create'
  | 'createMany'
  | 'createManyAndReturn'
  | 'update'
  | 'updateMany'
  | 'updateManyAndReturn'
  | 'upsert'
  | 'delete'
  | 'deleteMany'
  | 'executeRaw'
  | 'queryRaw'
  | 'aggregate'
  | 'count'
  | 'runCommandRaw'
  | 'findRaw'
  | 'groupBy'

/**
 * `PrismaClient` proxy available in interactive transactions.
 */
export type TransactionClient = Omit<DefaultPrismaClient, runtime.ITXClientDenyList>

