
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models.ts'
export type * from './prismaNamespace.ts'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.objectEnumValues.classes.DbNull as (new (secret: never) => typeof runtime.objectEnumValues.instances.DbNull),
  JsonNull: runtime.objectEnumValues.classes.JsonNull as (new (secret: never) => typeof runtime.objectEnumValues.instances.JsonNull),
  AnyNull: runtime.objectEnumValues.classes.AnyNull as (new (secret: never) => typeof runtime.objectEnumValues.instances.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.objectEnumValues.instances.DbNull
/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.objectEnumValues.instances.JsonNull
/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.objectEnumValues.instances.AnyNull


export const ModelName = {
  Filiale: 'Filiale',
  Abteilung: 'Abteilung',
  Mitarbeiter: 'Mitarbeiter',
  Buch: 'Buch',
  Exemplar: 'Exemplar',
  Kunde: 'Kunde',
  Entlehnung: 'Entlehnung'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const FilialeScalarFieldEnum = {
  id: 'id',
  name: 'name'
} as const

export type FilialeScalarFieldEnum = (typeof FilialeScalarFieldEnum)[keyof typeof FilialeScalarFieldEnum]


export const AbteilungScalarFieldEnum = {
  id: 'id',
  name: 'name',
  filialeId: 'filialeId'
} as const

export type AbteilungScalarFieldEnum = (typeof AbteilungScalarFieldEnum)[keyof typeof AbteilungScalarFieldEnum]


export const MitarbeiterScalarFieldEnum = {
  id: 'id',
  name: 'name',
  filialeId: 'filialeId'
} as const

export type MitarbeiterScalarFieldEnum = (typeof MitarbeiterScalarFieldEnum)[keyof typeof MitarbeiterScalarFieldEnum]


export const BuchScalarFieldEnum = {
  id: 'id',
  titel: 'titel',
  autor: 'autor',
  abteilungId: 'abteilungId'
} as const

export type BuchScalarFieldEnum = (typeof BuchScalarFieldEnum)[keyof typeof BuchScalarFieldEnum]


export const ExemplarScalarFieldEnum = {
  id: 'id',
  buchId: 'buchId',
  filialeId: 'filialeId'
} as const

export type ExemplarScalarFieldEnum = (typeof ExemplarScalarFieldEnum)[keyof typeof ExemplarScalarFieldEnum]


export const KundeScalarFieldEnum = {
  id: 'id',
  name: 'name',
  email: 'email'
} as const

export type KundeScalarFieldEnum = (typeof KundeScalarFieldEnum)[keyof typeof KundeScalarFieldEnum]


export const EntlehnungScalarFieldEnum = {
  id: 'id',
  kundeId: 'kundeId',
  exemplarId: 'exemplarId',
  mitarbeiterId: 'mitarbeiterId',
  entlehnungsDatum: 'entlehnungsDatum',
  rueckgabeDatum: 'rueckgabeDatum'
} as const

export type EntlehnungScalarFieldEnum = (typeof EntlehnungScalarFieldEnum)[keyof typeof EntlehnungScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]

