
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This is a barrel export file for all models and their related types.
 *
 * 🟢 You can import this file directly.
 */
export type * from './models/Filiale.ts'
export type * from './models/Abteilung.ts'
export type * from './models/Mitarbeiter.ts'
export type * from './models/Buch.ts'
export type * from './models/Exemplar.ts'
export type * from './models/Kunde.ts'
export type * from './models/Entlehnung.ts'
export type * from './commonInputTypes.ts'